type ResearchSpec = {
  slug: string; title: string; excerpt: string; subject: string; unit: string;
  finding: string; source: string; sourceLinks: string[]; evidence: string;
  field: string; boundary: string; published: '2026-08-14';
};

const makeBody = (s: ResearchSpec): readonly string[] => [
  `Scope and question. This research examines ${s.subject} as a bounded administrative work lane for a small business. The unit of analysis is one ${s.unit}. That choice prevents a loose activity count from being mistaken for a reliable result. The practical question is whether a reviewer can see what happened, reproduce the record from its source, and identify the next decision without giving away authority that belongs to the business owner. This is a study design for an individual business, not a claim about every provider, sector, or software system.`,
  `Finding. ${s.finding} The useful outcome is not a larger queue by itself. It is a record that is complete enough to review, accurate enough to act on, and explicit about uncertainty. A fast entry that hides a missing source can create more work later. A slower entry that identifies the exact gap may be the better result when the item could affect a customer, a supplier, money, privacy, or a public promise.`,
  `Evidence base. ${s.source} These sources provide guidance and control principles, not a measured performance result for an outside specialist. The individual business still needs its own sample. Record the source document, observation date, reviewer, and rule used for classification. Keep source links beside the record rather than collecting them later from memory. ${s.sourceLinks.join(' and ')} should be read in its current form before the business relies on a legal, tax, privacy, security, or sector-specific conclusion.`,
  `Research design. Use a defined collection period, such as ten business days, and state the intake boundary before collecting observations. Count received items, items with enough evidence to classify, items corrected after review, items escalated, and items still open. Preserve the denominator. If 42 of 50 records pass the first review, report 84 percent and show the eight exceptions. A count of 42 completed items without the 50-item denominator says little about the result.`,
  `Record structure. Each ${s.unit} should carry a stable identifier, source location, received or observed date, current status, responsible queue, next action, and reviewer disposition. Add the topic-specific field ${s.field}. Record the value as observed, reported, or inferred, and do not mix those categories. A missing field and a wrong field are different defects. The first suggests unavailable evidence; the second suggests a classification or interpretation problem.`,
  `Comparison. Compare like with like. Use the same definition of ${s.unit}, the same business-hours convention, and the same policy or source version when possible. Report the period, sample size, exclusions, and any change in channel, demand, staffing, or system. Medians can help when a few long-running cases distort the average, but neither statistic explains quality on its own. Pair time measures with correction, escalation, and aging counts.`,
  `Topic-specific test. For ${s.subject}, a passing record should answer four questions: what source was checked, what fact was observed, what rule was applied, and what remains undecided. The reviewer should be able to distinguish a routine match from a conflict. ${s.evidence} That distinction matters because an unresolved item is not evidence of failure when the record makes the unresolved point visible and routes it to the right owner.`,
  `Role boundary. Outside support can prepare a record, compare stated information with an approved source, flag a discrepancy, and draft a neutral note. The owner or named manager should retain decisions involving ${s.boundary}. This division is about authority and accountability, not a judgment about a person’s skill. The work instruction should say what the preparer may do, what requires approval, and where the item goes when the source is incomplete.`,
  `Review method. During the first sample, inspect every item or use a documented review plan that covers all high-risk categories. Once the lane is stable, sample ordinary items and review every item marked sensitive, disputed, unusual, or outside the documented rule. A sample is not a magic number. Increase it when the business sees repeated corrections, a source-system change, or a serious error. Reduce it only when dated records support the decision.`,
  `Interpretation. A falling backlog can hide a rise in misclassification if difficult items are closed or moved without resolution. The report should therefore show open age, reopened cases, correction reasons, and owner interventions beside throughput. Keep observation separate from interpretation. For example, a source may show that a date is present; it does not by itself prove that the date is still valid, that the document is authentic, or that a business decision should follow.`,
  `Access and privacy. Grant only the access needed to locate, read, or prepare the record. Named accounts and multifactor authentication reduce ambiguity where the system supports them. Do not export a broad customer, supplier, or employee file to answer a narrow question. Keep the source in the approved system, limit copied data, and record any access exception. Review access when the work changes and remove it when the approved scope ends.`,
  `Limitations. This is operational research, not a randomized experiment, audit opinion, legal opinion, tax advice, or market-wide performance study. Ten business days may miss seasonal demand, monthly reconciliation, unusual complaints, or a rare high-impact event. A source can be stale or incomplete. Results from one company should not be generalized without checking its data sensitivity, service promise, channel mix, review capacity, and applicable rules. Ask a qualified adviser about questions outside routine record preparation.`,
  `Decision rule. Before the first handoff, set a quality floor and a stop condition. A useful rule names the denominator, the period, the severity of an error, and the person who decides. For example, the owner might require every high-risk case to be escalated, pause expansion after a material unsupported entry, and require a written explanation for each reopened item. The exact threshold belongs to the business. The important point is that it exists before results are selected.`,
  `Practical conclusion. Start with one narrow lane and keep the first sample reversible. Define ${s.unit}, preserve the source, record the topic-specific field, and name the next decision owner. Expand only when the business can explain what improved, what remained uncertain, and how a correction would be made. A measured handoff should reduce avoidable coordination work while preserving the business’s ability to inspect the evidence, change the scope, and recover control of the records.`,
  `Review questions. What exactly is being counted? Which source proves the status? How many records passed without correction? Which exception category is growing? Which field is most often missing? Did review time fall, or did work move into a later correction queue? What action is allowed without approval? What must stop until an owner decides? What evidence would cause the business to narrow the work lane again? Keeping these answers with the sample makes the conclusion auditable.`,
  `Final assessment. The evidence supports a conditional, bounded handoff when inputs are identifiable, the finish condition is visible, access is limited, and judgment-heavy cases have a named escalation path. It does not support treating completion volume as proof of quality. For ${s.subject}, the owner should accept the lane only if its own dated records show acceptable accuracy, manageable review effort, and an honest account of exceptions.`,
];

const specs: ResearchSpec[] = [
  {slug:'august-14-research-inventory-variance-evidence',title:'Research: Inventory Variance Evidence Before Outsourcing Stock Records',excerpt:'A bounded method for checking stock-count differences without turning preparation into an inventory adjustment or valuation decision.',subject:'inventory variance evidence',unit:'stock-count observation',finding:'Inventory record preparation is most useful when observed counts, item identity, location, unit of measure, and source history remain visible beside each variance.',source:'The SBA Business Guide describes day-to-day management and financial review as business responsibilities; NIST CSF 2.0 offers a risk-based approach to identifying assets and protecting records.',sourceLinks:['https://www.sba.gov/business-guide/manage-your-business','https://www.nist.gov/cyberframework'],evidence:'A quantity difference can come from timing, unit conversion, damage, location, or a genuine record error, so the difference should be reported before it is “fixed.”',field:'count method, unit of measure, and count location',boundary:'inventory adjustments, valuation, purchasing, and disposal',published:'2026-08-14'},
  {slug:'august-14-research-contract-renewal-date-tracking',title:'Research: Contract Renewal Date Tracking With Source Control',excerpt:'How small businesses can prepare renewal records while leaving interpretation, negotiation, and termination decisions with the owner.',subject:'contract renewal date tracking',unit:'agreement date record',finding:'Renewal tracking is reliable when every date is tied to the correct agreement version and its source wording, instead of being copied into a calendar without context.',source:'NIST CSF 2.0 supports identifying information assets and business dependencies; the SBA Business Guide places planning and day-to-day management with the business.',sourceLinks:['https://www.nist.gov/cyberframework','https://www.sba.gov/business-guide'],evidence:'A displayed renewal date does not prove that notice requirements, automatic renewal language, or the current counterparty relationship have been interpreted correctly.',field:'agreement version, date label, and notice source',boundary:'legal interpretation, negotiation, acceptance of terms, and termination',published:'2026-08-14'},
  {slug:'august-14-research-customer-consent-record-completeness',title:'Research: Customer Consent Record Completeness in Outsourced Administration',excerpt:'A research model for preserving what a customer agreed to, where it came from, and what remains uncertain.',subject:'customer consent record completeness',unit:'consent-related record',finding:'Consent records are more reviewable when the original wording, channel, timestamp, purpose, and applicable business rule are preserved without treating silence or an old record as fresh permission.',source:'FTC business guidance covers privacy and security responsibilities and warns businesses to consider how customer information is handled; NIST CSF 2.0 provides a risk-management lens for protecting information.',sourceLinks:['https://www.ftc.gov/business-guidance','https://www.nist.gov/itl/smallbusinesscyber/nist-cybersecurity-framework-0'],evidence:'A complete timestamp is not the same as proof that the stated purpose, audience, or scope matched the later use.',field:'purpose, source channel, timestamp, and exact customer wording',boundary:'consent interpretation, policy changes, sensitive-data use, and outreach decisions',published:'2026-08-14'},
  {slug:'august-14-research-supplier-invoice-match-review',title:'Research: Supplier Invoice Match Review for Small Businesses',excerpt:'How to prepare invoice evidence for review without approving payment or concealing a disputed supplier charge.',subject:'supplier invoice matching',unit:'supplier invoice case',finding:'Invoice preparation adds value when the invoice, purchase record, receipt evidence, supplier identity, and discrepancy reason can be reviewed together.',source:'IRS Publication 583 explains the role of supporting records in business recordkeeping; SBA financial guidance emphasizes regular review and categorization of business finances.',sourceLinks:['https://www.irs.gov/publications/p583','https://www.sba.gov/business-guide/manage-your-business/manage-your-finances'],evidence:'A matched amount can still belong to the wrong supplier, period, tax treatment, or purchase, so amount agreement alone is not a payment approval.',field:'purchase reference, receipt evidence, accounting period, and discrepancy type',boundary:'payment release, tax treatment, disputed charges, and supplier concessions',published:'2026-08-14'},
  {slug:'august-14-research-appointment-no-show-evidence',title:'Research: Appointment No-Show Evidence and Outsourced Coordination',excerpt:'A careful way to study missed appointments without blaming customers or changing attendance records on assumption.',subject:'appointment no-show evidence',unit:'appointment attendance case',finding:'No-show analysis is more useful when scheduled time, confirmation evidence, cancellation history, arrival record, and business rule are kept distinct.',source:'The SBA Business Guide frames operations and customer management as business activities; FTC business guidance provides a general standard against unsupported or misleading customer communications.',sourceLinks:['https://www.sba.gov/business-guide','https://www.ftc.gov/business-guidance'],evidence:'A missed appointment record does not establish why a person did not attend, and an automated status may conflict with staff notes or a documented cancellation.',field:'confirmation event, cancellation source, arrival record, and reason status',boundary:'customer blame, fees, refunds, policy exceptions, and status changes without evidence',published:'2026-08-14'},
  {slug:'august-14-research-service-complaint-categorization',title:'Research: Service Complaint Categorization Before Outsourced Review',excerpt:'How to classify complaint records for owner review while keeping facts, sentiment, and remedy decisions separate.',subject:'service complaint categorization',unit:'customer complaint record',finding:'Complaint triage is measurable when the customer’s stated issue, related service record, urgency, privacy concern, and requested remedy are recorded separately.',source:'FTC business guidance emphasizes truthful communication and privacy awareness; NIST CSF 2.0 supports identifying risk and assigning responsibility for response.',sourceLinks:['https://www.ftc.gov/business-guidance','https://www.nist.gov/cyberframework'],evidence:'A strongly worded complaint may be routine, while a calm message can contain a safety, privacy, or legal issue that needs faster escalation.',field:'issue category, source quotation, urgency signal, and requested remedy',boundary:'admitting liability, offering compensation, legal response, and closing a disputed complaint',published:'2026-08-14'},
  {slug:'august-14-research-business-email-deliverability-records',title:'Research: Business Email Deliverability Records and Safe Outsourcing',excerpt:'A source-led method for reviewing delivery evidence without changing domain settings or treating one bounce as a root-cause diagnosis.',subject:'business email deliverability records',unit:'email delivery event',finding:'Deliverability review is useful when the original message, recipient status, timestamp, system response, and approved technical owner are connected in one record.',source:'NIST CSF 2.0 provides guidance for identifying and protecting systems; FTC business guidance covers privacy and security considerations for business information.',sourceLinks:['https://www.nist.gov/cyberframework','https://www.ftc.gov/business-guidance'],evidence:'A bounce response documents a delivery event, but it does not alone prove whether the address, sender policy, recipient system, or message content caused it.',field:'message identifier, response code, domain, and observation time',boundary:'DNS changes, authentication changes, mailbox access, and claims about root cause',published:'2026-08-14'},
  {slug:'august-14-research-accessibility-request-records',title:'Research: Accessibility Request Records With Clear Escalation',excerpt:'How to keep accommodation-related requests findable without making promises or exposing sensitive details beyond the approved purpose.',subject:'accessibility request records',unit:'accessibility-related request',finding:'Request preparation is safer when the record preserves the person’s stated need, requested service, source, date, and unanswered feasibility question without inventing a medical explanation.',source:'FTC business guidance addresses privacy and security responsibilities; the SBA Business Guide places customer and operational decisions with the business.',sourceLinks:['https://www.ftc.gov/business-guidance','https://www.sba.gov/business-guide'],evidence:'A helpful-sounding assumption about a person’s condition can be inaccurate and may expose information that the business did not need to collect.',field:'stated request, service context, source wording, and privacy classification',boundary:'medical inference, accommodation promises, eligibility decisions, and disclosure of sensitive information',published:'2026-08-14'},
  {slug:'august-14-research-warranty-claim-evidence-packets',title:'Research: Warranty Claim Evidence Packets for Outsourced Support',excerpt:'A bounded model for assembling warranty evidence while keeping eligibility, repair, replacement, and refund decisions with the owner.',subject:'warranty claim evidence packets',unit:'warranty claim case',finding:'A claim packet supports review when purchase evidence, product identity, reported problem, dates, policy version, and prior contact are preserved without turning a symptom into a diagnosis.',source:'FTC business guidance emphasizes truthful consumer communication; NIST CSF 2.0 supports protecting business records and identifying dependencies in the response process.',sourceLinks:['https://www.ftc.gov/business-guidance','https://www.nist.gov/cyberframework'],evidence:'A complete packet can show that a claim is ready for review, but it cannot prove eligibility or require a remedy when the policy and facts still conflict.',field:'purchase source, product identifier, reported symptom, and policy version',boundary:'eligibility, repair diagnosis, replacement, refund, and legal interpretation',published:'2026-08-14'},
  {slug:'august-14-research-business-continuity-contact-records',title:'Research: Business Continuity Contact Records for Small Teams',excerpt:'What evidence makes a continuity contact list usable without granting authority or exposing an unnecessary directory.',subject:'business continuity contact records',unit:'continuity contact record',finding:'A continuity list is useful when each contact has a defined purpose, source, last review date, communication channel, and backup path rather than only a name and phone number.',source:'NIST CSF 2.0 includes governance, response, and recovery considerations; the SBA Business Guide connects planning and operations to business continuity decisions.',sourceLinks:['https://www.nist.gov/itl/smallbusinesscyber/nist-cybersecurity-framework-0','https://www.sba.gov/business-guide'],evidence:'A current phone number does not prove that the person is available, authorized, or the correct decision owner during a disruption.',field:'purpose, authorization boundary, review date, and backup contact',boundary:'emergency authority, public statements, account recovery, and unapproved disclosure',published:'2026-08-14'},
];

export const augustFourteenResearchBatch = specs.map((s) => ({...s, body: makeBody(s)}));
