type ResearchSpec = {
  slug: string;
  title: string;
  excerpt: string;
  subject: string;
  unit: string;
  finding: string;
  source: string;
  evidence: string[];
  lens: string[];
  published: '2026-08-13';
};

const makeBody = (s: ResearchSpec): readonly string[] => {
  const paragraphs = [
    `Scope and question. This article examines ${s.subject} for a small business considering outside operational support. The question is not whether a larger queue is impressive; it is whether the business can obtain a more accurate, reviewable result without losing decision authority. The unit of analysis is the ${s.unit}. That definition matters because an email, a record, an exception, and a completed case are not interchangeable units. A business should write down which unit it is counting before comparing a baseline with a later period.`,
    `Finding. ${s.finding} The strongest result is a balanced one: speed, completeness, and exception quality should be viewed together. A fast result that cannot be traced to a source, or that creates a second correction queue, is not operational improvement. This conclusion is bounded to repeatable administrative and support work. It does not claim that external support is appropriate for every business, every customer, or every decision.`,
    `Evidence base. ${s.source} The guidance is useful as a control baseline, not as proof of a particular provider's performance. The evidence question for an individual business is narrower: can a reviewer reproduce the result from the original record, identify what was assumed, and see who approved the unusual case? A dated sample is more informative than an anecdote because it makes omissions and exceptions visible.`,
    `Baseline design. Before changing ownership, collect a baseline for at least one defined period, such as ten business days, and record the number received, completed, waiting, corrected, and escalated. Record elapsed time in hours or business days, not vague labels such as fast or slow. Keep the denominator visible. If 18 of 24 cases are complete, the completion rate is 75 percent; it is not useful to report only the 18 completed cases.`,
    `Data fields. The proposed record should contain a source identifier, received date, current status, responsible person, next action, and exception reason. Add the field that is unique to ${s.subject}: ${s.lens[0]}. Missing fields should be counted separately from incorrect fields. A blank field may indicate a missing source, while an incorrect field may indicate misunderstanding. Those causes require different responses and should not be combined into one defect number.`,
    `Comparison method. Compare like with like. Use the same ${s.unit} definition, similar business hours, and the same policy version when possible. If the first sample contains seasonal demand or an unusual promotion, label it rather than presenting it as normal. Compare medians as well as averages when a few very long cases distort the mean. Report the sample size, period, exclusions, and any change in intake channel so the reader can judge the strength of the comparison.`,
    `Role boundary. A specialist can prepare, classify, update, or draft within approved rules. The business owner or named manager should retain decisions involving money, legal exposure, sensitive personal information, policy exceptions, or commitments that the source record cannot support. This boundary is not a judgment about skill. It is a way to keep accountability aligned with authority. The handoff should state what happens next when the evidence is incomplete.`,
    `Review design. Review every item during a short initial sample, then use a documented sample after the result is stable. For example, a manager might inspect 5 of 25 completed cases, while reviewing 100 percent of cases marked high risk. Those numbers are starting points, not universal rules. Increase the sample when the error severity rises, the source system changes, or the business sees repeated corrections. Decrease it only when dated records support that decision.`,
    `Interpretation. A lower response time can coexist with lower accuracy if difficult cases are silently deferred. For that reason, the dashboard should show aging, reopened cases, corrections, and escalation quality beside throughput. ${s.evidence[0]} The business should also ask whether owner review time fell or merely moved to a later correction stage. A useful result removes avoidable coordination work while preserving a clear route for judgment-heavy cases.`,
    `Risk and access. Apply least-privilege access to the systems needed for the defined work. A person preparing ${s.subject} may not need authority to delete records, release funds, change account ownership, or alter public policy. Use named accounts, multifactor authentication where available, and an access review when the scope changes. The access map should list the task, system, permission, business owner, and removal step.`,
    `Limitations. This is operational research, not a randomized experiment or a market-wide performance study. A ten-day sample can miss monthly, seasonal, or rare high-impact events. A well-designed record can still contain a source error. Results from one business should not be generalized to another without checking its channel mix, service promise, data sensitivity, staffing pattern, and review capacity. Legal, tax, privacy, employment, and sector-specific questions need qualified advice where applicable.`,
    `Practical conclusion. Start with one narrow lane and a dated evidence set. Define the unit, preserve the source, name the reviewer, and make the exception route explicit. Expand only when the business can explain what improved, what did not, and what risk remains. For ${s.subject}, the decision should be based on accuracy and owner visibility as well as speed. The best handoff is reversible: access can be removed, records remain with the business, and unresolved judgment returns to the named owner.`,
    `Questions for a decision review. Which ${s.unit} is being counted? What percentage is complete without correction? How many cases required owner intervention? Which field is most often missing? Which exception category is growing? What source proves the reported status? What action is allowed without approval? What must stop until a decision is made? What would make the business narrow the scope again? Writing answers beside the sample prevents a promising first result from becoming an unsupported expansion.`,
    `Decision thresholds. Before the first handoff, the owner should set a quality floor and a stop condition in plain language. For example, a business might require 23 of 25 records to pass the first review, require every high-risk case to be escalated, and pause expansion after two material errors in a week. The threshold should name the denominator, severity, time period, and person who decides. Without those details, a later argument about whether performance is acceptable cannot be resolved from the record.`,
    `Measurement note. Keep the baseline and follow-up samples in the same business record, with collection dates and a short note about exclusions. That makes later review possible when staff, software, policy, or demand changes. It also prevents a single favorable week from being mistaken for a stable pattern.`,
    `Final assessment. The evidence supports a measured, bounded handoff when the work is repeatable, the input is identifiable, and the finish condition is visible. It does not support delegating unresolved judgment simply because the queue is busy. ${s.evidence[1]} A small business can learn from a controlled sample without promising a universal outcome. The appropriate conclusion is therefore conditional: proceed only if the business's own records show acceptable quality, manageable review effort, and a safe exception path.`
  ];
  return paragraphs;
};

const specs: ResearchSpec[] = [
  {slug:'august-13-research-inbox-triage-accuracy',title:'Research: Measuring Inbox Triage Accuracy Before Outsourcing',excerpt:'How small businesses can evaluate message classification and escalation quality before assigning inbox triage to outside support.',subject:'customer inbox triage',unit:'incoming conversation',finding:'Inbox triage is a good candidate for measured support when classification accuracy and escalation completeness are tracked alongside response time.',source:'The SBA Business Guide frames day-to-day management around clear objectives, while FTC business guidance emphasizes truthful communication and responsible handling of customer information.',evidence:['A message tagged quickly but sent to the wrong queue can increase customer risk rather than reduce it.','The highest-value comparison is accurate routing per 100 conversations, separated by routine questions and exceptions.'],published:'2026-08-13',lens:['customer intent and urgency','whether the reply needs an approved policy reference']},
  {slug:'august-13-research-bookkeeping-source-traceability',title:'Research: Source Traceability in Outsourced Bookkeeping Preparation',excerpt:'What evidence helps an owner judge whether bookkeeping preparation remains complete, reviewable, and separate from financial judgment.',subject:'bookkeeping preparation',unit:'financial record prepared from a source document',finding:'Bookkeeping preparation is easier to review when every entry preserves its source, treatment, unresolved question, and reviewer disposition.',source:'IRS Publication 583 describes the importance of supporting records and a system that clearly shows income and expenses; SBA financial guidance emphasizes regular review of business finances.',evidence:['A prepared entry without source support is a claim, not a completed control.','The useful measure is supported records accepted on first review, not the number of entries entered.'],published:'2026-08-13',lens:['source-document identifier and accounting period','whether the item is routine, unreconciled, or judgment-heavy']},
  {slug:'august-13-research-lead-record-completeness',title:'Research: Lead Record Completeness in Outsourced Intake',excerpt:'A research-based way to measure whether outside support produces owner-ready lead records rather than an unverified volume queue.',subject:'lead record intake',unit:'new lead record',finding:'Lead intake quality depends on complete, attributable records and appropriate routing; raw lead volume is a weak proxy for useful sales readiness.',source:'FTC small-business advertising guidance stresses truthful claims and privacy awareness, while NIST CSF 2.0 begins with identifying assets, risks, and business context.',evidence:['A record with an invented qualification detail can be more harmful than an incomplete record that is honestly flagged.','Measure valid required fields and correct routing per 100 received leads, then inspect the missing-field reasons.'],published:'2026-08-13',lens:['source channel and contact context','whether qualification is observed, reported, or still unknown']},
  {slug:'august-13-research-invoice-dispute-visibility',title:'Research: Invoice Dispute Visibility When Follow-Up Is Outsourced',excerpt:'How to tell whether an external follow-up queue improves visibility without turning unresolved disputes into inappropriate pressure.',subject:'invoice follow-up and dispute records',unit:'open invoice case',finding:'Follow-up support creates value when it makes age, source balance, customer context, and next owner decision visible without disguising disputed cases as ordinary overdue work.',source:'SBA financial-management guidance calls for regular review of financial information; FTC guidance provides a useful reminder that business communications should not make unsupported claims.',evidence:['A higher message count does not demonstrate healthier receivables if disputes are misclassified or source balances are stale.','Report reconciled cases, disputed cases, and owner decisions separately so the queue cannot hide uncertainty.'],published:'2026-08-13',lens:['ledger date, source balance, and dispute status','whether a proposed message is approved for the account context']},
  {slug:'august-13-research-ecommerce-return-exceptions',title:'Research: Ecommerce Return Exceptions and Outsourced Order Support',excerpt:'A bounded evidence model for separating routine order updates from returns, refunds, and policy exceptions.',subject:'ecommerce order and return support',unit:'customer order case',finding:'Order support is most measurable when the order record, fulfillment evidence, customer request, and approved policy agree before a reply is sent.',source:'FTC business guidance on advertising and consumer protection supports careful treatment of advertised terms; NIST CSF 2.0 supports identifying systems and protecting the information they hold.',evidence:['A case closed quickly can still be defective if the policy promise, order status, and customer message conflict.','Track correct status explanations and safe exception routing, not only closed tickets.'],published:'2026-08-13',lens:['order status, fulfillment evidence, and policy version','whether the request is an update, return, refund, or exception']},
  {slug:'august-13-research-service-appointment-capacity',title:'Research: Capacity Accuracy in Outsourced Service Appointments',excerpt:'Why small businesses should measure promise accuracy and reschedules, not just the number of appointments placed.',subject:'local-service appointment coordination',unit:'appointment request',finding:'Appointment coordination is useful only when the selected time, service, location, and available capacity are consistent with the business promise.',source:'SBA planning guidance connects sound operations with understanding customers, resources, and delivery capacity; NIST guidance reinforces identifying dependencies before protecting operations.',evidence:['A booking that creates a conflict is not a successful booking even if it increases the daily count.','Measure confirmed requests without correction, reschedules, conflicts, and owner interventions by service type.'],published:'2026-08-13',lens:['service type, location, preparation time, and capacity window','whether the request fits a published rule or needs a decision']},
  {slug:'august-13-research-supplier-delay-risk',title:'Research: Supplier Delay Risk in Outsourced Vendor Coordination',excerpt:'A source-led method for keeping supplier commitments, changes, and owner decisions visible in a small business.',subject:'supplier update coordination',unit:'supplier commitment or open purchase case',finding:'Vendor coordination improves visibility when each commitment has a source, promised date, latest confirmation, dependency, and named decision owner.',source:'NIST CSF 2.0 emphasizes identifying dependencies and risks; SBA business guidance places supplier and operating decisions within broader day-to-day management.',evidence:['A current email without a linked commitment can create false confidence about delivery or service readiness.','Report commitments with evidence and separate confirmed facts from assumptions about a delay.'],published:'2026-08-13',lens:['latest supplier confirmation and promised date','whether a change affects customer commitments or requires owner approval']},
  {slug:'august-13-research-public-review-drafting-privacy',title:'Research: Privacy Safeguards for Outsourced Public Review Drafting',excerpt:'How to evaluate drafting support while protecting customer privacy, factual accuracy, and the business owner’s public voice.',subject:'public review response drafting',unit:'public review case',finding:'Drafting support is bounded and reviewable when the draft uses verified facts, avoids private details, and routes sensitive or legal-risk cases to the business owner.',source:'FTC advertising and endorsement guidance requires truthful, non-misleading public communication; NIST CSF 2.0 provides a risk-based lens for protecting information and assigning responsibility.',evidence:['A polished response can still create harm if it reveals a customer detail or asserts a fact the source record cannot prove.','Measure factual support and safe escalation per 100 review cases, not only posting speed.'],published:'2026-08-13',lens:['verified service fact and privacy classification','whether the response includes compensation, legal, or sensitive claims']},
  {slug:'august-13-research-admin-document-retrieval',title:'Research: Document Retrieval Accuracy in Outsourced Administration',excerpt:'Evidence for deciding whether document lookup and preparation can be delegated without losing version, permission, or source control.',subject:'administrative document retrieval and preparation',unit:'document request',finding:'Document support is a strong candidate for bounded delegation when the requested version, source location, access boundary, and completion test are explicit.',source:'SBA guidance treats day-to-day operations and record organization as management concerns, while NIST CSF 2.0 supports identifying information assets and protecting access to them.',evidence:['Finding a file is not enough if it is the wrong version, lacks required context, or exposes information to the wrong recipient.','Track correct-version retrieval, missing-source cases, and permission exceptions separately.'],published:'2026-08-13',lens:['document version, source location, and recipient purpose','whether the request permits retrieval, formatting, or external sharing']},
  {slug:'august-13-research-outsourced-access-removal',title:'Research: Access Removal Evidence After Outsourced Work Changes',excerpt:'A practical research model for measuring whether small businesses can change or end outside support without losing control of records.',subject:'outsourced-work access changes and offboarding',unit:'access change event',finding:'Access governance is measurable when the business can show who had which permission, why it was needed, when scope changed, and how removal was confirmed.',source:'NIST CSF 2.0 and its small-business guidance emphasize identifying assets, protecting them, and learning from outcomes; SBA guidance places continuity and risk management within business operations.',evidence:['A removal request is not proof of removal until the system or owner record confirms the change.','Measure confirmed access changes within the required period, including shared-account exceptions and unreturned records.'],published:'2026-08-13',lens:['system, role, permission, and business purpose','whether the change is a scope reduction, transfer, suspension, or full removal']}
];

export const augustThirteenResearchBatch = specs.map((s) => ({...s, body: makeBody(s)}));
