type BatchPost = { slug: string; title: string; excerpt: string; focus: string; opening: string; checklist: readonly string[]; watchout: string; measure: string; lens: string };

const publicationDates = [
  '2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18',
  '2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18','2026-08-18'
] as const;

const topics: BatchPost[] = [
  ['outsource-small-business-invoice-status-checks','Outsource small-business invoice status checks','Keep invoice follow-up factual while leaving disputes, credits, and payment decisions with the owner.','invoice status checks','An invoice status check compares the invoice record, latest payment evidence, customer message, and unresolved finance question.','invoice number and period','payment evidence','disputed amount','approved next step'],
  ['outsource-small-business-project-risk-notes','How to outsource small-business project risk notes','Turn observed delivery risks into reviewable notes without promising recovery or assigning blame.','project risk notes','A project risk note separates an observed condition from its possible consequence, evidence, owner, and decision needed.','project milestone and source','observed condition','possible consequence','owner decision'],
  ['outsource-small-business-customer-consent-records','Outsource small-business customer consent records carefully','Preserve what a customer actually agreed to without inferring permission from silence or an unrelated interaction.','customer consent records','A consent record identifies the request, exact response, channel, timestamp, purpose, and limits of what was agreed.','exact customer wording and timestamp','stated purpose','permission limit','renewal question'],
  ['outsource-small-business-supplier-quote-logs','Build outsourced supplier quote logs with clear boundaries','Make supplier comparisons easier to review without selecting a vendor or presenting an estimate as an approval.','supplier quote logs','A quote log records the supplier, item, scope, date, stated terms, source, and question that still belongs to the owner.','supplier identity as shown','quoted scope','stated term','comparison question'],
  ['outsource-small-business-customer-priority-flags','How to outsource customer priority flag checks','Make urgency visible using an approved rule while keeping remedy, safety, and exception decisions with the business.','customer priority flag checks','A priority check compares the customer request with the written urgency rule, source evidence, due point, and escalation path.','approved urgency rule','customer impact','due point','escalation path'],
  ['outsource-small-business-employee-document-indexes','Outsource small-business employee document indexes safely','Keep personnel files findable without deciding employment status, entitlement, or retention treatment.','employee document indexes','A personnel-document index records the file label, person, source location, date, access boundary, and review question.','document label and version','person record','access boundary','retention question'],
  ['outsource-small-business-service-issue-triage','A practical guide to outsourcing service issue triage','Sort service issues into approved lanes without diagnosing a cause or promising a remedy.','service issue triage','Service triage is a documented routing step: capture the report, classify only from approved examples, and escalate uncertainty.','customer report','approved category','evidence link','escalation reason'],
  ['outsource-small-business-content-approval-queues','Outsource small-business content approval queues','Prepare drafts for review while preserving source claims, reviewer ownership, and publication controls.','content approval queues','An approval queue connects the draft, source material, intended audience, reviewer, status, and decision needed.','draft source and version','intended audience','reviewer','publication decision'],
  ['outsource-small-business-customer-identity-questions','How to outsource customer identity question logs','Record identity mismatches without attempting verification or exposing more information than the task requires.','customer identity question logs','An identity question log records the request, record matched, mismatch observed, evidence available, and approved verification path.','request as received','matched record','mismatch observed','verification path'],
  ['outsource-small-business-operations-calendar-reviews','Outsource small-business operations calendar reviews','Find schedule conflicts and missing details without committing capacity or changing the operating plan.','operations calendar reviews','A calendar review compares the approved event, dependencies, owner, timing, and conflict evidence before an update is proposed.','approved event','dependency','timing','conflict evidence'],
  ['outsource-small-business-customer-escalation-packets','Build customer escalation packets for owner review','Give difficult cases a complete evidence trail without deciding liability, refunds, or policy exceptions.','customer escalation packets','An escalation packet states the customer request, source history, current status, policy reference, and precise owner question.','customer request','source history','current status','owner question'],
  ['outsource-small-business-website-content-inventories','Outsource small-business website content inventories','Create a current page inventory without changing public claims, navigation, or technical settings.','website content inventories','A content inventory records the page, displayed claim, source owner, last observed state, and review question.','page URL and title','displayed claim','source owner','review question'],
  ['outsource-small-business-lead-response-age-checks','How to outsource lead response age checks','Show where inquiries are waiting without promising response performance or changing attribution.','lead response age checks','A response-age check measures elapsed time from the recorded inquiry to the latest supported action and preserves the reason for waiting.','inquiry timestamp','latest action','waiting reason','owner decision'],
  ['outsource-small-business-work-instruction-version-checks','Outsource work-instruction version checks','Keep SOP references aligned with approved versions without silently rewriting instructions or policy.','work-instruction version checks','A version check compares the instruction used, approved version, source location, effective date, and discrepancy.','instruction title and version','approved source','effective date','discrepancy'],
  ['outsource-small-business-customer-appointment-confirmations','Outsource small-business appointment confirmation records','Prepare confirmation evidence without inventing availability, changing details, or treating silence as acceptance.','appointment confirmation records','A confirmation record shows the appointment details, message sent, source, response status, and unresolved scheduling question.','appointment details','message sent','response status','scheduling question'],
  ['outsource-small-business-business-license-records','How to outsource business license record checks','Organize displayed license information without declaring compliance or interpreting a regulatory requirement.','business license record checks','A license check records the public or approved source, displayed identifier, dates, entity wording, and question for the responsible reviewer.','source and observation date','displayed identifier','entity wording','review question'],
  ['outsource-small-business-customer-sentiment-coding','Outsource customer sentiment coding without overclaiming','Use a defined coding scheme to summarize messages while preserving the customer words and uncertainty.','customer sentiment coding','Sentiment coding is a structured description of message signals, not a diagnosis of the customer or a substitute for reading the source.','customer words and source','approved code','uncertainty','review need'],
  ['outsource-small-business-open-question-registers','Build outsourced open-question registers for owners','Turn scattered uncertainties into a decision list with source links and clear consequences of waiting.','open-question registers','An open-question register names the work, question, evidence, waiting owner, due point, and next review action.','question in one sentence','evidence link','waiting owner','next review'],
  ['outsource-small-business-customer-message-translation-checks','Outsource customer message translation checks carefully','Compare translated meaning with the source and approved policy without making legal, cultural, or remedy decisions.','customer message translation checks','A translation check records the source meaning, translated wording, uncertainty, policy context, and reviewer needed for a consequential choice.','source message','translated wording','uncertainty','reviewer'],
  ['outsource-small-business-business-continuity-contact-lists','Outsource small-business continuity contact lists','Keep emergency contact information reviewable without expanding access or making response commitments.','business continuity contact lists','A continuity list identifies the role, approved contact channel, source, review date, and conditions for escalation.','role and approved channel','source','review date','escalation condition'],
  ['outsource-small-business-customer-data-correction-logs','How to outsource customer data correction logs','Track requested corrections without changing the record or deciding whether a request is valid.','customer data correction logs','A correction log preserves the requested field, source request, current value as shown, evidence, and decision owner.','requested field','source request','current value','decision owner'],
  ['outsource-small-business-recurring-task-coverage-reviews','Outsource recurring task coverage reviews','Identify work with no current owner while keeping capacity and staffing decisions with the business.','recurring task coverage reviews','A coverage review compares the recurring task, expected cadence, last completion, current owner, backup, and gap.','task and cadence','last completion','current owner','coverage gap'],
].map(([slug,title,excerpt,focus,opening,a,b,c,d]) => ({slug,title,excerpt,focus,opening,checklist:[`record the ${a} exactly from the approved source`,`separate the ${b} from a decision or assumption`,`flag ${c}, conflicting evidence, and missing context`],watchout:`Do not resolve ${c}, change the source record, or make a commitment about ${d} without the named owner’s approval.`,measure:`Track items reviewed, ${c} found, evidence gaps, and ${d} waiting for review.`,lens:`whether the ${focus} record lets the owner act without guessing about ${a}, ${b}, or ${d}`}));

export const augustEighteenBlogBatch = topics.map((post, index) => ({ ...post, publicationDate: publicationDates[index] }));
