type ResearchPost = { slug:string; title:string; excerpt:string; published:string; campaignDate:string; imagePath:string; body:readonly string[] };

const common = {
  sba:'https://www.sba.gov/business-guide/manage-your-business',
  plan:'https://www.sba.gov/business-guide/plan-your-business',
  nist:'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20',
  ftc:'https://www.ftc.gov/business-guidance/resources/start-security-guide-business',
  irs:'https://www.irs.gov/publications/p583'
} as const;

const posts: ResearchPost[] = [
  {slug:'august-20-research-handoff-provenance-outsourced-support',title:'Research: Handoff Provenance in Outsourced Small-Business Support',excerpt:'Which evidence lets an owner verify that a transferred task still means what the original request meant?',published:'2026-08-20',campaignDate:'2026-08-20',imagePath:'/research-heroes/aug20-handoff-provenance.png',body:[
    'Research question. When a small business moves a task between an owner, a Philippines-based specialist, and an internal system, which evidence shows that the handoff preserved the request rather than merely producing a polished summary? This study treats one transferred work item as the unit of analysis. The item includes its source request, relevant record, current status, proposed next action, unresolved question, and receiving owner. It does not include a new promise, remedy, or policy decision made by the person preparing the transfer.',
    'Methodology and evidence scope. The proposed review uses a dated sample of transferred items from one defined service lane. For each item, retain the original request, the source record consulted, the time of transfer, the exact fields carried forward, the receiving person’s first action, and any clarification loop. Compare ordinary items with incomplete, duplicated, corrected, and escalated items. Public evidence frames the method: the SBA describes management of day-to-day operations, NIST CSF 2.0 emphasizes governance and accountability, and FTC guidance stresses deliberate handling of business information. Sources: '+common.sba+'; '+common.nist+'; '+common.ftc+'.',
    'Facts versus analysis. The facts are observable: identifiers, timestamps, source links, field values, status changes, and the receiving person’s recorded disposition. Analysis begins when the reviewer asks whether the recipient could act without reopening the original context. A fast transfer is not automatically a good transfer. A longer handoff may be more reliable if it exposes a missing approval or preserves a conflict that a short summary would hide.',
    'The evidence should distinguish four states that are often collapsed. Prepared means the support role assembled the available information. Received means the next role acknowledged the transfer. Accepted means the recipient found the record sufficient for the permitted next action. Decided means an authorized owner resolved a judgment-heavy question. Counting all four as completion inflates apparent throughput and makes it difficult to see where work is actually waiting.',
    'For outsourced small-business operations, provenance is practical only when the source remains reachable. A handoff should link to the source rather than copy a large uncontrolled extract. It should preserve the customer’s or operator’s original wording where meaning matters, identify which system field was checked, and name the rule used for routine routing. If the source is unavailable, the preparer should record that limitation and escalate instead of reconstructing a likely answer from memory.',
    'A useful measurement set pairs receiving acceptance with correction and clarification. Track first-pass acceptance, requests for missing context, owner rerouting, reopened items, and high-consequence cases found after transfer. Report counts with denominators and mark periods affected by a new inbox, system, policy, or reviewer. A lower clarification rate can mean better handoffs, but it can also mean that recipients stopped asking questions. The raw sample is necessary to interpret the number.',
    'Role boundary. A Philippines-based support role can organize a source packet, compare stated information with an approved record, flag an inconsistency, and draft a neutral handoff. The owner or named manager retains decisions about money, legal meaning, privacy-sensitive disclosure, customer remedies, policy exceptions, and commitments. This boundary is about authority and traceability, not a claim about capability. A safe lane gives the preparer permission to stop when evidence conflicts.',
    'Limitations. This is qualitative operational research, not a randomized experiment, audit opinion, security certification, or provider performance study. A short sample can miss seasonal work, rare complaints, and later corrections. Public guidance does not establish a universal handoff taxonomy or prove that outsourcing caused an observed improvement. Contractual, privacy, employment, tax, or sector-specific obligations may require qualified advice outside this article.',
    'Evidence-led conclusion. Handoff quality is supportable when a reviewer can reconstruct the original request, the source checked, the permitted next action, the unresolved question, and the receiving owner. The evidence supports a narrow, reversible support lane when acceptance and correction are measured together. It does not support treating a complete-looking summary as proof that the business has made the underlying decision. Recheck after any material change to systems, policy, access, or ownership.',
    'Review prompts. Which transferred item is being counted? Can the receiver reach the source without a broad export? Which field proves current status? What happens when two sources disagree? Which category requires owner review before any customer-facing message? How many items were accepted without correction, and how many were later reopened? These questions keep a daily publishing and operating routine grounded in evidence rather than completion language.',
    'Additional interpretation. Provenance is most valuable when the work is ordinary enough to repeat but consequential enough that a missing detail changes the next action. Reviewers should therefore inspect the first source, not only the final handoff, and compare what was carried forward with what was intentionally left out. A concise handoff can be strong when its omissions are deliberate and its links are live; a long handoff can be weak when it buries the decision point under copied context. Record whether the recipient needed a clarification, whether the clarification changed the proposed action, and whether the owner later discovered an earlier source that should have been attached. These observations help distinguish a wording problem from a source problem or an authority problem. They also help decide whether the daily lane needs a new field, a clearer stop rule, or no process change at all. The evidence should be reviewed by a person who understands the business boundary, because a transfer can be technically complete and still misstate what the business is willing to promise. A reversible pilot is preferable when results are mixed: preserve the sample, narrow the category, and require explicit acceptance before increasing volume. That conclusion is intentionally modest. It protects the purpose of research, which is to make the next operating decision more inspectable, not to turn a successful handoff sample into a universal outsourcing claim.'
  ]},
  {slug:'august-20-research-least-privilege-outsourced-administration',title:'Research: Least-Privilege Access for Outsourced Small-Business Administration',excerpt:'How to test whether an outside support role can complete a defined task without receiving unrelated business access.',published:'2026-08-20',campaignDate:'2026-08-20',imagePath:'/research-heroes/aug20-least-privilege.png',body:[
    'Research question. Can a small business give outsourced administrative support enough information to prepare accurate work while excluding systems, records, and actions that are merely convenient? The unit studied is one task-specific access request, not an employee or vendor as a whole. The question is whether each permission has a stated purpose, a bounded action, a source owner, and a review point when the task changes.',
    'Method. Map one recurring lane from input to permitted output. List every system, field, export, and action the proposed role would touch. For each, record why it is necessary, what less-privileged alternative was considered, who approves access, how activity is logged, and how access is removed. Compare the map against an ordinary task, a missing-input case, and an exception involving sensitive or financial information. NIST CSF 2.0, FTC small-business security guidance, and SBA management guidance provide the public control context: '+common.nist+'; '+common.ftc+'; '+common.sba+'.',
    'Facts and interpretation. Facts include the permission assigned, the task attempted, the fields viewed, the action taken, the source record, the timestamp, and the removal or review event. Analysis is the judgment that a permission is necessary or excessive. “The role has never misused access” is not evidence that the access was properly scoped. Likewise, a blocked task proves only that the design needs adjustment; it does not justify opening unrelated records by default.',
    'The strongest design separates seeing, preparing, changing, approving, exporting, and deleting. A support role may need to see a status field to prepare a queue, but not payment credentials to record that status. It may draft a customer message without permission to publish it. It may identify a duplicate without deleting the original. These distinctions are especially important for small businesses, where one account can otherwise combine routine administration with irreversible authority.',
    'Test the boundary with counterfactuals. What would the task lose if one field were masked? Could a source link replace a downloaded dataset? Could an owner approve the final change through a separate role? What happens when a specialist encounters an unexpected record? A good access design gives the person a clear stop path: preserve the source, describe the blocker, and ask the named owner rather than treating access expansion as an ordinary productivity fix.',
    'Measure exposure and usefulness together. Record required fields per task, blocked attempts, unnecessary fields viewed, exception escalations, access-review findings, and time between role change and permission removal. A high completion count cannot compensate for broad exposure. A high block count may reveal that the task was poorly specified rather than that least privilege failed. Interpret metrics against the actual task and mark any change in software, data classification, reviewer, or business process.',
    'Outsourced support boundaries. A Philippines-based specialist can prepare records, reconcile visible fields, organize approved documents, and draft a neutral question. The business retains account administration, credential recovery, payment release, deletion, legal interpretation, privacy decisions, and access expansion. A named manager should decide whether a blocked action is truly necessary. Where obligations differ by jurisdiction or contract, qualified advice outranks an operational shortcut.',
    'Limitations. This review does not certify a system, assess a particular provider, or establish compliance with a law or contract. Public frameworks are flexible guidance, not proof that a local permission map is complete. Logs can show activity but not always intent, and a short observation period can miss dormant access or a rare export. The study also does not claim that the smallest possible permission is always workable; necessity must be tested against the actual service lane.',
    'Conclusion. Least privilege is a reviewable operating decision when every permission maps to a task, every exception has an owner, and access removal is tested rather than assumed. The evidence supports starting with the narrowest useful view and adding one documented permission only when the task sample shows a real need. It does not support granting broad access because a role may eventually encounter an unusual case.',
    'Owner review questions. Which exact task requires this field? Can the source remain in the original system? What action is irreversible? Who sees the log? What is the removal trigger? What happens when a customer, employee, supplier, or payment record is outside the lane? These questions turn access from a vague trust decision into a bounded researchable control.',
    'Additional interpretation. Access evidence should be read as a relationship between a task and a permission, not as a permanent verdict about a person. The same specialist may need one view for a queue-preparation task and a different, narrower view for a document-checking task. Combining the roles for convenience makes later review difficult because the record no longer shows which permission supported which action. A useful test is to remove one field, run the task on a small sample, and record whether the result became inaccurate, slower, or merely less convenient. Only the first two outcomes establish a possible operational need, and even then the business should consider a source link, a masked field, or an owner-provided confirmation before opening a broader system. Review the access map after a policy change, a new customer channel, a software migration, or a change in the person approving exceptions. Dormant permissions matter because they create exposure even when no suspicious action has appeared in the log. Record the date of the review and the disposition of each exception. If the evidence remains ambiguous, keep the current boundary and route the task to the owner. A narrow lane that sometimes pauses is easier to govern than a broad lane that silently normalizes access. The practical conclusion is that least privilege is a continuing research question: the business should test necessity against real work, preserve the reason for every expansion, and remove permissions when the task ends.'
  ]},
  {slug:'august-20-research-bookkeeping-exception-reconciliation',title:'Research: Exception Reconciliation in Outsourced Small-Business Bookkeeping Preparation',excerpt:'What a bookkeeping preparation queue can prove when source records do not agree.',published:'2026-08-20',campaignDate:'2026-08-20',imagePath:'/research-heroes/aug20-bookkeeping-exceptions.png',body:[
    'Research question. When bank, card, invoice, receipt, and ledger records disagree, does outsourced bookkeeping preparation make the exception easier to resolve, or does it hide uncertainty behind a completed entry? The unit here is one unmatched transaction or supporting-record conflict. The study asks whether the source identity, amount, date, proposed classification, missing evidence, and decision owner remain visible to the person responsible for accounting judgment.',
    'Evidence scope and method. Select a dated sample from one defined period and preserve the original source identifiers. Match records using documented fields, then classify differences as timing, duplicate, missing document, changed amount, unclear payee, or other unresolved conflict. Compare the prepared queue with the eventual owner or qualified-accountant disposition. IRS Publication 583 and SBA financial-management guidance inform recordkeeping and review; NIST adds a control lens for protecting business information. Sources: '+common.irs+'; '+common.sba+'; '+common.nist+'.',
    'Observed facts are not conclusions. Amounts, dates, source documents, ledger states, reconciliation timestamps, and correction history are facts when directly recorded. Whether an item should be categorized, accrued, written off, or treated for tax purposes is analysis requiring appropriate authority. A queue marked “reconciled” should mean the defined evidence test passed, not that every accounting question has been settled.',
    'The research design should keep three records apart: the source document, the preparation note, and the authorized disposition. Copying all three into one editable field weakens the trail. A preparer may link a receipt, point out that the amount differs from a ledger entry, and request the missing context. The owner or qualified professional decides treatment where the evidence involves judgment, a filing, a payment, a related party, payroll, or an unusual transaction.',
    'A meaningful review looks at the shape of exceptions, not only the total cleared. Track match rate, unresolved items by reason, duplicate findings, missing-document age, correction rate, and items escalated before a financial action. Compare like periods and note bank-feed changes, new software, delayed statements, or a different close calendar. Faster clearing may reflect better source capture, but it may also reflect premature matching. Inspect sampled source pairs before interpreting a trend.',
    'For a small business using Philippines-based support, role design should favor preparation and visibility. The support lane can gather records, compare fields, identify duplicates, maintain a list of missing evidence, and draft questions. It should not invent a receipt, alter a source to force a match, approve a payment, file a return, or present a judgment as settled. The person reviewing the exception should be named in the record, and the original version should remain recoverable.',
    'Test difficult cases deliberately. Include a transaction with the right amount but wrong date, a receipt with a missing business purpose, a duplicate-looking charge, and an item where two sources disagree. These cases reveal whether the process rewards honest uncertainty. A workflow that performs only on clean receipts cannot show that the bookkeeping lane is ready for broader access or a shorter review cycle.',
    'Limitations. This is operational research, not tax, accounting, audit, or legal advice. Public IRS and SBA material cannot determine the correct treatment for a particular transaction or jurisdiction. The sample may miss period-end adjustments, late documents, fraud, or changes in professional oversight. The method cannot prove a provider’s competence or establish that outsourcing caused a reduction in close time or correction work.',
    'Conclusion. Outsourced preparation is evidence-led when it reduces search effort while making unresolved differences more visible. The defensible result is a better-organized review queue, not a claim that every prepared classification is correct. Expand only when dated samples show stable source linkage, accurate exception categories, and appropriate escalation. Narrow the lane when records are altered to make the queue appear complete.',
    'Review prompts. What source proves the amount and date? What does “matched” mean in this lane? Which exceptions require a qualified reviewer? How long do missing documents remain open? Were corrections made to the source or only to the preparation note? What financial action is prohibited until disposition is recorded? These questions preserve owner visibility while daily support work remains repeatable.',
    'Additional interpretation. The most informative reconciliation sample contains both easy matches and uncomfortable exceptions. If the sample excludes transactions that lack a receipt, contain a changed amount, or arrive after close, the resulting rate describes document completeness rather than preparation quality. Keep an exception taxonomy stable long enough to compare periods, but allow a new category when the evidence shows that an old label is hiding materially different causes. For example, “unmatched” could mean a timing difference, a duplicate, a missing source, or a judgment question; each requires a different next action and a different owner. The support lane should preserve the first observation and any later correction so a reviewer can tell whether the problem was in the source, the comparison, or the disposition. This also protects the preparer from pressure to make a record look cleaner than the evidence permits. A daily routine can report how many items are ready for review, how many are waiting on a source, and how many require an authorized accounting decision. Those are useful operational states even when they do not reduce the open count immediately. Before expanding the lane, compare correction reasons and reviewer time across at least two comparable periods, while noting system or close-calendar changes. The evidence may support more preparation, a better source-collection rule, or a narrower task. It should not be used to infer tax treatment or financial performance from a queue alone.'
  ]},
  {slug:'august-20-research-scheduling-capacity-evidence',title:'Research: Capacity Evidence Before Outsourced Small-Business Scheduling',excerpt:'How to tell whether scheduling support reflects real capacity instead of creating attractive but unreliable promises.',published:'2026-08-20',campaignDate:'2026-08-20',imagePath:'/research-heroes/aug20-scheduling-capacity.png',body:[
    'Research question. Before a small business expands outsourced scheduling support, what evidence distinguishes available capacity from an empty-looking calendar? The unit is one requested appointment or service slot, including service type, location or delivery constraint, required preparation, proposed time, confirmation status, and exception owner. The study is about promise accuracy and decision visibility, not the number of bookings placed.',
    'Methodology. Compare a dated sample of requests with the capacity source used to answer them. Record the requested service, resource requirement, travel or preparation buffer, selected slot, confirmation, later change, and reason for any conflict. Separate ordinary requests from urgent, unusual, incomplete, and customer-impacting cases. SBA planning guidance addresses understanding customers and resources; NIST CSF 2.0 supports identifying dependencies and risk before changing a control. Sources: '+common.plan+'; '+common.nist+'; '+common.sba+'.',
    'The facts are the source calendar, stated availability, timestamps, resource assignments, confirmed messages, and observed reschedules. Analysis begins when a reviewer attributes a conflict to capacity, missing information, or an unsupported assumption. A calendar with open space does not prove that the right person, equipment, travel time, or preparation window exists. Conversely, a full calendar does not prove that every slot is necessary if records contain stale holds.',
    'A scheduling lane should distinguish request received, slot proposed, slot confirmed, slot changed, and service completed. These states have different implications. Support can often check a request against published availability and prepare a proposed slot. Confirmation may require an owner or manager when the request changes terms, involves a scarce resource, or creates a customer commitment outside the written boundary.',
    'Use paired measures. Track proposal accuracy, confirmation-to-reschedule rate, conflict reason, missing-input rate, late change rate, and the age of unconfirmed requests. Examine the distribution by service type and time period rather than reporting one overall booking rate. If a new channel, promotion, staff schedule, or service promise changes arrivals, mark that break. A rising booking count alongside rising reschedules is not evidence of better scheduling.',
    'Scenario testing makes capacity evidence more realistic. Test an ordinary request, a request missing a required detail, a request that fits the calendar but not the travel buffer, and a request that conflicts with a named resource. The support role should be able to stop and ask a specific question in each case. If the only available behavior is to choose the nearest open slot, the lane is not yet bounded enough for reliable customer-facing work.',
    'Role boundary. A Philippines-based specialist can collect request details, compare them with the approved availability source, prepare options, and log conflicts. The business retains decisions about changing service terms, guaranteeing a time, displacing another customer, offering compensation, or accepting a safety-sensitive exception. This separation lets support reduce administrative delay without turning an external role into the owner of capacity or customer promises.',
    'Limitations. Public planning and risk guidance cannot model a particular business’s travel, staffing, equipment, or local service rules. A short sample misses seasonal peaks and rare disruptions. Reschedules may reflect customer behavior, weather, supply, or policy changes rather than scheduling quality. This research does not establish causation, a universal capacity benchmark, or legal advice about a service commitment.',
    'Conclusion. Outsourced scheduling support is defensible when every proposal is tied to a current capacity source, buffers and dependencies are visible, and exceptions return to a named decision-maker. The evidence supports a narrow preparation lane before broader confirmation authority. It does not support treating open calendar space as proof that a service promise can be made.',
    'Owner review questions. What resource actually makes the slot possible? Which buffer is included? What changes the status from proposed to confirmed? How are stale holds removed? Which request types always escalate? Which metric would cause the business to pause the lane? Keeping these answers explicit protects both the daily routine and the customer-facing boundary.',
    'Additional interpretation. Capacity evidence becomes fragile when the calendar is treated as the source of truth even though the real constraint lives elsewhere. A service may require a particular skill, travel time, setup period, equipment, approval, or supplier dependency that is not represented by an empty cell. The research record should name the source used for each proposal and show when that source was last checked. If a slot is offered from stale availability, the error is not simply a scheduling mistake; it is a failure to distinguish a visible calendar from an authorized promise. Reviewers should examine cancellations and reschedules by reason, because a customer change, a weather disruption, and an internal overbooking do not describe the same capacity problem. Similarly, a proposal that was never confirmed should not be counted as a completed booking. The support role can improve visibility by recording missing inputs and presenting options, but it should not hide uncertainty to preserve a conversion metric. When evidence is mixed, test a smaller service category or a single time window and retain every exception. That makes the next decision reversible and allows the owner to see whether the constraint is staffing, information, policy, or demand. The evidence-led conclusion remains bounded: scheduling preparation may be suitable when the source is current and the status vocabulary is explicit; broader customer-facing authority requires a separate decision and a new sample. A second review should compare the proposed slot with what actually happened, including late arrivals, travel overruns, and changes made by the owner. Those observations can reveal that the calendar needs a new buffer or dependency field rather than more staffing. Keep the change explicit so future samples remain comparable.'
  ]},
  {slug:'august-20-research-public-review-response-evidence',title:'Research: Evidence Boundaries for Outsourced Public Review Responses',excerpt:'How drafting support can preserve factual accuracy and privacy without deciding remedies or speaking beyond approved authority.',published:'2026-08-20',campaignDate:'2026-08-20',imagePath:'/research-heroes/aug20-review-response.png',body:[
    'Research question. What evidence should a small business require before outsourced support drafts or prepares a public response to a customer review? The unit is one response case: the public statement, the underlying service record, the proposed wording, any privacy concern, and the person who approves publication. The study tests whether drafting makes a response more accurate and bounded, not whether it improves ratings or sentiment.',
    'Method and sources. Review a dated sample of response cases and classify each as routine, factual correction, service recovery, privacy-sensitive, disputed, or legal-risk. For each, preserve the public text, source record, approved facts, proposed draft, edits, and final disposition. FTC business guidance emphasizes truthful, non-misleading communications; NIST CSF 2.0 supports accountable information handling; SBA guidance places operating decisions with the business. Sources: '+common.ftc+'; '+common.nist+'; '+common.sba+'.',
    'Facts versus analysis. The review can establish what the customer wrote, what the source record says, which statements are verified, and whether an authorized person approved the final wording. It cannot infer the customer’s identity, motive, or legal position from tone. Nor does a response being polite prove that it is accurate. Analysis concerns whether the draft stayed within verified facts, protected private information, and routed any remedy or disputed claim to the right owner.',
    'A safe research design separates drafting from publication. A support role can locate the relevant record, summarize the issue without adding motive, draft from approved facts, and flag uncertainty. The business owner or named manager decides whether to publish, apologize, offer a remedy, disclose a status, or address a complaint. A draft should not include order details, contact information, internal notes, or a promise simply because those details might make the response sound more specific.',
    'Measure response quality with more than volume. Track factual correction rate, unsupported-claim findings, privacy redactions, owner edits, response age, escalation reason, and cases where a public draft was withheld. Inspect every disputed, sensitive, or remedy-related case and sample routine responses. A higher publication rate may mean better drafting, but it may also mean that the process is suppressing appropriate escalation. A lower response count can be evidence of better restraint.',
    'Use counterexamples to test the boundary. Include a review that names a product or appointment but lacks enough information to verify it, a review that contains private details, a complaint involving a refund or safety issue, and a plainly positive review where a simple factual acknowledgement is sufficient. The process should preserve what is known, avoid guessing, and identify the next decision. It should never edit the source record to make a public reply easier.',
    'Outsourced support boundaries. A Philippines-based specialist may prepare a neutral draft and link the approved source. The business retains publication, admissions, compensation, legal responses, privacy judgments, and claims about performance or customer outcomes. The role should not create testimonials, impersonate a customer, threaten a reviewer, reveal internal records, or decide that silence means approval. Named approval is part of the evidence, not an administrative afterthought.',
    'Limitations. This article is operational research, not legal advice, reputation-management certification, or a prediction of customer sentiment. Public FTC, NIST, and SBA guidance does not resolve a particular dispute or establish that any response is permitted in every jurisdiction. A sample cannot measure all future reviews, and a recorded approval cannot prove that every underlying fact was independently verified. Sensitive matters may require qualified counsel or a specialist.',
    'Evidence-led conclusion. Drafting support can improve reviewability when every public statement is tied to a verified source, privacy is treated as a stop condition, and publication and remedy decisions remain with the business. The evidence supports measuring correction, escalation, and withheld cases alongside response time. It does not support treating a polished public reply as proof that the underlying complaint was resolved.',
    'Owner review prompts. Which statements are directly verified? What information should never be public? Who can approve a remedy or admission? What happens when the review conflicts with the source record? Which cases must be withheld rather than drafted? These questions keep response work factual, bounded, and appropriate for a repeatable daily support routine.',
    'Additional interpretation. A public response is a small record with an unusually large audience, so the evidence threshold should be higher than for an internal note. The reviewer should be able to point from each factual assertion to an approved source without exposing the source itself. If the business cannot verify the date, service detail, or outcome, the draft should say less or wait for a decision. This is not a demand for a defensive or impersonal voice; it is a reminder that warmth cannot substitute for evidence. Review edits by reason: factual correction, privacy removal, tone adjustment, remedy approval, or legal escalation. Those categories show whether the process needs better source capture or whether the support role is being asked to decide beyond its boundary. Include withheld drafts in the sample because restraint is an outcome that volume reports do not show. A response process should also protect the original customer record and avoid turning a public claim into a new, unverified source. When a review is disputed, preserve the disagreement rather than asking the preparer to choose which account sounds more credible. The owner can decide whether to acknowledge, investigate privately, or obtain qualified advice. A small pilot across routine cases can reveal whether the draft is accurate and reviewable; it cannot prove improved reputation, customer loyalty, or business results. The defensible conclusion is therefore about evidence discipline: outsourced drafting may reduce preparation work when verified facts, privacy boundaries, approval identity, and escalation reasons remain visible.'
  ]}
];

export const augustTwentyResearchBatch = posts;
