export type AugustTwentyBlogPost = {
  slug: string; title: string; excerpt: string; focus: string; publicationDate: '2026-08-20';
  opening: string; sections: readonly [string, string][]; imagePath: string;
};

const operatingContext = (focus: string) => [
  `Small businesses often feel the cost of ${focus} before they have a clean way to describe it. An owner sees interruptions, missed handoffs, or questions returning to the same inbox, but a vague request to “help with operations” is not a safe work definition. Treat ${focus} as a bounded preparation lane: name the input, the source of truth, the expected record, the reviewer, and the point where an owner must decide. That structure makes outsourcing useful without quietly giving an outside operator authority over money, customer remedies, policy, staffing, or access.`,
  `Start by observing the current work for several normal cycles. Note where ${focus} begins, which systems are touched, what information is copied, and where the process pauses. Do not design from an ideal future state while ignoring the actual queue. A useful map distinguishes an event from a decision: a message can be recorded, while the answer to an unusual request may belong to the owner. Write down the interruptions and the repeated questions because they often reveal a missing rule rather than a staffing problem.`,
  `Define one work unit for ${focus}. It might be a single request, customer record, task, file, appointment, or review item. The unit needs a stable identifier, an observed date, a source link, a status, and a clear finish line. “Looked at” is not a finish line. A complete item should show what was checked, what was prepared, and whether a reviewer still needs to act. If a required source is unavailable, the correct result is a blocked record with a reason, not a guessed value or a silently carried-forward answer.`,
  `Build examples before granting wider access. Include one ordinary item, one incomplete item, one duplicate, one conflicting source, and one request that must be escalated. For ${focus}, examples should show the exact language of a useful note and the exact point where the operator stops. The goal is not to make every situation look routine. The goal is to make the boundary visible enough that a new person can recognize when the normal process no longer applies.`,
  `Use least-privilege access that matches ${focus}. A person preparing a record may need to read a queue or add a note, but that does not automatically authorize sending a commitment, changing a payment detail, editing a customer identity field, approving a refund, or changing a schedule. Use named accounts, keep secrets out of work notes, limit exports, and record where approved instructions live. The owner should be able to review and remove access without relying on the operator’s memory.`,
  `Create a handoff that answers one decision question. Put the source and identifier first, then the verified observation, the missing or conflicting information, the proposed next step if one is already approved, and the person who must decide. For ${focus}, avoid labels such as “urgent” unless the business has defined the term. Avoid promising an outcome because a queue is old. A short, linked, factual packet is easier to approve than a confident narrative that blends evidence with interpretation.`,
  `Review the first sample every day. Compare each prepared item with the source, the checklist, and the role boundary. Classify corrections rather than merely counting them: wrong source, missing field, unclear instruction, duplicate, late input, or escalation missed. If the same correction appears twice, improve the process definition before adding volume. A visible exception is safer than a polished record that hides the question an owner still needs to answer.`,
  `Measure ${focus} with evidence that helps an owner improve the lane. Track items received, prepared, blocked, returned for correction, awaiting clarification, and awaiting owner action. Add one quality sample and record the reason for each correction. Do not turn a high activity count into a claim about business results. The useful signal is whether the record is findable, the source is current, the next action is clear, and the boundary was respected.`,
  `Preserve continuity when the underlying work changes. Add a new observation when a customer replies, a vendor revises a file, a task moves, or an owner changes an instruction. For ${focus}, history lets a reviewer separate a preparation error from a later change in circumstances. Store the current SOP, examples, queue location, and escalation contacts where a backup operator can find them. Offboarding should remove access and preserve the work trail through the business’s approved process.`,
  `The owner’s closing review is simple: does this record contain enough evidence to act, and is the next action inside the approved role? If either answer is no, identify the missing source or decision and keep the item open. A small business gains from outsourcing when recurring preparation becomes easier to inspect and less likely to interrupt the owner. It does not gain when an outside helper becomes the unspoken approver for ${focus}.`
];

const topics: Array<[string,string,string,string,string,string]> = [
  ['outsource-small-business-weekly-capacity-planning-notes','How to outsource weekly capacity planning notes','Give owners a grounded view of available work and constraints without letting a coordinator promise capacity.','weekly capacity planning notes','A capacity note compares approved commitments, known availability, open constraints, and decisions still needed before work is assigned.','aug20-capacity-planning.png'],
  ['outsource-small-business-customer-renewal-reminder-queues','Build an outsourced customer renewal reminder queue','Keep renewal reminders visible while leaving terms, exceptions, and customer commitments with the business.','customer renewal reminder queues','A renewal queue records the account, relevant date, approved reminder, source, and escalation point without implying that renewal is guaranteed.','aug20-renewal-reminders.png'],
  ['outsource-small-business-service-scope-change-logs','Outsource service scope change logs safely','Record requested changes so an owner can review scope, evidence, and consequences before anyone promises extra work.','service scope change logs','A scope-change log distinguishes the original agreement, the new request, the source, and the decision needed before delivery changes.','aug20-scope-changes.png'],
  ['outsource-small-business-cash-collection-follow-up-records','How to outsource cash-collection follow-up records','Prepare factual follow-up records without making payment promises, changing terms, or pressuring a customer.','cash-collection follow-up records','A collection follow-up record captures the approved message, account source, observation, response, and owner decision point.','aug20-cash-followup.png'],
  ['outsource-small-business-project-dependency-maps','Create outsourced project dependency maps','Make handoffs and blockers visible without turning a map into an unsupported delivery forecast.','project dependency maps','A dependency map links a task to its prerequisite, source, owner, current state, and evidence for any claimed constraint.','aug20-dependency-maps.png'],
  ['outsource-small-business-inbox-intent-routing','Outsource small-business inbox intent routing','Sort incoming messages consistently while reserving interpretation, commitments, and sensitive handling for approved roles.','inbox intent routing','Intent routing assigns a message to an approved lane using its content and source, then exposes uncertainty instead of guessing.','aug20-inbox-routing.png'],
  ['outsource-small-business-training-completion-records','Outsource training completion records with care','Keep training evidence current without certifying competence or inventing completion from attendance alone.','training completion records','A completion record identifies the person, module, evidence, date, and reviewer who decides whether the requirement is satisfied.','aug20-training-records.png'],
  ['outsource-small-business-return-request-registers','Build a controlled return-request register','Give owners a clean view of return requests while keeping eligibility and remedy decisions within policy.','return-request registers','A return register records the request, source, item, policy reference, status, and decision still required.','aug20-return-registers.png'],
  ['outsource-small-business-local-listing-update-checks','How to outsource local listing update checks','Compare public business listing details with approved source information without publishing unverified changes.','local listing update checks','A listing check records the page, observed detail, approved source, discrepancy, and publication decision.','aug20-listing-checks.png'],
  ['outsource-small-business-recurring-vendor-deadline-calendars','Outsource recurring vendor deadline calendars','Make supplier deadlines easier to review without accepting a date as a commitment until the source is confirmed.','recurring vendor deadline calendars','A vendor calendar records the source date, deliverable, responsible party, confirmation status, and escalation rule.','aug20-vendor-calendars.png'],
  ['outsource-small-business-content-brief-readiness-checks','Run outsourced content brief readiness checks','Find missing inputs before drafting begins without approving claims, positioning, or publication on guesswork.','content brief readiness checks','A brief-readiness check compares the requested article, audience, source material, required review, and missing decision.','aug20-brief-readiness.png'],
  ['outsource-small-business-owner-decision-registers','Build an owner decision register for outsourced work','Give the owner a concise place to review open choices without hiding the records that support each question.','owner decision registers','A decision register names the question, source records, options already approved, deadline if supported, and accountable decision maker.','aug20-decision-registers.png']
];

export const augustTwentyBlogBatch: AugustTwentyBlogPost[] = topics.map(([slug,title,excerpt,focus,opening,image]) => ({ slug,title,excerpt,focus,opening,publicationDate:'2026-08-20',imagePath:`/blog-heroes/${image}`,sections: operatingContext(focus).map((p,i)=>[['Understand the real queue','Define the work unit','Write useful examples','Control access and authority','Prepare the handoff','Review early work','Measure evidence','Preserve continuity','Close with an owner decision','A practical operating rule'][i],p] as [string,string]) }));
