import { sharedResearchMethod } from './sep23-research';

const published = '2026-10-02' as const;
const checked = 'October 2, 2026';

const sources = {
  sba: { title: 'Manage your business', publisher: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business', checked },
  finance: { title: 'Manage your finances', publisher: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business/manage-your-finances', checked },
  irs: { title: 'Publication 583, Starting a Business and Keeping Records', publisher: 'Internal Revenue Service', url: 'https://www.irs.gov/publications/p583', checked },
  nistSmall: { title: 'NIST Cybersecurity Framework 2.0 for Small Business', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/itl/smallbusinesscyber/nist-cybersecurity-framework-0', checked },
  ftcSecurity: { title: 'Start with Security: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', checked },
  ftcScams: { title: 'Scams and Your Small Business: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/scams-your-small-business-guide-business-0', checked },
  ftcAds: { title: 'Advertising and Marketing Basics', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/advertising-marketing', checked },
};

const posts = [
  {
    slug: 'october-2-research-inbox-attachment-integrity',
    title: 'Inbox Attachment Integrity: Test Whether the Right File Reaches the Right Case',
    excerpt: 'Study attachment identity, quarantine, versioning, and case linkage before an outsourced inbox lane distributes customer files.',
    serviceHandoff: { href: '/services/customer-inbox-management', label: 'Scope a controlled inbox lane', description: 'Maintain attributable messages and file exceptions while identity, disclosure, remedies, and sensitive decisions stay with the business.' },
    referenceSources: [sources.ftcSecurity, sources.nistSmall, sources.sba],
    body: [
      'Decision in view. Shared inbox work becomes consequential when a message contains a document. A specialist can classify the email correctly yet attach the wrong estimate, forward a stale form, save a file under the wrong customer, overlook a password-protected attachment, or distribute a document whose recipient has not been verified. This study asks whether a bounded inbox lane can preserve file identity from receipt through storage, review, reply, and closure. The business is not testing whether the specialist can diagnose malware, decide disclosure rights, authenticate a requester by intuition, interpret a contract, or release confidential material. It is testing whether routine administration stops predictably when file provenance, version, recipient, or authority is uncertain.',
      'Evidence and inference. FTC security guidance tells businesses to understand the personal information they hold, keep only what is needed, limit access, protect information through its lifecycle, and plan for incidents. NIST small-business CSF guidance organizes cyber-risk work around Govern, Identify, Protect, Detect, Respond, and Recover. SBA operating guidance supports defined management processes. These sources do not certify an attachment, prescribe one scanning product, or decide who may receive a particular document. The operational inference is narrower: file handling should use stable identifiers, approved storage, minimum access, attributable actions, and a safe stop before any uncertain file is opened, moved, or sent.',
      'Study design and evidence map. Select one inbox, declared message categories, approved file types, and a consecutive window. Include ordinary attachments, cloud links, inline images, duplicate sends, corrected versions, empty files, encrypted files, unexpected archives, unsupported formats, very large files, and messages with no file despite referring to one. Preserve the source-message identifier, received timestamp and timezone, sender address as observed, conversation identifier, attachment name, media type, byte size, cryptographic hash where the system permits, storage reference, scanning state, case link, version relation, intended recipient, approval evidence, outbound message identifier, and cutoff disposition. Do not copy sensitive file contents into the study when a protected reference is sufficient.',
      'Control path and challenge cases. Use received, unopened-pending-control, blocked, approved-for-bounded-access, attributed, duplicate, superseded, case-linked, recipient-review, approved-to-send, sent, delivery-failed, recalled, corrected, and retained-under-policy states. Test two files with the same name but different contents; one file renamed without changing contents; a corrected file that arrives on a separate thread; an attachment whose customer number conflicts with the email subject; and a reply draft that still points to the superseded version. A specialist may record metadata, apply an approved scan path, link source and case, prepare a neutral exception, and use an already approved file. The specialist should not bypass a warning, upload to a personal tool, infer the correct customer from filename alone, or treat internal access as authority to disclose.',
      'Measures, decision rule, and limits. Reconcile all source messages to attachment records and report files received, unsupported or blocked items, exact duplicates, version conflicts, wrong-case candidates, recipient checks, approved sends, corrected sends, delivery failures, unresolved age, and owner interventions. Trace outbound files backward to their received or owner-created source; separately trace inbound files forward to final disposition. Expand only if every file remains attributable, uncertain content stops, approved and sent hashes agree, recipient evidence is present, and the queue exposes rather than hides unresolved items. A short pilot cannot establish malware absence, lawful disclosure, privacy compliance, contractual meaning, or recipient identity. File hashes show sameness, not safety or correctness. This is operational research, not cybersecurity, privacy, or legal advice.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'october-2-research-bookkeeping-refund-source-match',
    title: 'Bookkeeping Refund Matching: Test the Source Trail Before Closing an Exception',
    excerpt: 'Evaluate whether refunds are linked to the original transaction, processor event, and owner decision without assigning accounting judgment.',
    serviceHandoff: { href: '/services/small-business-bookkeeping', label: 'Design a source-linked bookkeeping lane', description: 'Prepare refund evidence and visible exceptions while treatment, posting, customer remedies, and money movement remain with authorized reviewers.' },
    referenceSources: [sources.irs, sources.finance, sources.nistSmall],
    body: [
      'Decision in view. A bank-feed credit labeled refund can relate to a returned purchase, card dispute, duplicate charge reversal, deposit correction, supplier credit, customer refund reversal, tax item, fee adjustment, or transfer. Matching by equal amount and nearby date may create a tidy ledger while attaching the wrong support. This study asks whether an outsourced preparation lane can connect a refund-like event to its original source chain and keep ambiguity visible for a qualified reviewer. It does not authorize the specialist to select accounting treatment, post an adjusting entry, determine tax consequences, decide a customer remedy, communicate a disputed position, or initiate or redirect money.',
      'Evidence and inference. IRS Publication 583 explains that business records and supporting documents should show transactions and support entries, and that electronic records must remain complete, accurate, retrievable, and reproducible. SBA finance guidance encourages regular control of business finances. NIST small-business guidance supports governed access and protection of information. None of these authorities says that matching fields prove the economic substance of a refund or dictates treatment for a particular business. We infer that preparation quality depends on a reconstructable relationship among the original event, refund request or notice, processor or bank event, amount components, dates, and authorized reviewer disposition.',
      'Population and matching graph. Choose one entity, currency, payment channel, and consecutive settlement window, then include every credit or reversal that meets a frozen identification rule. Keep partial refunds, multiple refunds against one transaction, one refund covering several lines, tips, shipping, tax, processor fees, foreign-exchange differences, store credit, chargebacks, voids, failed refunds, re-presentments, and unresolved events in the population. Record protected source identifiers, transaction and settlement dates, gross and net amounts, currency, processor event type, original order or bill reference, return or dispute reference, communication source, bank-feed identifier, candidate relationships, confidence reason, reviewer decision, correction history, and state at cutoff.',
      'Method and counterexamples. Build candidate edges from exact protected identifiers before considering amount, date, counterparty, memo, or narrative similarity. Preserve one-to-many and many-to-one possibilities instead of forcing a single row match. Use states such as source-captured, original-found, candidate-only, partial, fee-separated, currency-difference, credit-document-present, processor-pending, bank-posted, owner-review, reviewer-linked, reviewer-rejected, and unresolved. Challenge the procedure with two purchases for the same amount, a refund net of a fee, a partial return after a price change, a bank credit posted days later, and a chargeback that is not a merchant-issued refund. The specialist may assemble evidence and flag conflicts, but should never create missing support or close a candidate because month-end is near.',
      'Measures, decision rule, and limits. Report the eligible event count and value, source identifiers present, originals located, exact and non-exact candidates, partial relationships, fee or currency differences, reviewer acceptances and rejections, corrections, unresolved age, and items spanning cutoffs. Audit accepted links backward from bank event to original support and forward from refund notices to processor and bank outcomes. Expand only when the source population reconciles, identifiers survive imports, ambiguous matches stop, reviewer reversals remain bounded, and every closed relationship can be reproduced. Processor labels can change, feeds can duplicate or lag, and a correct operational link does not establish accounting, tax, audit, fraud, or legal treatment. This is an evidence-preparation study, not professional accounting or tax advice.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'october-2-research-backorder-promise-control',
    title: 'Backorder Promise Control: Test Customer Wording Against Fulfillment Evidence',
    excerpt: 'Measure whether stock gaps, supplier estimates, split shipments, and customer notices remain aligned before support makes a promise.',
    serviceHandoff: { href: '/services/ecommerce-order-support', label: 'Plan a controlled order-support lane', description: 'Prepare evidence-based order updates while substitutions, refunds, guarantees, inventory decisions, and exceptions stay with the business.' },
    referenceSources: [sources.ftcAds, sources.sba, sources.nistSmall],
    body: [
      'Decision in view. When an ordered item is unavailable, several dates may compete: a supplier estimate, purchase-order date, warehouse receipt forecast, replenishment calculation, storefront message, support template, and carrier label. Turning any one of them into a customer promise can create repeat contacts and remedies the business never approved. This study asks whether an outsourced ecommerce-support lane can distinguish evidence from estimates, keep split-order dependencies visible, and communicate only approved wording. It does not authorize inventory allocation, purchasing, substitutions, cancellations, refunds, compensation, guaranteed delivery, or a change to advertised terms.',
      'Evidence and inference. FTC advertising guidance says marketing claims must be truthful, non-deceptive, and evidence based. SBA guidance supports deliberate operating processes, while NIST small-business guidance supports governance, dependency awareness, and integrity. These sources do not establish a universal replenishment promise or decide rights for a specific sale. The operational inference is that support wording should name the actual state, source, observation time, uncertainty, and next review point. A supplier estimate is evidence that the supplier gave an estimate; it is not proof that inventory will be received, checked, allocated, packed, handed to a carrier, and delivered by that date.',
      'Cohort and event chain. Select one storefront, warehouse path, product family, and all order lines that enter an unavailable or delayed state during a consecutive window. Include partial stock, bundles, preorders, dropship items, split shipments, substitutions offered, cancellations, supplier changes, damaged receipts, allocation holds, address issues, and orders still unresolved at cutoff. Record order and line identifiers, quantity, inventory state at purchase and observation, storefront wording version, allocation event, supplier source and timestamp, purchase-order reference, expected and actual receipt events, inspection or release state, fulfillment decision, customer messages, approved remedy, shipment evidence, reopen events, and final disposition.',
      'Promise ladder and testing. Separate observed facts from conditional planning statements. Useful states include unavailable-confirmed, source-awaiting, supplier-estimate-recorded, estimate-expired, inbound-not-received, received-not-released, allocation-pending, allocated, split-approved, substitution-review, customer-choice-pending, cancel-review, ready-to-fulfill, shipped, and unresolved. Preapprove wording for each state and prohibit converting an estimate into certainty. Test a bundle with one missing component, a late supplier estimate, stock received but quarantined, two orders competing for one unit, and a label created before carrier acceptance. The specialist may reconcile status and prepare a message; the named owner decides allocation, remedy, and any exception to policy.',
      'Measures, decision rule, and limits. Report affected lines and customers, evidence-complete records, estimate changes, expired estimates, unsupported dates caught before sending, messages matching current state, split-order decisions, repeat contacts, cancellations, remedies, reopened cases, and unresolved age. Compare each sent statement with the evidence available at send time rather than with later hindsight. Reverse-sample confident date language and trace it to explicit approval. Expand only if inventory and supplier sources are time-stamped, state transitions reconcile, templates express uncertainty honestly, owner decisions reach support, and no unsupported guarantee escapes. A successful delivery does not validate earlier wording, and a missed estimate does not alone identify who caused delay. This is operational research, not consumer-law, logistics, inventory, or legal advice.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'october-2-research-supplier-payment-change-verification',
    title: 'Supplier Payment-Change Verification: Test the Handoff Without Moving Money',
    excerpt: 'Study whether changed remittance instructions are isolated, independently verified, and routed to an authorized owner.',
    serviceHandoff: { href: '/services/supplier-coordination', label: 'Design a controlled supplier lane', description: 'Maintain attributable requests and verification packets while bank-master changes, purchasing decisions, payment approval, and release stay with authorized owners.' },
    referenceSources: [sources.ftcScams, sources.ftcSecurity, sources.nistSmall, sources.sba],
    body: [
      'Decision in view. A supplier message that changes bank details can look routine while carrying disproportionate risk. The request may arrive in a genuine thread after an account compromise, from a lookalike domain, in a changed invoice, through a familiar contact using an unapproved channel, or alongside artificial urgency. This study does not ask an outsourced coordinator to judge fraud or validate a bank account. It asks whether the administrative handoff can isolate every payment-detail change, preserve the request, use an independently maintained contact path, and deliver a complete packet to people already authorized to change master data and approve payments.',
      'Evidence and inference. FTC small-business scam guidance warns that impostors create urgency, impersonate trusted organizations, and try to rush payments or access to sensitive information. FTC security guidance emphasizes access controls, information protection, and incident preparation. NIST small-business CSF guidance frames governance and protective, detective, response, and recovery outcomes. SBA guidance supports managed supplier operations. These sources do not authenticate a particular supplier or prescribe a universal verification ritual. We infer a safe administrative rule: changed payment instructions never flow directly from the requesting message into a payable or payment system; they enter a separate, attributable verification process.',
      'Request register and independence. Observe one supplier population and every request that adds or changes account name, bank, routing information, currency, payment channel, beneficiary, remittance address, portal, or payment timing. Record the exact source message, sender and reply-to as observed, domain, timestamp and timezone, affected supplier identifier, requested effective date, urgency language, attachments, related invoice, existing master-data version, preexisting contact method, verification attempts, responder identity under the approved process, owner decision, system change event, payment holds, and cutoff state. The independent contact path must come from a protected record established before the request, not a phone number or link inside the change message.',
      'Tabletop controls and authority. Use change-detected, isolated, payable-hold-requested, independent-contact-located, verification-attempted, conflict, owner-review, rejected, approved-by-authorized-owner, master-data-updated-by-authorized-role, second-review, and released states. Run read-only tabletop cases: an executive demands urgency; the supplier mailbox is genuine but the request conflicts with a prior contact; a PDF and email list different accounts; the known contact is unavailable; and a payment batch is imminent. A coordinator may recognize trigger fields, preserve headers and files, locate the approved contact route, schedule a verification, and escalate. They should not call a number from the request, reveal existing bank details, edit the supplier master, approve an exception, or release payment.',
      'Measures, decision rule, and limits. Report change requests, channels, isolation coverage, payment holds confirmed, preexisting contact paths found, verification attempts, conflicts, owner decisions, master-data events, second reviews, attempted bypasses, and requests unresolved at cutoff. Trace every master-data change backward to a registered request and approval; trace every registered request forward to rejection, approved change, or an active unresolved state. Expand only when the population reconciles, independence is demonstrable, urgent cases still stop, protected details remain minimized, and absence of an owner produces a hold rather than an improvised decision. A completed callback does not prove absence of compromise or legal validity. This is operational research, not banking, fraud, cybersecurity, accounting, or legal advice.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'october-2-research-public-review-record-minimization',
    title: 'Public Review Responses: Test Record Minimization Before a Draft Leaves the Queue',
    excerpt: 'Evaluate whether review-response drafts stay factual and useful without confirming private customer or service details.',
    serviceHandoff: { href: '/services/review-response-drafting', label: 'Scope a controlled review-response lane', description: 'Prepare neutral, source-linked drafts while identity, private records, remedies, admissions, threats, and publication decisions stay with the business.' },
    referenceSources: [sources.ftcAds, sources.ftcSecurity, sources.nistSmall, sources.sba],
    body: [
      'Decision in view. A public review may contain enough detail for staff to find a customer record, but finding a likely record does not authorize the business to confirm the relationship, dates, location, purchase, health or financial context, complaint history, or remedy in public. A draft can be factually accurate and still disclose too much. This study asks whether an outsourced drafting lane can produce a useful, neutral response from a deliberately minimized fact packet and stop sensitive cases. It does not authorize identity matching, public contradiction, admissions, legal positions, incentives, removal requests, compensation, or publication.',
      'Evidence and inference. FTC advertising guidance supports truthful and non-deceptive business communications. FTC security guidance advises businesses to know what personal information they hold, retain only what they need, restrict access, and protect it. NIST small-business CSF guidance frames governance and information protection, while SBA guidance supports managed customer processes. None supplies a universal reply template or determines the response required for a specific allegation. We infer that drafting should separate what the reviewer chose to publish from what the business knows privately, and should use the smallest approved factual packet needed to acknowledge and route the concern.',
      'Cohort and fact layers. Select one public platform, business profile, and consecutive review window. Include positive, neutral, negative, edited, deleted, duplicate, suspected-fake, employee-related, threatening, legally sensitive, accessibility-related, and unresolved reviews. Preserve the public review identifier, exact public text and rating at observation time, later edits, platform timestamp, business profile, objective category, sensitivity flags, owner-approved public facts, prohibited private fields, draft versions, reviewers, approval or hold reason, publication identifier, correction or removal event, and cutoff state. A protected customer record may be referenced by an authorized owner, but the drafting packet should not reproduce private details merely to make the draft sound specific.',
      'Redaction test and drafting boundary. Build drafts from an approved public-fact layer, then challenge each clause: does it confirm identity, relationship, service date, location, transaction, account state, diagnosis, dispute, refund, staff action, or prior contact that the business has not chosen to disclose? Use routine-positive, general-acknowledgment, private-channel-invitation, factual-correction-review, remedy-review, threat, privacy, legal, platform-report, and do-not-respond states. The specialist may classify, prepare restrained language, link the public source, and flag unsupported claims. They should not search broadly for a reviewer, quote private tickets, accuse the reviewer, invent empathy facts, promise an outcome, offer value for a changed review, or publish a sensitive draft.',
      'Measures, decision rule, and limits. Report the complete review population, sensitivity categories, records accessed, drafts prepared from minimized packets, disclosure defects caught, unsupported statements, owner rewrites, holds, approved publications, later corrections, and unresolved age. Blind-review drafts without the private file to see whether they remain coherent; separately have an authorized reviewer check that no sentence reveals protected context. Reverse-sample published responses to their approval and source version. Expand only if sensitive cases stop, private access is unnecessary for routine drafts, final text matches approval, edits reopen review, and public responses do not turn a dispute into a disclosure. This study cannot determine defamation, privacy law, platform enforcement, reviewer identity, or reputational impact. It is operational research, not legal or public-relations advice.',
      ...sharedResearchMethod,
    ],
  },
] as const;

export const octoberTwoResearchBatch = posts.map((post) => ({
  ...post,
  published,
  imagePath: '/filipino-support-workspace.jpg',
}));
