import { septemberNineBlogBatch, septemberNineResearchBatch } from './sep9-content';

const publicationDate = '2026-09-10' as const;
const blogTopics = [
['customer-onboarding-milestones','Track Customer Onboarding Milestones Without Promising a Launch Date','customer onboarding milestone tracking'],
['expense-receipt-matching','Match Expense Receipts Without Approving Reimbursement','expense receipt matching'],
['property-maintenance-intake','Triage Property Maintenance Requests Without Diagnosing the Repair','property maintenance request intake'],
['job-candidate-scheduling','Coordinate Candidate Interviews Without Making Hiring Decisions','candidate interview scheduling'],
['insurance-certificate-intake','Collect Insurance Certificates Without Certifying Coverage','insurance certificate intake'],
['customer-credit-request-packets','Prepare Customer Credit Request Packets Without Setting Credit Terms','customer credit request preparation'],
['website-content-change-queue','Run a Website Content Change Queue Without Publishing Unapproved Claims','website content change control'],
['service-renewal-reminders','Send Service Renewal Reminders Without Extending the Agreement','service renewal reminders'],
['warranty-claim-intake','Prepare Warranty Claim Intake Without Promising Eligibility','warranty claim intake'],
['training-attendance-records','Maintain Training Attendance Records Without Certifying Competence','training attendance records'],
['sales-call-note-cleanup','Clean Up Sales Call Notes Without Inventing Buyer Intent','sales call note cleanup'],
['delivery-exception-follow-up','Follow Up on Delivery Exceptions Without Guessing the Resolution','delivery exception follow-up'],
] as const;
const headings=['Set a narrow finish line','Work from the original record','Separate preparation from approval','Make incomplete work visible','Check the first live batch','Report what the queue really shows'] as const;
const openings=[
'Record the agreed onboarding steps, the customer owner, the internal owner, dependencies, and the source for each target date. Treat a date as proposed until the person responsible for delivery confirms it.',
'Match each receipt to the card or expense record by merchant, date, amount, and business purpose. A clean match is a prepared record for review, not permission to reimburse or book the expense.',
'Capture the location, reported symptom, urgency words used by the requester, access constraints, and photographs already supplied. Do not turn a caller\'s description into a technical diagnosis.',
'Offer only approved interview windows, record time zones, and confirm the participants and meeting link. Scheduling support should not rank applicants or imply that an interview guarantees progress.',
'Record the named insured, certificate holder, policy dates, document version, and requested destination. The operator can identify missing fields but cannot say whether the coverage satisfies a contract.',
'Assemble the application, references, requested limit, source documents, and missing items into one review packet. Do not calculate an approval or communicate terms that the credit owner has not set.',
'Capture the requested wording, page, requester, business reason, approver, and desired publish date. Draft and preview changes in a nonpublic state until the named owner approves the exact copy.',
'Use the contract record to prepare a reminder with the current end date, notice window, owner, and approved message. A reminder must not imply automatic renewal or agree to revised terms.',
'Collect the product identifier, purchase evidence, reported problem, photographs, contact details, and policy version. Intake is complete when the reviewer can assess the claim, not when the customer has been promised an outcome.',
'Record who attended, the session identifier, date, delivery method, and source attendance evidence. Attendance shows presence under the defined rule; it does not prove understanding or authorize work.',
'Attach the call recording or source notes, then normalize names, next steps, dates, and open questions. Mark uncertain language as uncertain rather than upgrading interest into purchase intent.',
'Record the order, carrier event, promised service level, customer contact, and latest verified scan. The support role can request an update but cannot invent a delivery date, refund, or replacement.',
] as const;
export const septemberTenBlogBatch=septemberNineBlogBatch.map((base,index)=>{const[slug,title,lane]=blogTopics[index];const copy=[openings[index],`Keep the request, attachments, later updates, and corrections linked to the ${lane} record. When sources conflict, show both values and ask the named owner; do not quietly select the value that closes the item.`,`For ${lane}, an outsourced specialist may collect records, label status, draft neutral follow-up, and prepare a review packet. Changes to money, contracts, access, customer remedies, compliance conclusions, or public promises remain with the named owner.`,`Use separate states for ready, waiting on evidence, conflicting records, outside scope, and owner decision required. Each hold should state the missing fact, the safe current state, the next question, and who can answer it.`,`Review every consequential case at launch and sample routine items from more than one source and operator. Compare the prepared result with the current instruction and linked evidence. Record the defect and correction in the queue, not only in private feedback.`,`Report received, prepared, held, corrected, escalated, and aging items with denominators. Add owner review time and repeated exception causes. Expand ${lane} only when a second person can reconstruct one completed case and one held case from the record.`] as const;return{...base,slug:`outsourcing-small-business-${slug}`,title,lane,excerpt:`A practical handoff for ${lane}, with source records, visible exceptions, and owner-held decisions.`,publicationDate,sections:headings.map((heading,i)=>[heading,copy[i]] as const)};});

const researchTopics=[
['source-link-coverage','Research: How Often Can Reviewers Reach the Source Behind Outsourced Work?','source-link coverage in an outsourced work queue'],
['exception-reopen-rate','Research: Which Outsourced Exceptions Reopen After Owner Review?','the rate and reasons that reviewed exceptions reopen'],
['handoff-wait-time','Research: Where Does Waiting Time Accumulate in an Outsourced Handoff?','waiting time across outsourced handoff stages'],
['checklist-drift','Research: Do Outsourced Checklists Drift From Current Instructions?','differences between active checklists and governing instructions'],
['approval-traceability','Research: Can a Small Business Reconstruct Outsourced Work Approvals?','approval traceability in outsourced work records'],
] as const;
export const septemberTenResearchBatch=septemberNineResearchBatch.map((base,index)=>{const[slug,title,topic]=researchTopics[index];return{...base,slug:`september-10-research-${slug}`,title,excerpt:`A bounded observational protocol for measuring ${topic}, with explicit scope, sources, and limits.`,published:publicationDate,body:[
`Research question and scope. This protocol asks how a small business can measure ${topic} in one named outsourced work lane during a predeclared observation window. One eligible task is the unit of analysis. Its record must include the source, instruction version, prepared output, timestamps, exception state, approval, and review result. Unrelated queues and records outside the window are excluded.`,
`Methodology. Register the window, eligibility rules, exclusions, field definitions, sampling rule, missing-data treatment, and stopping rule before reviewing results. Use consecutive eligible tasks rather than a convenient success sample. Two reviewers independently code a subset, retain their original labels, calculate agreement, and reconcile differences in a separate field.`,
`Measures. Report the eligible count and denominator, missing records, elapsed time by stage, exception category, correction and reopen counts, owner interventions, reviewer agreement, and review minutes. Separate routine work from cases involving money, access, customer remedies, contracts, or public claims. Absence of evidence is recorded as missing, not as a pass.`,
`Evidence context. NIST Cybersecurity Framework 2.0 supplies governance, access-control, and improvement concepts. U.S. Small Business Administration guidance supplies general management context. Federal Trade Commission business guidance supports accurate representation, and Google Search Central guidance supports people-first publication. These primary sources shape the protocol but do not establish the result of a local sample.`,
`Analysis and inference boundary. Describe observed counts, distributions, and associations for ${topic} within the declared records and period. Compare groups only when their definitions and denominators are reported. A difference may justify a limited process test, but it cannot show that outsourcing, a checklist, an approval step, or any individual caused the outcome.`,
`Limitations. System timestamps may reflect batch updates rather than work time. Deleted or off-platform messages can make a handoff look cleaner than it was. Reviewers may share assumptions, rare consequential events may not appear, and changes in staff, tools, queue mix, seasonality, or instructions can limit comparison. The findings do not establish provider-wide quality, profitability, legal compliance, security, or customer satisfaction.`,
`Decision rule and references. Expand the routine only if it meets the registered threshold, missingness is disclosed, every consequential exception reaches its named owner, and an independent reviewer can reconstruct a completed and a held item. Otherwise revise the intake, instruction, permission, or approval path and repeat a bounded test. References: NIST Cybersecurity Framework 2.0, https://www.nist.gov/cyberframework; U.S. Small Business Administration, Manage your business, https://www.sba.gov/business-guide/manage-your-business; Federal Trade Commission, Business Guidance, https://www.ftc.gov/business-guidance; Google Search Central, Creating helpful, reliable, people-first content, https://developers.google.com/search/docs/fundamentals/creating-helpful-content.`,
]};});
