export const septemberEighteenPublicationDate = '2026-09-18' as const;

type Topic = readonly [slug:string,title:string,excerpt:string,lane:string,decision:string,example:string,metric:string];
const topics:readonly Topic[] = [
  ['outsourced-bookkeeper-vs-virtual-assistant','Outsourced Bookkeeper vs. Virtual Assistant: Which Does Your Small Business Need?','Compare scope, controls, and first tasks before choosing bookkeeping or general administrative support.','bookkeeping and administrative support','whether the work requires accounting judgment or careful record preparation','A supplier invoice arrives with a new bank account and an assistant is asked to update the payment record.','matched transactions, unresolved exceptions, corrections, review minutes, and approvals'],
  ['in-house-vs-outsourced-customer-support','In-House vs. Outsourced Customer Support for a Small Business','Use ticket mix, coverage needs, and escalation load to choose a support model without guessing from headcount alone.','customer support','which customer conversations can follow approved guidance and which require an internal owner','A customer asks for a refund after an unusual service failure that is not covered by the saved replies.','first-response time, resolution time, reopen rate, escalations, QA defects, and owner review time'],
  ['outsource-payroll-admin-not-payroll-decisions','What Parts of Payroll Can a Small Business Outsource Safely?','Separate payroll preparation and exception chasing from pay, classification, and compliance decisions.','payroll administration','where administrative preparation ends and an authorized payroll decision begins','A missing clock-out conflicts with a manager note just before the payroll cutoff.','complete packets, missing records, corrections, disputed items, cutoff misses, and reviewer time'],
  ['outsource-social-media-or-keep-in-house','Should a Small Business Outsource Social Media Management?','Decide whether planning, production, moderation, and publishing can be delegated with truthful approval controls.','social media management','which messages may be scheduled from an approved plan and which public claims need business approval','A customer complaint appears under a scheduled promotion and asks for a remedy in public.','approved posts, publishing errors, response aging, escalations, corrections, and approval time'],
  ['outsourcing-pricing-models-hourly-retainer-dedicated','Hourly, Retainer, or Dedicated Outsourcing: How to Choose','Compare outsourcing pricing structures by workload shape, management effort, and evidence of value.','outsourcing commercial models','which arrangement fits the real queue without treating a low headline rate as total cost','A recurring support queue doubles during one seasonal month but is quiet for the rest of the year.','eligible volume, productive hours, rework, idle capacity, coverage gaps, and owner management time'],
  ['outsourcing-trial-project-scorecard','How to Score an Outsourcing Trial Project Before You Expand It','Build a trial scorecard that measures usable work, exceptions, and owner effort instead of activity alone.','outsourcing trial evaluation','whether evidence supports expanding, revising, or stopping the first delegated lane','The provider completes every assigned item, but half require the owner to reconstruct missing context.','accepted items, returned work, defect severity, exception accuracy, cycle time, and owner minutes'],
  ['outsourcing-data-access-first-week','What System Access Should an Outsourced Worker Get in Week One?','Grant enough access for a narrow first lane while keeping approvals, sensitive data, and recovery under control.','first-week system access','which minimum permissions are necessary for the tested task and who can revoke them','An assistant needs order status to answer customers but does not need refunds, exports, or user administration.','accounts issued, excess permissions found, blocked tasks, access exceptions, review findings, and removal time'],
  ['philippines-outsourcing-overlap-hours','How Many Overlap Hours Do You Need With a Philippines-Based Team?','Choose live overlap from handoff urgency, decision frequency, and customer coverage rather than habit.','Philippines team scheduling','which work needs a live decision window and which can move through a documented asynchronous handoff','A Manila-based coordinator finishes a decision packet after the owner has logged off, delaying a same-day reply.','handoff wait time, missed cutoffs, live escalations, coverage gaps, response aging, and after-hours load'],
  ['outsourcing-sop-readiness-test','Is Your SOP Ready for Outsourcing? A Practical Readiness Test','Test whether instructions, examples, exceptions, and ownership are clear enough for a controlled handoff.','SOP readiness','whether another person can complete normal work and stop correctly on an exception','The written procedure covers the happy path but does not explain what to do when two customer records conflict.','successful walkthroughs, clarification requests, exception accuracy, returned work, version errors, and review time'],
  ['outsourcing-provider-reference-check-questions','Reference Check Questions for a Small-Business Outsourcing Provider','Ask references about operating evidence, difficult cases, turnover, and exit support instead of seeking vague praise.','provider reference checks','what a reference can factually confirm and what still requires contract and trial evidence','A reference reports fast service but cannot explain how errors, access removal, or staffing changes were handled.','questions answered with examples, unresolved risks, control evidence, transition details, and follow-up items'],
  ['outsourcing-contract-exit-plan','The Outsourcing Exit Plan to Agree Before Work Starts','Protect continuity by defining account ownership, files, knowledge transfer, access removal, and final acceptance.','outsourcing exit planning','how the business can resume or transfer work without losing records or control','A provider relationship ends while open customer cases and provider-managed tool accounts remain active.','business-owned accounts, export completeness, open items, access removed, transfer defects, and acceptance time'],
  ['outsourcing-hidden-cost-calculator','How to Calculate the Hidden Management Cost of Outsourcing','Estimate setup, review, correction, coordination, tools, and transition work alongside provider fees.','outsourcing total-cost analysis','whether the delegated lane creates enough usable capacity after internal management work is counted','A low-cost service requires daily rewriting, duplicate data entry, and frequent owner approvals.','provider fees, setup hours, review hours, rework, tool costs, delay costs, and usable output'],
];

const sourceLinks = [
  ['U.S. Small Business Administration management guidance','https://www.sba.gov/business-guide/manage-your-business'],
  ['NIST Cybersecurity Framework 2.0','https://www.nist.gov/cyberframework'],
  ['Federal Trade Commission business guidance','https://www.ftc.gov/business-guidance'],
] as const;

export type SeptemberEighteenBlogPost = {
  slug:string; title:string; excerpt:string; lane:string; publicationDate:typeof septemberEighteenPublicationDate;
  imagePath:string; sections:readonly (readonly [string,string])[]; sources:typeof sourceLinks;
};

export const septemberEighteenBlogBatch:SeptemberEighteenBlogPost[] = topics.map(([slug,title,excerpt,lane,decision,example,metric]) => ({
  slug,title,excerpt,lane,publicationDate:septemberEighteenPublicationDate,imagePath:'/filipino-support-workspace.jpg',sources:sourceLinks,
  sections:[
    ['Start with the decision, not the job title',`A useful outsourcing choice begins with a specific work queue. For ${lane}, list the items arriving in a normal week, where they come from, what a usable result looks like, and what happens when the source is incomplete. The central decision is ${decision}. Write that boundary before comparing people or providers. A broad title can hide several different kinds of work, each with a different level of judgment and access. Follow ten recent examples from request to finish. Mark the steps that retrieve facts, organize records, apply an established rule, communicate an approved answer, or make a new business decision. That evidence gives you a scope you can price and test. It also prevents a proposal from quietly including risky authority simply because the task sounds routine.`],
    ['Map the real workload',`Count eligible items by day and week, including quiet periods and surges. Record arrival channel, due point, handling time, waiting time, common exceptions, languages, and any hours when a response is genuinely time-sensitive. Separate productive work from delay caused by missing information or owner approval. For ${lane}, use a small representative sample rather than a best-case demonstration. Include one ordinary item, one incomplete item, and one case that should be escalated. Note seasonal events and deadlines that could distort a short trial. This workload map helps distinguish a capacity problem from an unclear process. It also makes commercial comparisons fair: a quote for constant coverage is not comparable with a quote for a defined monthly volume unless both proposals state assumptions, exclusions, and overage treatment.`],
    ['Define the authority boundary',`Write what the outsourced worker may view, create, edit, send, schedule, export, approve, and close. Pair each permitted action with the evidence required first. Keep changes involving money, contracts, credentials, customer remedies, employment, compliance conclusions, or public claims with a named business owner until a narrow rule has been approved and tested. Consider this example: ${example} The instruction should tell the operator what can be prepared, what must remain unchanged, and exactly who receives the exception. Do not rely on “use good judgment” as a control. Named accounts, least-privilege permissions, multifactor authentication where supported, and a prompt offboarding path make the written boundary real. NIST Cybersecurity Framework 2.0 offers a useful governance and access-control reference, but the business still must adapt controls to its systems and risk.`],
    ['Build a source-backed handoff',`Every item needs an identifier, original request, source link, received time, current status, next action, and owner. Preserve later corrections instead of overwriting the history that explains a result. If two sources conflict, show both values and ask the authorized person; a tidy summary must not manufacture certainty. For ${lane}, design statuses that reveal whether the operator can act, awaits evidence, needs approval, or has finished with verifiable output. Avoid a single “in progress” state that hides waiting and rework. Store decisions with the work record rather than only in chat. A replacement operator should be able to reconstruct a completed item and a held item without somebody’s memory. That test exposes weak intake fields and private side channels before the lane grows.`],
    ['Compare options on the same evidence',`Give each candidate or operating model the same representative examples, boundary, service window, expected output, and evaluation method. Ask them to explain assumptions, demonstrate how an exception is routed, identify required permissions, and show the record an owner would review. Do not request real customer or employee data during an early comparison when redacted examples will answer the question. Compare the usable result and management burden, not presentation polish or a headline hourly rate. Ask what is excluded, how staffing changes are handled, who owns tool accounts and work product, how quality is sampled, and what happens at exit. The Federal Trade Commission’s business guidance is a useful reminder to assess claims carefully; a case study or reference is context, not proof that your business will achieve the same outcome.`],
    ['Run a reversible paid trial',`A trial for ${lane} should state its dates, eligible work, maximum volume, accounts, reviewers, communication rhythm, stop conditions, and acceptance rule. Use a queue large enough to show normal variation but small enough to inspect fully. Start customer-facing messages in draft mode when practical. Preserve questions and returned items because they reveal whether the instruction works. Review every consequential case and a random sample of routine work against the original source. If a defect could affect a customer, payment, account, or public statement, contain it first and then correct the process. Expand only the pieces that another trained person can reproduce. A trial is not successful merely because all items were marked complete; completion without usable evidence can create more owner work than it removes.`],
    ['Measure value without hiding owner work',`Track ${metric}. State the denominator for every rate and keep routine items separate from consequential exceptions. Record internal setup, coaching, review, correction, and coordination time, not just vendor invoices or worker hours. Speed without accuracy can move cost into rework, while high completion can hide rejected or reopened items. Compare the trial with a credible baseline from the same queue if one exists. If there is no baseline, report the trial plainly rather than inventing savings. The U.S. Small Business Administration’s general management guidance can help frame planning and oversight, but it does not validate a provider or guarantee an outcome. Decide in advance what evidence would support expansion, revision, or stopping so enthusiasm does not rewrite the test afterward.`],
    ['Ask practical questions before committing',`Ask who performs the work, who supervises it, how coverage and turnover are handled, where records are stored, and how the provider reports exceptions. Request a sample work record, quality review, access matrix, incident contact, and exit checklist with sensitive details removed. For ${lane}, ask the candidate to describe a time they stopped rather than guessed. Probe how they correct recurring defects and update instructions. Confirm fees, minimums, overages, paid leave or holiday assumptions, tool costs, notice periods, intellectual-property terms, confidentiality terms, and data-return steps in the actual agreement. Legal, tax, employment, privacy, and regulatory questions should go to qualified advisers for the relevant jurisdictions. Operational preparation can make those conversations clearer, but it is not a substitute for professional advice.`],
    ['Plan the first thirty days',`In week one, confirm scope, examples, access, owners, and the daily handoff. In week two, process a controlled sample and review it closely. In week three, revise fields, examples, permissions, and escalation rules based on observed defects. In week four, compare results with the predeclared decision rule and document what will expand, remain supervised, or stop. Keep one current instruction version and identify who may change it. Schedule access and quality reviews rather than assuming the launch configuration remains suitable. For ${lane}, publish a short owner dashboard showing completed work, aging, returns, exceptions, decisions needed, and review time. This sequence creates a proper routine for daily work while keeping the owner focused on meaningful decisions instead of monitoring every click.`],
    ['Use a clear go, revise, or stop decision',`Choose “go” only when the work is usable, the authority boundary held, exceptions reached the right owner, and the management cost fits the expected benefit. Choose “revise” when the lane is valuable but inputs, examples, permissions, staffing, or review rules need a bounded correction. Choose “stop” when the work depends on frequent undocumented judgment, access cannot be limited, evidence cannot be reconstructed, or the arrangement creates unacceptable customer or business risk. Document the reasons and the recovery action for open items. If you want help turning a repeatable lane into a controlled handoff, review the OutsourcingSmallBusinesses.com operations support service guide and bring a small sample of real, redacted work. The right starting point is a testable process, not a promise that every task belongs outside the business.`],
  ]
}));
