import { sharedResearchMethod } from './sep23-research';

const published = '2026-09-25' as const;
const checked = 'September 25, 2026';

const sources = {
  sba: { title: 'Manage your business', publisher: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business', checked },
  finance: { title: 'Manage your finances', publisher: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business/manage-your-finances', checked },
  irs: { title: 'Publication 583, Starting a Business and Keeping Records', publisher: 'Internal Revenue Service', url: 'https://www.irs.gov/publications/p583', checked },
  nist: { title: 'Cybersecurity Framework 2.0', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/cyberframework', checked },
  ftcSecurity: { title: 'Start with Security: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', checked },
  ftcAds: { title: 'Advertising and Marketing Basics', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/advertising-marketing', checked },
};

const posts = [
  {
    slug: 'september-25-research-customer-promise-ownership',
    title: 'Customer Promise Ownership: Test Whether Every Commitment Has an Authorized Owner',
    excerpt: 'Measure whether customer commitments remain attributable, bounded, and visible across an outsourced support handoff.',
    serviceHandoff: { href: '/services/customer-support', label: 'Design a controlled customer-support lane', description: 'Maintain source-linked commitments and follow-up queues while keeping remedies, exceptions, pricing, and policy decisions with the business.' },
    referenceSources: [sources.sba, sources.ftcAds, sources.ftcSecurity, sources.nist],
    body: [
      'Decision in view. A customer conversation can look resolved while a promised callback, delivery update, correction, credit review, or manager response has no authorized owner. Promise ownership means that every future-facing commitment is tied to the exact customer record, original wording, person who made it, authority basis, due condition, next owner, and final disposition. The buyer decision is whether an outsourced support lane preserves and routes commitments without inventing new ones. It is not authority to guarantee outcomes, change policy, offer money, admit liability, disclose protected information, or convert an estimate into a promise.',
      'Evidence and inference. SBA guidance supports managed customer-facing operations. FTC advertising guidance supports truthful representations, while FTC security guidance emphasizes knowing and limiting the information a business holds. NIST CSF 2.0 supplies governance, identity, protection, response, and recovery concepts. These sources do not define a universal response deadline or decide whether particular wording creates a legal obligation. We infer a narrower operational control: treat a recorded commitment as open until attributable evidence shows completion, withdrawal, supersession by an authorized person, or an owner-approved exception.',
      'Population and evidence. Select one customer queue, defined channels, one service family, and a consecutive intake window. Include resolved, reopened, escalated, duplicate, abandoned, disputed, and still-open contacts. Preserve message identifiers, received and sent times, actor, channel, exact commitment language, qualifying conditions, source facts, approval reference, customer deadline, responsible owner, dependencies, reminders, later changes, completion evidence, customer notice, and state at cutoff. Do not paraphrase away material conditions. A template may suggest language, but only the sent record shows what the customer actually received.',
      'Classification and boundary. Declare objective states: candidate commitment, authorized commitment, clarification required, assigned, waiting on dependency, fulfilled, owner-withdrawn, superseded, disputed, and unresolved. Keep customer request, worker statement, system estimate, and owner decision separate. A specialist may identify future-facing wording, link it to the source thread, assign an approved routine follow-up, and escalate uncertainty. The specialist should not decide whether ambiguous wording binds the business, promise a remedy, change a price or service term, or close a record because the expected date passed. Silence is not completion evidence.',
      'Measures and counterchecks. Report eligible conversations, candidate commitments, authorized commitments, records with named owners and due conditions, fulfilled commitments with evidence, overdue items, owner changes, customer-visible corrections, reopenings, disputes, and unknown states. Show counts beside rates and stratify by commitment type and consequence. Trace a sample from outgoing messages forward to closure, then trace closed commitment records backward to the exact customer-visible wording. Review messages classified as having no commitment so understated language and implied next actions do not disappear from the denominator.',
      'Decision and limitations. Expand only when authorized commitments are captured reproducibly, every open item has a reachable owner, unsupported wording stops before sending, changes remain visible, and completion can be reconstructed. If owners cannot service the exception queue, narrow the lane rather than granting broader discretion. A short window misses seasonal volume, rare remedies, staff absence, delayed fulfillment, and long-running disputes. Customer interpretation may differ from internal classification, and operational completion does not establish satisfaction or legal effect. This is operational research, not legal or consumer-protection advice. The bounded conclusion concerns preservation of customer commitments in one support lane.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'september-25-research-bookkeeping-source-completeness',
    title: 'Bookkeeping Source Completeness: Test the Queue Before Reviewing the Numbers',
    excerpt: 'Measure whether every in-scope financial record reaches a source-linked preparation queue without granting accounting authority.',
    serviceHandoff: { href: '/services/small-business-bookkeeping', label: 'Scope bookkeeping preparation', description: 'Build a complete, source-linked intake queue while qualified owners retain treatment, payment, filing, and close decisions.' },
    referenceSources: [sources.irs, sources.finance, sources.ftcSecurity, sources.nist],
    body: [
      'Decision in view. A bookkeeping queue can reconcile internally and still omit an inbox, card account, reimbursement form, processor report, cash record, corrected invoice, or newly opened account. Source completeness asks whether every declared input produced either a captured record or an explained zero for the period. It does not ask an administrative specialist to determine accounting treatment. The buyer decision is whether document collection, source reconciliation, missing-item follow-up, and exception preparation can be delegated while qualified owners retain classification, recognition, adjustment, payment, filing, and close approval.',
      'Evidence and inference. IRS Publication 583 discusses supporting documents and recordkeeping systems that clearly show income and expenses. SBA financial guidance encourages regular management of business finances. FTC security guidance and NIST CSF 2.0 support data minimization, access control, governance, and integrity. None prescribes the accounts, basis, close process, or evidence sufficient for a particular business. We infer an operational requirement: define the expected source population before collection, preserve identifiers and period evidence, reconcile arrivals to that population, and keep missing or ambiguous sources visible for an authorized reviewer.',
      'Population and source register. Choose one entity, one review period, and every owner-declared financial intake channel. Record source name, system or custodian, account suffix where safe, expected cadence, period coverage, statement or export identifier, opening and closing boundary, receipt time, file hash, page or record count, currency, known corrections, access owner, preparation state, and exception. Include sources with no activity, newly added or closed accounts, pending statements, unreadable files, duplicate deliveries, and owner-provided manual records. A blank folder is not evidence of zero activity.',
      'Reconciliation boundary. Use states such as expected, received, period-confirmed, duplicate, superseded, incomplete, unreadable, awaiting owner, unavailable, approved zero, and closed. The specialist may compare the register with received files, check objective coverage fields, retain versions, and request missing evidence through an approved channel. The specialist should not infer that silence means no transactions, choose an accounting period from convenience, edit a source statement, dismiss an unexplained gap, determine materiality, or approve the close. An export that ends early is incomplete even if its totals look plausible.',
      'Measures and tests. Report expected sources, received sources, confirmed period coverage, approved zero-activity sources, missing or partial sources, duplicates, corrected versions, unreadable records, late arrivals, owner decisions, and unresolved age. Show source counts and underlying record or value counts where authorized; one absent high-volume source should not look equivalent to one missing receipt. Reconcile the register to system administration records and prior-period sources, then reverse-sample prepared entries to source files. Investigate unexplained changes in cadence without assuming they are errors.',
      'Decision and limitations. Expand only if the source register is owner-approved, arrivals reconcile, versions remain attributable, gaps stop the relevant work, sensitive access stays narrow, and a qualified reviewer can reconstruct each exception. If ownership of accounts is unknown, repair governance before adding processing capacity. Manual cash activity, new products, processor reserves, foreign-currency records, delayed statements, and off-system reimbursements can defeat an apparently complete register. Completeness of declared sources does not prove all business activity was declared or that financial statements are correct. This is operational research, not accounting, tax, audit, or legal advice. The conclusion concerns evidence intake readiness.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'september-25-research-lead-routing-decision-latency',
    title: 'Lead Routing Decision Latency: Measure the Wait Without Rewarding Unsupported Speed',
    excerpt: 'Separate intake delay, owner decision time, and safe routing before expanding an outsourced lead-administration lane.',
    serviceHandoff: { href: '/services/lead-intake-administration', label: 'Plan a reviewable lead-intake lane', description: 'Prepare attributable lead records and approved routes while keeping targeting, claims, consent questions, pricing, and exceptions with the business.' },
    referenceSources: [sources.sba, sources.ftcAds, sources.ftcSecurity, sources.nist],
    body: [
      'Decision in view. A fast first touch can hide a slow or unsupported routing decision. A lead may wait for source verification, service-fit facts, territory ownership, suppression review, pricing authority, or a human decision while the dashboard records only form receipt and automated acknowledgment. Routing decision latency is the elapsed time between an attributable intake event and the first supported assignment, hold, rejection, or owner escalation. The buyer decision is whether an outsourced intake lane reduces avoidable waiting without guessing eligibility, consent, price, capacity, or sales claims.',
      'Evidence and inference. SBA management guidance supports deliberate operating processes. FTC advertising guidance supports truthful claims, and FTC security guidance supports limited collection and access. NIST provides governance and information-integrity concepts. These sources do not promise that faster contact improves conversion or determine whether outreach is permitted. We infer that a useful timing study must preserve event timestamps, separate automated events from decisions, expose waiting reasons, and measure accuracy and reversals beside speed. Otherwise the process can appear faster merely by routing uncertain records prematurely.',
      'Cohort and clock. Select one acquisition path, owner-approved geography, service family, and consecutive intake window. Include complete, incomplete, duplicate, spam-suspected, suppressed, misrouted, after-hours, existing-customer, unsupported, rejected, and unresolved records. Preserve the original source reference, capture time and timezone, wording version, requested service, customer-provided fields, transformations, suppression result, objective completeness checks, owner-approved rule version, assignment events, holds, escalations, first human review, reversals, and cutoff state. Define whether the clock pauses for a documented customer dependency before results are inspected.',
      'Authority and states. Separate received, attributable, duplicate-linked, minimum-fields-present, suppression-conflict, rule-matched, owner-review, assigned, rejected-by-owner-rule, contacted, reversed, and unresolved. A specialist may validate objective fields, apply a current owner-authored routing table, preserve provenance, and prepare a question. The specialist should not infer sensitive facts, reinterpret consent, invent fit, override suppression, quote unapproved pricing, promise availability, or route around a capacity decision. An instant assignment under an obsolete rule is a defect, not a success.',
      'Measures and counterchecks. Report the full cohort, time to attributable record, time to supported disposition, waiting time by owner and dependency, records meeting the declared rule, ambiguous holds, misroutes, reversals, duplicate contacts, suppression conflicts, owner interventions, and unresolved age. Publish medians with ranges or distributions rather than a single average, and keep counts visible. Compare a consecutive sample with the source evidence and current rule. Review very fast records for unsupported shortcuts and slow records for legitimate protective holds. Segment after-hours arrivals without pretending staffed and unstaffed periods are comparable.',
      'Decision and limitations. Expand only when provenance survives, the same rule produces the same route, uncertainty stops, protected states remain protected, reversals are rare and explained, and owner queues have capacity. If owner decisions dominate elapsed time, changing intake labor will not remove the bottleneck. Short studies miss campaign shifts, outages, seasonality, staffing changes, and delayed corrections. CRM timestamps may reflect synchronization rather than human action; a quick assignment does not prove contact quality, permission, revenue, or customer value. This is operational research, not marketing, privacy, telecommunications, or legal advice. The conclusion concerns one routing process.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'september-25-research-supplier-substitution-control',
    title: 'Supplier Substitution Control: Test the Handoff Before an Alternative Becomes an Order',
    excerpt: 'Separate supplier-proposed alternatives from owner-approved substitutions in a source-linked coordination queue.',
    serviceHandoff: { href: '/services/supplier-coordination', label: 'Design a supplier-coordination lane', description: 'Maintain dated proposals and exception packets while purchases, substitutions, changed terms, disputes, and customer promises stay with the owner.' },
    referenceSources: [sources.sba, sources.ftcAds, sources.nist],
    body: [
      'Decision in view. When an item, material, carrier, schedule, or service becomes unavailable, a supplier may propose an alternative that looks equivalent in an email summary but changes specification, quantity, price, lead time, warranty, origin, compatibility, or a customer commitment. Substitution control is the evidence trail from requested item through supplier proposal, affected dependencies, owner decision, and final acknowledgment. The buyer decision is whether an outsourced coordination lane can assemble and track that packet. It is not authority to accept an alternative, change terms, issue a purchase, or promise the result downstream.',
      'Evidence and inference. SBA guidance places supplier and operational management within running a business. NIST CSF 2.0 emphasizes governance, dependencies, current information, and risk response. FTC advertising guidance supports truthful customer-facing representations. These sources do not determine equivalence or authorize any purchase. We infer that alternatives should be recorded as proposals until the designated owner compares the relevant attributes and records a decision. Similar names, supplier assurances, prior acceptance, or system defaults are not substitutes for current scoped approval.',
      'Population and packet. Select one supplier group, purchasing category, destination, and observation window. Include accepted, rejected, expired, withdrawn, duplicate, partial, disputed, and unresolved proposals. Preserve the original request and version, requested identifier, supplier identity, proposal source and timestamp, alternative identifier, specification or service description as supplied, quantity, unit, location, price and currency, terms reference, lead time, dependencies, affected customer or operating promise, questions, owner, decision, decision conditions, acknowledgment, order reference, later changes, and cutoff state.',
      'Workflow boundary. Use states such as requested, unavailable, alternative-proposed, evidence-incomplete, impact-review, awaiting-owner, approved-with-conditions, rejected, expired, ordered-by-authorized-owner, supplier-acknowledged, changed-again, and closed. The specialist may request missing objective fields, compile a side-by-side record, flag affected deadlines, and follow up on a recorded decision. The specialist should not declare equivalence, negotiate or accept terms, change quantities, select a vendor, release funds, issue an order, or tell a customer the substitute is confirmed. No response from the owner is not approval.',
      'Measures and counterchecks. Report original requests, unavailable items, proposals, packets with required fields, proposals held for missing evidence, owner decisions, time awaiting owner, conditional approvals, post-decision supplier changes, orders matching the recorded decision, downstream promises reviewed, disputes, and unresolved age. Show counts and consequence categories. Trace approved substitutions forward to supplier acknowledgment and the authorized order; reverse-sample alternative items from final records back to the owner decision. Review rejected and expired proposals so only easy approvals do not define performance.',
      'Decision and limitations. Expand only if proposals remain visibly provisional, required comparisons are complete, dependencies surface, approvals are attributable and current, final records match conditions, and changes reopen review. If specifications live in inaccessible systems or owner decisions routinely expire, fix those dependencies before increasing volume. Supplier data can be wrong, product names can conceal material differences, exchange rates and freight can change cost, and later events can invalidate a sound earlier decision. A complete packet does not prove equivalence, fitness, availability, or legal compliance. This is operational research, not procurement, engineering, safety, or legal advice. The conclusion concerns substitution-handoff integrity.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'september-25-research-outsourced-access-removal',
    title: 'Outsourced Access Removal: Test Whether the Offboarding Record Matches Reality',
    excerpt: 'Verify accounts, tokens, shared resources, ownership transfers, and residual access after a small-business work lane changes.',
    serviceHandoff: { href: '/services/operations-support', label: 'Scope a controlled operations lane', description: 'Maintain access inventories and evidence packets while account administration, security decisions, and incident response remain with authorized owners.' },
    referenceSources: [sources.nist, sources.ftcSecurity, sources.sba],
    body: [
      'Decision in view. An offboarding checklist can say complete while an account remains active, a token still works, a group grants inherited access, a shared mailbox retains forwarding, an automation runs under the departing identity, or a business-owned file has no new owner. Access removal is therefore a tested state, not a checked task. The buyer decision is whether an outsourced operations lane can maintain the inventory, coordinate evidence, and surface residual access. It is not permission to administer identities, investigate people, delete records, transfer ownership, or declare a security incident resolved.',
      'Evidence and inference. NIST CSF 2.0 organizes cybersecurity outcomes around governance, identity and access, protection, detection, response, and recovery. FTC security guidance advises businesses to know what information they keep, limit access, and protect it. SBA guidance supports managed operations. These sources do not prescribe a universal offboarding interval or toolset. We infer that a small business needs a current inventory tied to named owners, an authorized removal action for every access path, independent confirmation, preservation of required business records, and a visible route for anything that cannot be verified.',
      'Scope and inventory. Choose one genuine role change or an owner-approved read-only exercise; do not disable production access merely to run research. Declare systems, named accounts, groups, roles, devices, application passwords, API tokens, integrations, shared mailboxes, forwarding rules, calendars, file shares, repositories, billing portals, recovery methods, vendor consoles, and physical credentials that are in scope. Record system owner, identity, access basis, privilege, inherited path, business data ownership, last review, requested action, authorized actor, action time, evidence reference, verification method, residual dependency, exception owner, and cutoff.',
      'Control boundary. Separate disable, revoke session, rotate secret, remove group, transfer ownership, preserve record, remove device, confirm vendor action, exception-approved, and verified-no-access. The specialist may reconcile the declared inventory, prepare owner-approved tickets, collect non-sensitive evidence references, and chase unresolved confirmations. The specialist should not view secrets, impersonate the worker, delete content, change recovery ownership, rotate production credentials, infer malicious intent, or perform administrator actions without explicit authorization. Loss of interactive login does not prove tokens, delegated access, or integrations stopped.',
      'Measures and tests. Report inventoried access paths, paths with named system owners, authorized actions, completed actions, independently verified removals, ownership transfers, retained records, residual access, unknown states, exceptions, elapsed time, and systems discovered outside the inventory. Show counts by privilege and consequence. Reconcile identity-provider groups with application-local roles where available, inspect owner-approved audit evidence, and test only through safe administrator views or sanctioned test accounts. Reverse-sample active accounts against the current workforce and provider register. Never attempt unauthorized login as a verification method.',
      'Decision and limitations. Expand the lane only when the inventory is current, actions are attributable, business records retain owners, residual access escalates, verification is independent enough for consequence, and the backup owner can complete the process. If a vendor cannot expose access state, record the limitation and choose an owner-approved compensating action rather than marking complete. Hidden integrations, cached sessions, unmanaged devices, delayed vendor processing, and shadow systems can survive the cutoff. Absence from one console does not prove absence everywhere, and this test does not establish that no data was copied. This is operational research, not cybersecurity, forensic, privacy, employment, or legal advice. The conclusion concerns one offboarding control.',
      ...sharedResearchMethod,
    ],
  },
] as const;

export const septemberTwentyFiveResearchBatch = posts.map((post) => ({
  ...post,
  published,
  imagePath: '/filipino-support-workspace.jpg',
}));
