import { sharedResearchMethod } from './sep23-research';

const published = '2026-09-28' as const;
const checked = 'September 28, 2026';

const sources = {
  sba: { title: 'Manage your business', publisher: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business', checked },
  finance: { title: 'Manage your finances', publisher: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business/manage-your-finances', checked },
  irs: { title: 'Publication 583, Starting a Business and Keeping Records', publisher: 'Internal Revenue Service', url: 'https://www.irs.gov/publications/p583', checked },
  nist: { title: 'Cybersecurity Framework 2.0', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/cyberframework', checked },
  ftcSecurity: { title: 'Start with Security: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', checked },
  ftcAds: { title: 'Advertising and Marketing Basics', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/advertising-marketing', checked },
  copyright: { title: 'Copyright Basics, Circular 1', publisher: 'U.S. Copyright Office', url: 'https://www.copyright.gov/circs/circ01.pdf', checked },
};

const posts = [
  {
    slug: 'september-28-research-inbox-escalation-closure',
    title: 'Inbox Escalation Closure: Test Whether the Owner Decision Reaches the Customer Thread',
    excerpt: 'Measure whether sensitive inbox escalations remain open until an authorized decision is reflected in the customer-visible record.',
    serviceHandoff: { href: '/services/customer-inbox-management', label: 'Scope a controlled customer-inbox lane', description: 'Maintain source-linked triage and follow-up while sensitive replies, remedies, account decisions, and policy exceptions stay with the business.' },
    referenceSources: [sources.ftcSecurity, sources.nist, sources.sba],
    body: [
      'Decision in view. An inbox dashboard can show an escalation as complete when the owner answered an internal question but nobody updated the customer thread, recorded the authorized wording, or confirmed the next action. The customer then waits while the internal queue looks healthy. Escalation closure means that the original message, classification, owner decision, permitted response, customer-visible action, and remaining obligation form one traceable chain. The buyer decision is whether an outsourced inbox lane can maintain that chain and expose broken handoffs. It is not authority to decide refunds, account access, privacy requests, contractual meaning, legal positions, service recovery, or policy exceptions.',
      'Evidence and inference. FTC security guidance advises businesses to know what personal information they keep, retain only what is needed, control access, and protect information throughout its lifecycle. NIST Cybersecurity Framework 2.0 describes governance, roles, protection, response, recovery, and continuous improvement. SBA management guidance supports deliberate operating processes. None of these sources defines when a specific customer dispute is substantively resolved or supplies a universal response target. We infer a narrower operational rule: a sensitive thread remains open until an authorized disposition is joined to the correct source record and any promised customer-facing action has attributable evidence.',
      'Population and unit of analysis. Choose one shared inbox, a consecutive intake window, declared message types, and a cutoff long enough to observe owner decisions. Include routine questions that became sensitive, duplicate threads, forwarded messages, spam later restored, reopened conversations, requests moved to another system, customer withdrawals, and items still waiting at cutoff. Treat the conversation as the unit, while preserving individual message identifiers. Record received time and timezone, sender and recipient channels, account reference where permitted, classification version, reason for escalation, evidence links, owner assigned, decision request, decision time, approved language, sender of the final response, delivery evidence, follow-up date, reopen event, and state at cutoff.',
      'State model and authority boundary. Use states such as received, attributable, routine, sensitive-review, awaiting-source, awaiting-owner, decision-recorded, response-approved, response-sent, delivery-failed, follow-up-due, reopened, withdrawn, and closed-with-evidence. The specialist may classify under a written rule, gather linked facts, prepare a neutral draft, remind the named owner, and send only within tested authority. The specialist should not treat an internal comment as customer notice, disclose data from another account, authenticate through improvised questions, promise a remedy, interpret law or contract, delete the original, or close an item because an aging target is near. A customer saying thanks may be relevant, but it does not erase a documented unfinished action.',
      'Measures and counterchecks. Report eligible conversations, escalations, escalations with complete decision packets, owner wait time, decisions translated into approved replies, replies with delivery evidence, follow-ups completed, reopened threads, wrong-thread attachments, customer-visible corrections, unresolved items, and age by consequence. Show counts beside rates and separate owner decision latency from specialist preparation and sending latency. Trace a sample of sensitive incoming messages forward through the final customer record. Reverse-sample closed escalations back to the triggering message and authority evidence. Review apparently fast closures for unsupported shortcuts, and compare the shared inbox with any task system so moving a record cannot remove it from the denominator.',
      'Decision and limitations. Expand the lane only when the eligible population reconciles, sensitive categories stop reliably, owner decisions remain attributable, approved wording reaches the correct thread, promised follow-ups recur in an active queue, and closure evidence survives independent review. If owners cannot answer escalations at the declared cadence, narrowing intake or adding a backup decision owner is more honest than granting the specialist judgment authority. Short studies miss rare privacy, threat, legal, and account-takeover cases. Email delivery does not prove comprehension or satisfaction, and an operationally closed thread does not establish that the underlying dispute was fairly or legally resolved. This is operational research, not legal, privacy, or customer-remedy advice.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'september-28-research-duplicate-invoice-screening',
    title: 'Duplicate Invoice Screening: Test the Preparation Queue Before Payment Review',
    excerpt: 'Evaluate whether repeated supplier documents are linked and held for review without granting payment or accounting authority.',
    serviceHandoff: { href: '/services/small-business-bookkeeping', label: 'Design a source-linked bookkeeping lane', description: 'Prepare invoice records and visible exceptions while classification, vendor changes, payment release, and accounting decisions stay with authorized reviewers.' },
    referenceSources: [sources.irs, sources.finance, sources.ftcSecurity, sources.nist],
    body: [
      'Decision in view. Duplicate invoices rarely arrive as identical files in one folder. A supplier may resend an invoice, correct a tax or address field, change the file name, split a charge, reuse a number across entities, attach a statement copy, or issue a replacement that resembles a second obligation. Duplicate screening asks whether the preparation lane can recognize plausible repeats, preserve every source, link versions, and place uncertainty before a reviewer. It does not ask a specialist to decide that a liability is valid, alter supplier master data, post an accounting entry, release money, recover a payment, or accuse a supplier of misconduct.',
      'Evidence and inference. IRS Publication 583 describes records and supporting documents that show business income and expenses and support entries. SBA financial guidance encourages regular management of business finances. FTC security guidance and NIST CSF 2.0 support limited access, integrity, governance, and accountable handling. These sources do not define a universal duplicate algorithm, prove an invoice is owed, or replace accounting controls. We infer that screening is useful only when it begins with a declared document population, preserves source and version identity, uses explainable comparison fields, and routes possible matches without silently deleting or merging evidence.',
      'Population and comparison record. Select one legal entity, a bounded supplier set, every declared invoice channel, and a consecutive receipt period. Include emailed files, portal downloads, scans, statements, corrected copies, credit notes, recurring invoices, deposits, partial bills, multi-currency documents, handwritten records, rejected items, and unresolved candidates. Capture source message or portal reference, receipt timestamp, supplier identity as shown, owner-approved supplier identifier, invoice number exactly as printed, invoice and service dates, currency, gross amount, purchase or job reference, bank-detail-change indicator, attachment hash, page count, revision wording, related credit, prior candidate links, reviewer disposition, and cutoff state.',
      'Screening logic and boundary. Declare comparison layers before inspecting outcomes: exact file hash; normalized supplier, number, currency, and amount; repeated purchase reference; near dates and amounts; shared line descriptions; and explicit replacement language. Keep exact duplicate, apparent resend, corrected version, possible duplicate, related but distinct, split billing, statement copy, credit-related, insufficient evidence, reviewer-released, and held states separate. A specialist may calculate candidates and assemble a side-by-side packet. The specialist should not discard a source, edit identifiers to force a match, infer supplier identity from bank data alone, approve a new account, determine tax treatment, select which version to book, or clear a candidate because the due date is close.',
      'Measures and challenge tests. Report total documents, unique source events, exact hashes, rule-generated candidates, candidate pairs rather than only documents, confirmed repeats, corrected versions, legitimate similar invoices, unresolved candidates, reviewer reversals, already-paid matches, late discoveries, and time awaiting decision. Precision without recall is misleading, so seed only owner-approved synthetic examples in a safe test environment or retrospectively test known historical dispositions without changing records. Review false positives by invoice type and supplier, and search a consecutive paid sample backward for repeated identifiers or source files. Keep the rule version with every result so a later threshold change cannot rewrite the original screen.',
      'Decision and limitations. Expand preparation only when all declared channels reconcile, high-consequence candidates stop before payment review, original files remain available, similarity reasons are understandable, supplier changes escalate, and authorized reviewers can distinguish corrections from separate obligations. If the supplier register is incomplete or invoices bypass declared channels, repair intake before tuning a matching score. OCR errors, reused invoice numbers, currency conversions, consolidated statements, recurring equal amounts, and legitimate split invoices can mislead a screen. A clean screen does not prove the invoice is accurate, authorized, correctly classified, unpaid, or nonfraudulent. This is operational research, not accounting, audit, tax, fraud, procurement, or legal advice.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'september-28-research-order-address-change-verification',
    title: 'Order Address Changes: Test the Verification Handoff Before Fulfillment',
    excerpt: 'Study whether post-order address requests pause safely, preserve provenance, and reach an authorized fulfillment decision.',
    serviceHandoff: { href: '/services/ecommerce-order-support', label: 'Plan a controlled ecommerce-support lane', description: 'Prepare verified order updates and exception packets while identity, rerouting, refunds, replacements, and delivery promises remain with authorized owners.' },
    referenceSources: [sources.ftcSecurity, sources.nist, sources.ftcAds, sources.sba],
    body: [
      'Decision in view. A post-order address request may be a harmless correction, a carrier limitation, a customer-service issue, or an attempt to redirect goods. Speed alone is unsafe: support can update the wrong order, expose account data, override a fulfillment lock, or promise rerouting after a parcel is committed. Address-change control is the chain from the original order and request channel through approved verification, fulfillment state, authorized decision, system action, and customer notice. The buyer decision is whether outsourced support can prepare and track that chain. It is not authority to authenticate by intuition, change fraud settings, override carrier controls, refund, replace, or guarantee delivery.',
      'Evidence and inference. FTC security guidance emphasizes collecting only needed information, restricting access, using sound authentication practices, and protecting data in use and disposal. NIST CSF 2.0 frames identity, access, protection, response, and recovery as governed outcomes. FTC advertising guidance supports accurate customer-facing representations, while SBA guidance supports managed operations. These authorities do not prescribe one verification method for every store or establish liability for a rerouted order. We infer an operational principle: an address request should be bound to the correct order, handled under a current owner-approved rule, and stopped whenever identity, timing, system state, or authority is uncertain.',
      'Cohort and evidence capture. Select one storefront, fulfillment path, destination region, and consecutive request window. Include requests before picking, during packing, after label creation, after carrier acceptance, after attempted delivery, and after delivery; also include duplicate, abandoned, denied, mistyped, gift, subscription, marketplace, split-shipment, and reopened cases. Preserve order identifier, original address in the protected system, request source and timestamp, authenticated-session evidence reference rather than secret answers, requested change, fulfillment events, payment-risk flags visible to the authorized role, applicable rule version, decision owner, carrier or warehouse response, system change audit event, customer wording, delivery result, and cutoff state.',
      'State and access boundary. Use requested, order-linked, verification-pending, verification-passed-under-rule, verification-failed, fulfillment-hold-requested, hold-confirmed, too-late-under-rule, owner-review, authorized-change, denied, carrier-requested, customer-notified, delivery-exception, and closed states. The specialist may link records, apply objective steps, request a sanctioned hold, prepare options, and send approved status language. The specialist should not ask for unnecessary identity data, reveal the stored address before verification, bypass account controls, copy payment information, interpret a fraud score, edit carrier data without authority, or state that an address changed until the source system confirms it. An internal ticket is not a warehouse hold.',
      'Measures and scenario review. Report eligible requests, correctly linked orders, verification outcomes, holds requested and confirmed, requests arriving after each fulfillment milestone, owner decisions, authorized system changes, conflicting warehouse or carrier states, duplicate actions, customer corrections, delivery exceptions, unauthorized disclosures, unresolved age, and final evidence coverage. Stratify by fulfillment stage because a favorable pre-pick result says little about in-transit cases. Trace requests forward to the order and shipment audit trail, then reverse-sample changed shipping records back to a verified request and approval. Walk through tabletop cases for split shipments, gifts, subscription renewals, marketplace restrictions, and an unavailable owner without touching real orders.',
      'Decision and limitations. Expand only if requests bind reliably to the right order, verification uses the approved path, holds are confirmed rather than assumed, system changes match the decision, customer language reflects actual carrier state, and exceptions remain visible. If the support platform cannot expose fulfillment transitions promptly, narrow the lane to preparation and escalation. Customer accounts can be compromised, carrier scans can lag, warehouse cutoffs can change, and successful delivery does not prove the request was authentic. The study cannot establish fraud absence, legal compliance, carrier performance, or customer satisfaction. This is operational research, not identity, fraud, security, logistics, insurance, or legal advice.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'september-28-research-dashboard-denominator-control',
    title: 'Dashboard Denominator Control: Test Whether a Better Rate Hides Missing Work',
    excerpt: 'Measure whether owner dashboards preserve eligible populations, exclusions, and late records before staffing decisions rely on them.',
    serviceHandoff: { href: '/services/owner-dashboard-reporting', label: 'Build a source-linked owner dashboard', description: 'Maintain approved measures, refresh evidence, and data exceptions while definitions, targets, interpretation, and business decisions remain with the owner.' },
    referenceSources: [sources.sba, sources.finance, sources.nist],
    body: [
      'Decision in view. A service rate can improve because the team worked better, but it can also improve because unresolved records dropped from a filter, a new channel was omitted, deleted items disappeared, late events fell after cutoff, or the denominator definition changed. Denominator control means every reported rate retains an attributable eligible population, explicit exclusions, cutoff rule, source coverage, and versioned definition. The buyer decision is whether an outsourced reporting lane can refresh that evidence consistently and surface gaps. It is not authority to choose targets, redefine success after results appear, forecast outcomes, evaluate staff, or decide what the business should do.',
      'Evidence and inference. SBA guidance treats financial and operational review as part of managing a business, and its financial guidance encourages regular attention to records and performance. NIST CSF 2.0 emphasizes governance, information integrity, defined responsibilities, and continuous improvement. These sources do not prescribe a dashboard formula or validate a particular KPI. We infer that a decision-grade rate requires more than a numerator: the business must be able to reconstruct which records were eligible, which were excluded and why, what arrived late, which systems were covered, and which definition version generated the displayed value.',
      'Metric register and population. Choose one owner decision and no more than a few measures used for it. For each measure record its plain-language question, accountable owner, unit of analysis, source systems, eligible states, numerator rule, denominator rule, exclusions, duplicate handling, timezone, event-time field, cutoff, late-arrival treatment, refresh cadence, historical revision policy, expected source controls, and display rounding. Freeze those rules before comparing periods. Preserve record identifiers or privacy-safe keys sufficient to reproduce membership. Include zero-activity sources, unresolved records, transferred work, deleted or merged items when audit history permits, system outages, manual corrections, and records awaiting classification.',
      'Refresh workflow and boundary. Use states such as expected-source, received, coverage-confirmed, incomplete, stale, schema-changed, duplicate, excluded-by-declared-rule, eligibility-unknown, calculated, reconciled, owner-reviewed, published, and superseded. A reporting specialist may retrieve authorized fields, run a documented transformation, reconcile counts, flag anomalies, and annotate missingness. The specialist should not silently substitute a convenient timestamp, remove an outlier, impute an unknown, change a filter to match expectations, blend unlike channels, edit source data, or publish a revised definition as though it were continuous history. A blank value is not zero, and a record outside the reporting tool may still belong in the business population.',
      'Tests and measures. For every displayed rate, publish numerator count, denominator count, exclusion count by reason, unknown eligibility, late arrivals, duplicate removals, source coverage, refresh time, and definition version. Recompute a sample directly from source records and reconcile dashboard totals to source control totals. Compare current membership with the prior period and explain large additions or removals. Run boundary tests around midnight, status changes, reopened work, merged records, and the cutoff. Inspect apparently improved rates for falling denominators, rising unknowns, work transferred to unmeasured queues, and corrections after publication. Measure reproducibility by having a second reviewer run the frozen rule.',
      'Decision and limitations. Rely on the dashboard only when source coverage is known, population membership can be reconstructed, exclusions are bounded, definition changes are visible, late data follows a declared policy, and a second reviewer can reproduce material figures. If a source system cannot provide stable identifiers or historical states, label the metric provisional rather than manufacturing precision. Operational systems may overwrite status, integrations may lag, and small denominators produce volatile rates. Accurate calculation does not make a metric strategically useful or prove causation, productivity, quality, or employee performance. This is operational research, not accounting, audit, statistical, employment, or investment advice.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'september-28-research-social-asset-rights-provenance',
    title: 'Social Asset Rights Provenance: Test the Record Before Scheduling Content',
    excerpt: 'Evaluate whether each image, clip, quotation, and testimonial reaches scheduling with attributable source and approval evidence.',
    serviceHandoff: { href: '/services/social-content-administration', label: 'Scope a reviewable social-content lane', description: 'Maintain asset provenance, approval queues, and publication records while rights, claims, offers, testimonials, and sensitive replies remain with the business.' },
    referenceSources: [sources.copyright, sources.ftcAds, sources.ftcSecurity, sources.sba],
    body: [
      'Decision in view. A polished social calendar can conceal weak provenance: an image copied from search, a contractor file with unknown terms, a customer quotation without approval, music licensed only for another account, an expired stock entitlement, or a product claim detached from its source. Asset-rights provenance is the record connecting each proposed element to its origin, permitted use evidence, required attribution or disclosure, content version, approver, channel, and publication. The buyer decision is whether outsourced content administration can preserve and stop on that evidence. It is not authority to interpret ownership, grant rights, approve endorsements, substantiate claims, or decide that an exception is legally safe.',
      'Evidence and inference. The U.S. Copyright Office explains that copyright protects original works and distinguishes ownership of a copy from ownership of copyright. FTC advertising guidance states that advertising must be truthful and non-deceptive, and its broader guidance addresses endorsements and disclosures. FTC security guidance supports minimizing and protecting information, while SBA guidance supports managed business operations. These sources do not determine whether a particular asset is licensed, whether an exception applies, or whether a disclosure is adequate in context. We infer an operational control: every scheduled element should have an attributable evidence path and unresolved rights or claim questions should stop before publication.',
      'Population and provenance record. Select one brand-controlled account, campaign window, and all proposed posts, including drafts later canceled. Inventory every photograph, illustration, logo, typeface, video, audio track, screenshot, chart, quotation, testimonial, customer image, partner mark, template, generated element, and factual claim. Record asset identifier and hash, source creator or repository, acquisition date, source URL or contract reference, purchaser or contributor, license or permission evidence, account and channel scope as recorded, geographic or time limits, modification notes, attribution requirement, disclosure instruction, claim source, depicted-person approval reference, brand approver, scheduled version, publication URL, takedown or correction event, and cutoff state.',
      'Workflow and authority boundary. Use owner-created, commissioned-evidence-present, stock-license-recorded, customer-permission-recorded, partner-approved, public-domain-claimed-for-review, generated-provenance-recorded, rights-unclear, claim-source-missing, disclosure-required, owner-review, approved-for-specified-use, scheduled, published, corrected, withdrawn, and archived states. The specialist may collect evidence, link exact files, apply approved labels, compare scheduled and approved versions, and halt incomplete posts. The specialist should not assume that online availability means permission, remove a watermark, fabricate consent, broaden a license, decide fair use, rewrite a testimonial’s meaning, invent a product result, or reuse approval across channels or campaigns when the evidence does not say so.',
      'Measures and adversarial review. Report proposed posts, distinct assets and claims, records with attributable origin, records with use evidence, scope restrictions, required attributions or disclosures, incomplete items stopped, substitutions, post-approval file changes, published-version matches, corrections, withdrawals, takedown notices, and unresolved age. Sample from the schedule forward to every embedded element, then reverse-sample repository assets into the campaigns where they appeared. Compare hashes or stable versions so a filename match cannot hide a changed file. Challenge common weak points: cropped stock images, music inside edited video, screenshots containing private data, old partner logos, customer messages converted into testimonials, template elements, and files copied between accounts.',
      'Decision and limitations. Expand scheduling authority only when provenance accompanies the exact version, restrictions are understandable to the operator, required approvals occur before scheduling, substitutions reopen review, published outputs match approvals, and a takedown path has a named owner. If historic asset folders lack evidence, quarantine them from new scheduling instead of inferring permission from prior use. Licenses and platform terms can change, contributors can supply incomplete information, metadata can be stripped, and a complete administrative record can still reflect a mistaken legal conclusion. This study does not determine copyright ownership, license validity, fair use, privacy, publicity rights, endorsement compliance, or claim substantiation. It is operational research, not legal advice.',
      ...sharedResearchMethod,
    ],
  },
] as const;

export const septemberTwentyEightResearchBatch = posts.map((post) => ({
  ...post,
  published,
  imagePath: '/filipino-support-workspace.jpg',
}));
