export const septemberTwentyThreePublicationDate = '2026-09-23' as const;

type Topic = readonly [slug:string,title:string,excerpt:string,lane:string,work:string,example:string,boundary:string,service:string,metric:string];
const topics: readonly Topic[] = [
  ['outsource-dental-front-desk-tasks','How to Outsource Dental Front Desk Tasks Without Confusing Patients','A practical handoff for appointment requests, reminders, forms, and insurance-document collection while clinical and financial decisions stay in the practice.','dental front desk support','appointment requests, reminder lists, incomplete forms, referral records, and insurance-document follow-up','A patient asks whether a painful tooth needs urgent treatment while requesting the last opening today.','Clinical triage, treatment advice, fee changes, insurance-coverage promises, and release of protected records require authorized practice staff.','customer-support','complete requests with verified patient identity, correct appointment status, and documented escalation time'],
  ['outsource-property-management-tenant-inbox','How to Outsource a Property Management Tenant Inbox','Organize tenant messages, maintenance details, and follow-ups without letting an outside operator make lease, safety, or spending decisions.','property management inbox support','tenant emails, portal messages, maintenance details, vendor updates, and appointment windows','A tenant reports a water stain, then says the ceiling is sagging and asks whether the unit is safe.','Emergency response, habitability judgments, entry authorization, lease interpretation, vendor approval, and tenant remedies stay with authorized management.','customer-support','messages correctly classified, complete maintenance details, aged threads, and time to reach the named manager'],
  ['outsource-law-firm-client-intake-admin','How to Outsource Law Firm Client Intake Administration','Use a controlled intake process for contact details, conflict-check inputs, documents, and consultation scheduling without giving legal advice.','law firm intake administration','new inquiries, contact and opposing-party details, document requests, conflict-check inputs, and consultation scheduling','A caller asks whether the filing deadline has passed and whether the firm will take the case.','Legal advice, deadline calculations, conflict clearance, matter acceptance, fee commitments, and attorney-client relationship decisions remain with the firm.','admin-support','intakes with required fields, source documents linked, conflicts routed, and no unapproved statement of representation'],
  ['outsource-real-estate-transaction-coordination-admin','How to Outsource Real Estate Transaction Coordination Admin','Delegate checklist maintenance, document chasing, and calendar reminders while licensed and contractual decisions remain with the broker or agent.','real estate transaction administration','milestone checklists, signature status, inspection dates, lender updates, title requests, and closing-file organization','A buyer asks whether to waive an inspection contingency so the closing date does not move.','Contract interpretation, negotiation, disclosure advice, contingency decisions, and representations requiring a license stay with the responsible professional.','operations-support','milestones supported by source documents, overdue items surfaced, and decisions routed before the documented deadline'],
  ['outsource-hvac-dispatch-support','How to Outsource HVAC Dispatch Support for a Small Service Business','Build a dispatch-support lane for complete job intake, approved service areas, schedule updates, and technician handoffs.','HVAC dispatch support','new service requests, equipment details, service-area checks, approved availability, technician notes, and arrival updates','A caller smells gas, reports dizziness, and asks for a technician instead of emergency services.','Safety instructions, emergency classification, technical diagnosis, price exceptions, and promises outside approved availability require trained local staff.','operations-support','jobs with complete location and equipment details, correct urgency escalation, schedule accuracy, and avoided duplicate dispatches'],
  ['outsource-plumbing-call-answering-intake','How to Outsource Plumbing Call Answering and Intake','Capture complete plumbing requests and book only approved slots while urgent hazards, diagnosis, and pricing stay with the local business.','plumbing call intake','caller identity, service address, fixture or system affected, visible symptoms, access notes, and approved booking windows','A caller reports sewage backing into a finished basement and asks for a guaranteed arrival time and repair price.','Emergency guidance, diagnosis, estimates, guarantees, after-hours exceptions, and service-area overrides stay with authorized local staff.','customer-support','complete service records, correctly escalated hazards, valid bookings, and callbacks caused by missing intake fields'],
  ['outsource-construction-bid-administration','How to Outsource Construction Bid Administration Without Losing Scope Control','Organize invitations, addenda, subcontractor questions, and submission checklists while estimators retain scope and price decisions.','construction bid administration','bid invitations, plan-set versions, addenda, subcontractor requests, clarification logs, compliance forms, and submission milestones','A subcontractor price excludes a specification item, but the proposal deadline is two hours away.','Quantity takeoffs, scope interpretation, substitutions, pricing, bonding statements, contractual acceptance, and final submission approval remain with qualified staff.','admin-support','current documents acknowledged, open scope questions visible, submission items complete, and no superseded plan used'],
  ['outsource-restaurant-reservation-inbox','How to Outsource a Restaurant Reservation and Events Inbox','Handle routine reservation changes and event-information collection without making allergy, capacity, pricing, or contract promises.','restaurant reservation and events inbox support','reservation requests, approved availability, party details, accessibility requests, event inquiries, and confirmation records','A party of fourteen mentions a severe allergy and asks for a private room at the standard menu price.','Food-safety assurances, allergy accommodation decisions, capacity exceptions, deposits, event pricing, and contract terms stay with restaurant management.','customer-support','requests matched to approved availability, special requirements surfaced, accurate confirmations, and manager response time'],
  ['outsource-insurance-agency-renewal-prep','How to Outsource Insurance Agency Renewal Preparation','Prepare renewal files and missing-information follow-up without allowing unlicensed staff to recommend coverage or bind a policy.','insurance renewal preparation','renewal dates, carrier notices, exposure questionnaires, missing documents, contact attempts, and licensed-agent review queues','A client reports a new location and asks whether the current policy automatically covers it.','Coverage interpretation, recommendations, quotes presented as advice, policy changes, binding, and regulatory communications stay with licensed personnel.','admin-support','renewals opened on time, required information present, changes routed, and licensed review completed before the carrier deadline'],
  ['outsource-accounting-firm-client-document-chase','How to Outsource Client Document Follow-Up for an Accounting Firm','Create a respectful document-chase routine with secure links, precise missing-item lists, and accountant-owned tax or accounting judgments.','accounting firm document follow-up','client request lists, secure upload status, missing periods, unreadable files, reminder history, and reviewer questions','A client uploads a spreadsheet of expenses and asks which items are deductible before sending receipts.','Tax advice, accounting classification, filing positions, materiality decisions, deadline exceptions, and acceptance of incomplete evidence remain with qualified firm staff.','admin-support','requested items received through approved channels, files matched to the right client and period, and technical questions routed'],
  ['outsource-nonprofit-donor-database-cleanup','How to Outsource Nonprofit Donor Database Cleanup','Improve donor records with reversible updates, source evidence, and privacy controls while gift, relationship, and tax decisions remain internal.','nonprofit donor database cleanup','duplicate candidates, returned mail, contact preferences, gift-source records, campaign codes, and acknowledgment status','Two household members share an address and surname, but each has separate giving history and communication preferences.','Record merges, gift adjustments, tax-receipt decisions, sensitive constituent handling, suppression overrides, and relationship strategy require authorized staff.','reporting-and-qa','proposed duplicates reviewed, corrections tied to evidence, preferences preserved, and records recoverable from an audit log'],
  ['outsource-medical-practice-referral-coordination-admin','How to Outsource Medical Practice Referral Coordination Admin','Track referral documents, status, and scheduling handoffs while clinical urgency and protected-information decisions stay with the practice.','medical referral coordination administration','referral orders, required records, receiving-office status, patient contact attempts, appointment confirmation, and closed-loop notes','A referral marked routine includes a note describing new weakness, and the receiving office has no appointment for six weeks.','Clinical triage, urgency changes, medical advice, authorization interpretation, and disclosure beyond approved workflows remain with authorized healthcare staff.','operations-support','referrals with complete approved records, status checked on schedule, clinical concerns escalated, and completion documented'],
];

export const septemberTwentyThreeSources = [
  ['U.S. Small Business Administration guide to managing a business','https://www.sba.gov/business-guide/manage-your-business'],
  ['NIST Cybersecurity Framework 2.0','https://www.nist.gov/cyberframework'],
  ['CISA guidance on phishing-resistant MFA','https://www.cisa.gov/resources-tools/resources/implementing-phishing-resistant-mfa'],
] as const;

export const septemberTwentyThreeBlogBatch = topics.map(([slug,title,excerpt,lane,work,example,boundary,service,metric]) => ({
  slug,title,excerpt,lane,publicationDate:septemberTwentyThreePublicationDate,imagePath:'/filipino-support-workspace.jpg',sources:septemberTwentyThreeSources,service,
  sections:[
    ['Decide whether this lane is ready to outsource',`Start with the work, not a job title. For ${lane}, list the items that arrived during the last two normal weeks: ${work}. Mark the source of each item, the action taken, the person who approved an exception, and the evidence that showed completion. This sample reveals whether the lane repeats often enough to teach and whether its finish line is observable. Do not outsource a queue whose rules live only in one person's memory. First separate routine preparation from professional judgment, safety decisions, money movement, and commitments to customers. Write a one-sentence outcome that a reviewer can test. Then list eligible items, excluded items, normal service hours, and the person accountable for the result. This turns “help with ${lane}” into a bounded operating process. It also gives a provider enough detail to estimate staffing without pretending that every arrival takes the same effort.`],
    ['Map the intake before discussing staffing',`Create one intake record with an identifier, received time, requester, source link, relevant dates, required fields, current status, next action, and owner. Use statuses that explain what is happening: ready, working, waiting for requester, waiting for internal decision, scheduled, completed, or closed with a reason. Avoid a broad “in progress” status that hides delay. For this lane, the record should cover ${work}. Use a representative sample containing ordinary requests, missing information, duplicate messages, a change after submission, and at least one consequential exception. Measure active handling time separately from waiting time. A five-minute update may remain open for days while an authorized person decides. That difference affects coverage, service levels, and price. Before granting access, ask a candidate to process redacted samples and show what they would record, what they would return as incomplete, and what they would escalate.`],
    ['Set the authority boundary in verbs',`Define what the operator may view, create, edit, send, schedule, export, approve, merge, close, and delete. Pair each permitted verb with the required evidence and identify actions that always need review. ${boundary} A policy that merely says “ask when unsure” is not enough. Give the operator named stop conditions, a primary escalation contact, a backup, and the safe action while waiting. Use named accounts, multifactor authentication where supported, and only the folders, fields, and systems needed for the lane. NIST Cybersecurity Framework 2.0 offers a useful governance structure, and CISA explains stronger MFA options, but neither replaces a business-specific access decision. Test access removal before launch. Never put credentials in the SOP, work queue, or chat transcript.`],
    ['Work through a realistic exception',`Use this scenario during training: ${example} The operator should preserve the caller's or requester's wording, record the time and available source, avoid inventing an answer, and route the item through the written exception path. The business should decide in advance whether the operator may acknowledge receipt, which neutral language is approved, and when a live transfer or local response is required. Review the scenario from two angles. First, could delay create customer, safety, financial, privacy, or deadline risk? Second, would the proposed response exceed the operator's training or authority? A good escalation contains the identifier, verified facts, missing facts, attempted actions, requested decision, and supported due time. It does not bury the decision inside a long chat log. Store the final decision with the item so it becomes a future example only after an authorized reviewer approves it.`],
    ['Build the SOP from examples',`Write the shortest instruction that another trained person can follow. Start with the trigger, eligible inputs, required sources, step order, approved templates, quality checks, stop rules, escalation contacts, and completion evidence. Add three annotated examples: one ordinary item, one incomplete item, and one exception. For ${lane}, include screenshots or field names only when they are stable and do not expose real customer data. State which system is the source of truth when email, a portal, and a spreadsheet disagree. Preserve the conflict instead of silently selecting the convenient value. Give the SOP an owner, version, effective date, and review date. Operators may propose clarifications, but changes to authority, policy, or customer commitments require owner approval. Retire old versions so a backup worker cannot accidentally follow a superseded rule.`],
    ['Run a paid and reversible pilot',`Use a pilot with a start date, end date, eligible volume, working hours, accounts, reviewer, daily handoff, stop conditions, and acceptance rules. Begin with preparation or draft mode when an error could affect a customer, a protected record, money, safety, or a legal commitment. Review every consequential item and a random sample of routine work against the original source. Keep returned work in the record; deleting it makes the pilot look cleaner while hiding training needs. Limit volume until the operator can demonstrate the boundary as reliably as the routine steps. If a material error occurs, contain the affected item, correct the customer or system record through an authorized person, preserve what happened, and update the instruction or access. Expand only when another trained reviewer can reproduce why items passed, stopped, or escalated.`],
    ['Score quality without rewarding shortcuts',`Track ${metric}. Add received volume, completed volume, aging, returned work, clarification requests, repeated exceptions, and owner review minutes. Every percentage needs a denominator. Separate ordinary work from high-consequence exceptions, because combining them can hide the very cases that test the process. Do not reward closure speed if the operator can close an item with missing evidence. Sample completed items directly from the source system and compare the record, action, and timestamp. Count setup, training, tools, correction, management time, and coverage gaps alongside the provider fee. If no credible baseline exists, report the pilot period plainly rather than claiming savings. Agree before launch what evidence supports a go, revise, or stop decision. That prevents enthusiasm or frustration from changing the test after results arrive.`],
    ['Design the daily handoff and backup path',`At the beginning of each shift, review new arrivals, aging items, promised dates, failed contacts, and decisions returned by the business. During the shift, keep the source link and status current instead of reconstructing work at day end. Finish with a short handoff: completed items, exceptions, near-deadline items, failed system access, and the exact decisions needed from named people. The owner should answer in the shared record so the reasoning is available to reviewers and backup staff. Test backup coverage using a non-sensitive sample. The backup should be able to locate the live SOP, queue, approved language, source systems, and escalation contacts without borrowing another person's account. Weekly, sample quality and review recurring questions. Monthly, reassess permissions, volume, service windows, and whether the lane still creates useful owner capacity.`],
    ['Choose go, revise, or stop',`Choose go when outputs are usable, sources support the record, authority stayed within bounds, exceptions reached the right person, and management effort fits the benefit. Choose revise when the lane is valuable but needs a clearer field, example, schedule, permission, reviewer, or staffing assumption. Choose stop when the work depends on undocumented judgment, access cannot be limited, records cannot be reconstructed, or the provider repeatedly crosses consequential boundaries. Document who owns every open item and how access and data will be returned if the pilot ends. Before signing a longer arrangement, confirm fees, minimums, service windows, confidentiality, account ownership, work-product terms, incident notice, subcontracting, data return, and termination help in the actual agreement. For a next step, compare this plan with the on-site ${service.replaceAll('-',' ')} service guide and bring a small redacted sample to a scoping conversation.`],
  ] as const,
}));

export type SeptemberTwentyThreeBlogPost = (typeof septemberTwentyThreeBlogBatch)[number];
