import { buildSeptemberTwentyFiveSections } from './sep25-blog-originality';

export const septemberTwentyFivePublicationDate = '2026-09-25' as const;

type Topic = readonly [slug:string,title:string,excerpt:string,lane:string,work:string,example:string,boundary:string,service:string,metric:string];
const topics: readonly Topic[] = [
  ['outsource-dental-insurance-verification-admin','How to Outsource Dental Insurance Verification Administration','Build a documented verification lane for plan facts and missing information while treatment, coverage interpretation, and patient estimates stay with authorized practice staff.','dental insurance verification administration','patient identifiers, payer portal results, effective dates, benefit fields, frequency limits, missing information, and verification timestamps','A payer portal shows an annual maximum but gives an ambiguous response about a planned procedure, and the patient asks whether the treatment is fully covered.','Treatment advice, benefit interpretation, patient financial promises, coding decisions, appeals, and collection exceptions remain with authorized dental staff.','administrative-support','verifications tied to payer evidence, missing fields surfaced, timestamps recorded, and questions routed before the appointment'],
  ['outsource-property-maintenance-request-intake','How to Outsource Property Maintenance Request Intake','Organize tenant reports, access details, photos, and vendor routing without letting an intake specialist diagnose hazards or authorize unplanned work.','property maintenance request intake','property and unit, reporter contact, issue description, photos, access permission, approved priority rules, vendor status, and completion evidence','A tenant reports a ceiling stain near a light fixture, says it is getting larger, and asks whether the apartment is safe to occupy overnight.','Emergency and habitability decisions, technical diagnosis, vendor selection exceptions, spending approval, lease interpretation, and resident remedies remain with authorized property staff.','customer-inbox-management','requests with complete location and access facts, safety language escalated, vendor handoffs acknowledged, and closures supported by evidence'],
  ['outsource-freight-proof-of-delivery-follow-up','How to Outsource Freight Proof-of-Delivery Follow-Up','Track shipment evidence and missing delivery records while claims, liability, carrier selection, and customer remedies stay with logistics leaders.','freight proof-of-delivery follow-up','shipment identifiers, carrier references, scheduled dates, delivery status, proof-of-delivery files, exceptions, and customer update history','A carrier marks a shipment delivered, the consignee denies receipt, and the document appears to contain an unfamiliar signature.','Loss determinations, claims, liability statements, carrier disputes, customer credits, and fraud allegations remain with authorized logistics staff.','supplier-coordination','shipments matched to evidence, missing documents chased, discrepancies preserved, and disputed deliveries escalated promptly'],
  ['outsource-subscription-billing-dispute-intake','How to Outsource Subscription Billing Dispute Intake','Capture billing questions and account evidence without allowing a support queue to decide refunds, fraud, contract meaning, or payment liability.','subscription billing dispute intake','verified account, invoice and transaction references, plan history, cancellation records, customer wording, prior contacts, and requested resolution','A customer says a renewal was unauthorized, threatens a chargeback, and asks the operator to delete the account and refund a different card.','Refunds, fraud findings, chargeback responses, contract interpretation, payment-method changes, data deletion approval, and legal statements remain with authorized staff.','customer-support','disputes linked to source records, identity checks completed, requested outcomes captured, and consequential decisions routed'],
  ['outsource-insurance-renewal-packet-preparation','How to Outsource Insurance Renewal Packet Preparation Without Giving Coverage Advice','Prepare complete renewal records and follow-ups while licensed staff retain recommendations, representations, binding authority, and carrier negotiations.','insurance renewal packet preparation','approved client checklist, policy identifiers, exposure updates, loss-run status, signed forms, carrier deadlines, and licensed-review questions','A client reports a new operation shortly before renewal and asks whether the current policy automatically covers it.','Coverage advice, risk interpretation, carrier representations, premium promises, application changes, binding, and placement decisions stay with licensed personnel.','administrative-support','packets complete against the approved checklist, source dates visible, missing facts followed up, and licensed questions separated'],
  ['outsource-contractor-certificate-tracking','How to Outsource Contractor Certificate Tracking','Track requested insurance evidence, dates, and review queues while qualified staff retain coverage interpretation, acceptance, waivers, and vendor eligibility decisions.','contractor certificate tracking','contractor identity, project or site, requested certificate fields, received document, policy dates, holder details, review status, and renewal reminders','A contractor sends a certificate with an expired policy date and asks the coordinator to mark it accepted so site access is not delayed.','Coverage interpretation, sufficiency decisions, waivers, endorsements, contract compliance, site eligibility, and risk acceptance remain with authorized staff or advisers.','administrative-support','documents matched to contractors, dates captured from source evidence, gaps routed before access, and acceptance supported by named review'],
  ['outsource-construction-change-order-log-admin','How to Outsource Construction Change-Order Log Administration','Keep requests, quotations, approvals, and status evidence aligned while scope, entitlement, safety, and commercial decisions stay with project leaders.','construction change-order log administration','request identifiers, drawing references, submitted quotations, review status, approval evidence, schedule notes, and linked correspondence','A subcontractor begins extra work after a verbal conversation and asks the coordinator to mark the price and time extension approved.','Scope direction, contractual entitlement, price acceptance, schedule relief, safety decisions, and authorization to proceed remain with designated project leaders.','operations-support','requests linked to source documents, approval status accurate, aging decisions visible, and no unsupported authorization recorded'],
  ['outsource-hvac-maintenance-agreement-admin','How to Outsource HVAC Maintenance Agreement Administration','Coordinate approved service plans, reminders, asset records, and visit windows while technicians and managers retain diagnosis, safety, pricing, and contract exceptions.','HVAC maintenance agreement administration','customer and site records, covered equipment, approved visit cadence, reminder history, access notes, technician status, and renewal dates','A customer reports a gas smell during a maintenance reminder call and asks whether the system can remain running until tomorrow.','Emergency direction, technical diagnosis, equipment safety, scope changes, pricing exceptions, warranty decisions, and contract interpretation stay with local authorized staff.','local-service-scheduling','visits scheduled against approved plans, asset details complete, urgent wording escalated, and renewals routed before expiration'],
  ['outsource-wholesale-order-entry-admin','How to Outsource Wholesale Order Entry Without Losing Commercial Control','Turn approved customer orders into accurate records while credit, substitutions, pricing, allocation, and acceptance decisions remain internal.','wholesale order entry administration','customer account, purchase order, item and quantity, approved price list, requested date, ship-to details, tax status, and exception flags','A customer submits an expired price, requests more stock than is available, and asks for a substitute item on the same terms.','Credit decisions, price overrides, substitutions, inventory allocation, tax treatment, contract acceptance, and shipment promises remain with authorized staff.','ecommerce-order-support','orders matched to purchase orders, fields validated, exceptions held for review, and corrections traced to source evidence'],
  ['outsource-hotel-group-booking-inquiry-admin','How to Outsource Hotel Group Booking Inquiry Administration','Qualify group requests and coordinate approved next steps without allowing intake staff to promise inventory, rates, concessions, or contract terms.','hotel group booking inquiry administration','event dates, room pattern, guest count, meeting space, food and beverage needs, accessibility requests, decision timeline, and contact history','A planner wants a large room block during a busy period, free upgrades, and a verbal guarantee while delaying the deposit.','Inventory commitment, pricing, concessions, accessibility commitments, deposit exceptions, contract terms, and event feasibility remain with authorized hotel staff.','lead-intake-administration','inquiries with complete patterns and requirements, viable dates routed, exceptions highlighted, and no unapproved hold or rate promise'],
  ['outsource-security-questionnaire-coordination','How to Outsource Security Questionnaire Coordination Without Inventing Controls','Coordinate evidence requests and approved answers while security owners retain risk acceptance, control claims, incident disclosure, and contractual commitments.','security questionnaire coordination','requesting customer, questionnaire version, due date, question owner, approved answer library, evidence link, review status, and submission record','A prospect asks whether the company is fully compliant with a framework and requests an absolute guarantee that no breach has occurred.','Compliance claims, risk acceptance, incident disclosure, legal interpretation, contract commitments, and unsupported control statements remain with authorized security and legal owners.','reporting-and-qa','questions assigned to accountable owners, approved answers reused with version checks, evidence linked, and unsupported claims blocked'],
  ['outsource-medical-billing-denial-document-prep','How to Outsource Medical Billing Denial Documentation Preparation','Assemble denial records and approved supporting documents while coding, clinical interpretation, appeals strategy, and patient advice stay with authorized specialists.','medical billing denial documentation preparation','claim identifier, payer response, denial code, submission history, approved document checklist, missing records, deadline source, and reviewer queue','A denial cites medical necessity and the patient asks the coordinator to change the diagnosis so the claim will be paid.','Coding changes, clinical interpretation, record alteration, appeal arguments, deadline conclusions, payer representations, and patient financial advice remain with authorized staff.','administrative-support','denials matched to payer evidence, document packets complete, missing records surfaced, and prohibited changes escalated'],
];

export const septemberTwentyFiveSources = [
  ['U.S. Small Business Administration guide to managing a business','https://www.sba.gov/business-guide/manage-your-business'],
  ['NIST Cybersecurity Framework 2.0','https://www.nist.gov/cyberframework'],
  ['CISA guidance on phishing-resistant MFA','https://www.cisa.gov/resources-tools/resources/implementing-phishing-resistant-mfa'],
] as const;

export const septemberTwentyFiveBlogBatch = topics.map(([slug,title,excerpt,lane,work,example,boundary,service,metric],index) => ({
  slug,title,excerpt,lane,publicationDate:septemberTwentyFivePublicationDate,imagePath:'/filipino-support-workspace.jpg',sources:septemberTwentyFiveSources,service,
  sections:buildSeptemberTwentyFiveSections(slug,lane,index),
}));

export type SeptemberTwentyFiveBlogPost = (typeof septemberTwentyFiveBlogBatch)[number];
