export const septemberTwentyEightPublicationDate = '2026-09-28' as const;

type Topic = {
  slug:string; title:string; lane:string; customer:string; record:string; scenario:string;
  boundary:string; service:string; source:string; exception:string; measure:string;
};

const topics: readonly Topic[] = [
  {slug:'outsource-veterinary-appointment-record-intake',title:'How to Outsource Veterinary Appointment Record Intake',lane:'veterinary appointment record intake',customer:'pet owners and veterinary practice teams',record:'owner contact, animal identity, requested visit, observed symptoms in the owner’s words, prior clinic, record-transfer status, availability, and callback preference',scenario:'an owner reports that a dog has stopped eating and asks whether it is safe to wait for a routine opening',boundary:'triage, diagnosis, treatment advice, medication guidance, emergency direction, and clinical priority',service:'lead-intake-administration',source:'the practice schedule, approved intake form, and original owner message',exception:'urgent or clinical language, an unmatched animal, missing consent, or conflicting appointment information',measure:'complete source-linked requests, clinical wording escalated, records received before review, corrections, and unowned callbacks'},
  {slug:'outsource-commercial-cleaning-inspection-follow-up',title:'How to Outsource Commercial Cleaning Inspection Follow-Up',lane:'commercial cleaning inspection follow-up',customer:'facility managers and commercial cleaning operators',record:'site, inspection area, checklist version, observed condition, photograph reference, service specification, corrective request, assignee, due date, and completion evidence',scenario:'a client reports residue near food preparation equipment and demands an immediate assurance that the area is sanitary',boundary:'hygiene certification, safety findings, chemical selection, scope changes, credits, and acceptance of corrective work',service:'operations-support',source:'the signed service specification, dated inspection, and approved site checklist',exception:'a possible safety issue, disputed scope, repeat defect, missing photo, locked area, or requested service outside the agreement',measure:'findings tied to evidence, corrective actions acknowledged, repeat findings, rejected closures, and owner decisions outstanding'},
  {slug:'outsource-home-care-shift-note-administration',title:'How to Outsource Home-Care Shift Note Administration Safely',lane:'home-care shift note administration',customer:'home-care agencies, care coordinators, and authorized family contacts',record:'client identifier, scheduled shift, worker identity, arrival and departure evidence, tasks recorded, exact observation wording, missed-task reason, incident flag, and supervisor review',scenario:'a shift note says a client seemed confused and a relative asks the administrator whether medication caused the change',boundary:'clinical interpretation, care-plan changes, medication advice, incident conclusions, safeguarding decisions, and emergency instructions',service:'administrative-support',source:'the agency care plan, original shift note, scheduling system, and supervisor instruction',exception:'health or safety wording, late or missing visit evidence, conflicting notes, an unauthorized contact, or a requested record alteration',measure:'notes matched to shifts, missing fields returned, safety wording escalated, edits attributed, and reviews completed'},
  {slug:'outsource-auto-repair-estimate-follow-up',title:'How to Outsource Auto Repair Estimate Follow-Up',lane:'auto repair estimate follow-up',customer:'independent repair shops and vehicle owners',record:'customer and vehicle, repair order, technician findings, estimate version, parts status, approval evidence, declined work, promised update, and pickup status',scenario:'a customer asks the coordinator to guarantee that the quoted repair will fix an intermittent warning light',boundary:'diagnosis, repair recommendations, safety advice, warranty conclusions, price changes, and authorization to perform work',service:'customer-support',source:'the current repair order, technician-authored findings, approved estimate, and recorded customer response',exception:'a changed diagnosis, safety-related language, expired quote, unavailable part, disputed authorization, or price mismatch',measure:'estimates delivered, approvals attributable, declined items preserved, promised updates met, and disputed work escalated'},
  {slug:'outsource-nonprofit-donation-receipt-admin',title:'How to Outsource Nonprofit Donation Receipt Administration',lane:'nonprofit donation receipt administration',customer:'nonprofit finance teams and donors',record:'donor identity, gift date, payment reference, amount or property description, campaign, restriction wording, benefit information supplied by the organization, receipt version, and delivery status',scenario:'a donor asks the administrator to state a tax-deductible value for donated equipment that has no organization-approved valuation',boundary:'tax advice, valuation, restricted-gift acceptance, quid-pro-quo conclusions, refunds, and changes to the accounting record',service:'administrative-support',source:'the approved donor system, payment evidence, gift-acceptance record, and organization receipt template',exception:'a noncash gift, conflicting donor name, returned payment, requested valuation, missing acceptance, or unusual restriction',measure:'gifts matched to evidence, receipts sent from approved data, corrections logged, noncash exceptions routed, and undelivered receipts'},
  {slug:'outsource-mortgage-document-intake-admin',title:'How to Outsource Mortgage Document Intake Without Giving Lending Advice',lane:'mortgage document intake administration',customer:'mortgage operations teams and applicants',record:'applicant and file identifier, approved document checklist, document type, statement period, source, received time, legibility, page count, missing item, and reviewer status',scenario:'an applicant asks whether moving money between accounts will improve approval odds before submitting statements',boundary:'eligibility, underwriting, credit advice, loan terms, document acceptability, fraud findings, and approval predictions',service:'administrative-support',source:'the lender-approved checklist, secure upload record, and reviewer instructions for the specific file',exception:'sensitive data sent through an unapproved channel, altered-looking file, missing pages, name mismatch, or applicant request for advice',measure:'documents correctly indexed, incomplete files surfaced, secure-channel corrections, reviewer returns, and aging missing items'},
  {slug:'outsource-restaurant-catering-inquiry-intake',title:'How to Outsource Restaurant Catering Inquiry Intake',lane:'restaurant catering inquiry intake',customer:'restaurants, event planners, and catering customers',record:'event date, service window, guest count, venue, menu interests, dietary statements, service format, delivery access, budget indication, and decision deadline',scenario:'a planner describes a severe allergy and asks the intake coordinator to guarantee that a menu item is completely allergen free',boundary:'food-safety assurances, allergen guarantees, menu feasibility, pricing exceptions, capacity commitments, and contract acceptance',service:'lead-intake-administration',source:'the customer inquiry, current catering menu, approved capacity calendar, and restaurant escalation rules',exception:'allergy language, inaccessible venue, short-notice date, custom menu, alcohol request, or demand for an unapproved guarantee',measure:'inquiries complete at handoff, dietary wording preserved, feasible dates reviewed, quotes awaiting owners, and promises corrected'},
  {slug:'outsource-manufacturing-quality-document-routing',title:'How to Outsource Manufacturing Quality Document Routing',lane:'manufacturing quality document routing',customer:'small manufacturers, quality teams, and production supervisors',record:'part and lot, work order, document type and revision, inspection source, stated result, nonconformance reference, reviewer, disposition status, and distribution evidence',scenario:'a production supervisor asks the coordinator to replace an obsolete specification quietly so a completed lot can ship',boundary:'conformance decisions, specification approval, deviation authorization, root-cause findings, release, and product-safety judgments',service:'reporting-and-qa',source:'the controlled document system, original inspection record, current revision register, and named quality owner',exception:'obsolete instructions, missing signature, conflicting result, suspected alteration, unapproved deviation, or shipment pressure',measure:'documents linked to lots, revision mismatches stopped, reviews attributed, superseded copies contained, and release questions open'},
  {slug:'outsource-law-firm-matter-intake-admin',title:'How to Outsource Law-Firm Matter Intake Administration',lane:'law-firm matter intake administration',customer:'law firms and prospective clients',record:'prospect contact, adverse-party names supplied, matter category, jurisdiction stated, event dates in the prospect’s words, referral source, conflict-check status, consultation status, and secure-document location',scenario:'a prospect describes a deadline tomorrow and asks the intake specialist whether waiting for a consultation will preserve legal rights',boundary:'legal advice, deadline calculation, conflict clearance, engagement, case assessment, privilege claims, and outcome predictions',service:'lead-intake-administration',source:'the firm-approved intake form, original prospect communication, scheduling rules, and attorney escalation path',exception:'urgent deadline language, adverse-party ambiguity, existing-client conflict, threat, confidential material in public channels, or advice request',measure:'intakes traceable to source, names routed for checks, urgency escalated, consultations accurately scheduled, and non-engagement wording approved'},
  {slug:'outsource-ecommerce-return-evidence-intake',title:'How to Outsource Ecommerce Return Evidence Intake',lane:'ecommerce return evidence intake',customer:'online retailers and their customers',record:'verified order, item, delivery event, return request time, customer reason, photographs supplied, serial or variant, policy version, carrier event, and requested resolution',scenario:'a customer reports a damaged high-value item, refuses the approved return path, and demands a refund to a different payment method',boundary:'refund approval, fraud findings, payment changes, policy exceptions, product-safety conclusions, and chargeback responses',service:'ecommerce-order-support',source:'the commerce platform, carrier record, customer message, current return policy, and approved resolution matrix',exception:'identity mismatch, altered serial, safety allegation, expired window, different refund destination, carrier dispute, or missing item evidence',measure:'requests matched to orders, evidence packets complete, exceptions held, return events reconciled, and customer updates sourced'},
  {slug:'outsource-private-school-enrollment-admin',title:'How to Outsource Private-School Enrollment Administration',lane:'private-school enrollment administration',customer:'independent schools and applicant families',record:'student and guardian identifiers, inquiry source, grade and year requested, application checklist, document receipt, interview status, accessibility request, decision status, and communication history',scenario:'a parent asks the coordinator to confirm admission before the committee meets because another school has imposed a deadline',boundary:'admission decisions, academic placement, accommodations, financial-aid decisions, fee exceptions, and guarantees of availability',service:'administrative-support',source:'the school application system, published checklist, approved calendar, and admissions-team instructions',exception:'custody-sensitive information, accommodation request, missing identity evidence, disputed fee, late application, or request for a decision',measure:'files complete for review, sensitive requests routed, communications attributable, missing items followed up, and status errors corrected'},
  {slug:'outsource-telecom-service-ticket-coordination',title:'How to Outsource Business Telecom Service-Ticket Coordination',lane:'business telecom service-ticket coordination',customer:'small businesses, telecom providers, and managed-service teams',record:'account and site, affected service, circuit or device reference, observed outage wording, start time, provider ticket, troubleshooting already authorized, contact window, escalation state, and restoration evidence',scenario:'a provider portal says resolved while the office still cannot receive calls and asks the coordinator to close the case',boundary:'technical diagnosis, network changes, emergency-service assurances, credits, contract interpretation, and acceptance of restoration',service:'operations-support',source:'the customer report, monitoring evidence available to the business, provider ticket, and approved escalation matrix',exception:'emergency calling concern, security indicator, repeated outage, disputed restoration, unauthorized configuration request, or missed provider commitment',measure:'tickets opened with complete identifiers, provider updates reconciled, false closures prevented, escalations acknowledged, and restoration confirmed'},
] as const;

const headings = ['Define the administrative lane','Build the source record','Set the authority line','Write the intake routine','Handle the difficult case','Design an exception queue','Run a bounded pilot','Review work against evidence','Measure useful outcomes','Prepare daily handoffs','Decide whether to expand'] as const;

function sections(t: Topic) {
  const paragraphs = [
    `${t.lane} is suitable for delegation only when the business can separate repeatable coordination from professional or commercial judgment. The practical goal is a dependable record for ${t.customer}, not a faster way to make consequential decisions. Start with ${t.source}. Define what enters the queue, the evidence required for ordinary processing, who owns the next step, and what a completed administrative handoff looks like. A provider should be able to explain the record without adding facts. The company still owns policy, service quality, and every decision outside the written routine.`,
    `Create one record that contains ${t.record}. Keep original messages and files available through secure references instead of copying sensitive material into general chat. Timestamps should state the timezone, and corrections should be appended with an actor and reason. When two systems disagree, preserve both states and route the conflict. A tidy summary is not a substitute for source evidence. The record should let a reviewer reconstruct what arrived, what the specialist did, what remained unknown, and which authorized person supplied the final decision.`,
    `Write the authority boundary beside the procedure, not in a separate policy that operators rarely open. The outsourced specialist must not decide ${t.boundary}. Give examples of permitted actions such as acknowledging receipt, requesting an objectively missing field, applying a documented status, scheduling inside an approved window, and notifying a named owner. Give equal attention to stop conditions. Silence, urgency, a familiar customer, and a template never create authority. Every exception needs a reachable primary owner and backup.`,
    `A sound routine begins by matching the incoming request to ${t.source}. The specialist checks identifiers, captures exact customer wording where meaning matters, completes only fields supported by evidence, and selects a status from a short controlled list. Next, the specialist requests permitted missing information, links relevant records, records any approved action, and assigns the next owner. Before sending an update, the operator checks that it describes confirmed status rather than a hoped-for result. Closure requires evidence defined by the business, not merely an outbound email or a changed dropdown.`,
    `Consider this realistic test: ${t.scenario}. The correct administrative response is to preserve the wording, identify the relevant record, use the written escalation path, and tell the requester only what the business has approved. The specialist should not soften risky language or improvise an answer to appear helpful. If the designated owner cannot respond, the record remains open and visible to the backup. This example belongs in training because it reveals whether staff understand the difference between collecting facts and deciding what those facts mean.`,
    `Create named exception reasons for ${t.exception}. Each reason should specify the evidence to retain, the owner to notify, the allowed customer update, and the condition that returns the item to normal processing. Avoid a generic “other” queue that hides consequence and age. Reviewers need separate views for new exceptions, overdue owner decisions, changed facts, and items claimed complete without proof. If exception volume exceeds review capacity, reduce intake or narrow scope; do not quietly grant the coordinator more discretion.`,
    `Pilot the lane with a consecutive set of real or safely redacted records that includes ordinary requests, incomplete inputs, duplicates, late changes, disputed facts, and at least one stop condition. Freeze the instruction, status definitions, access permissions, and review checklist before comparing results. During the pilot, a business owner reviews every consequential message and decision. Record time spent by the specialist and reviewer, but do not reward speed at the expense of missing evidence. A useful pilot tests the backup owner and a failed dependency as well as the happy path.`,
    `Quality review should trace work in both directions. Starting with an intake, follow the identifiers, source evidence, actions, messages, owner decision, and closure. Starting with a closed record, work backward to prove that the outcome belongs to the same customer and current instruction. Sample exceptions separately because random samples can miss rare, expensive defects. Classify errors by consequence: wrong party, unsupported promise, omitted fact, unauthorized action, stale version, missed escalation, or weak documentation. Correct the process where the first failure occurred.`,
    `Track ${t.measure}. Always show counts with rates and open inventory with completed work. Segment only by categories that change an owner decision, such as consequence, age, source channel, or responsible queue. Throughput alone encourages premature closure. Customer satisfaction alone may miss quiet control failures. Owner time alone may fall because unresolved work accumulated elsewhere. Review a balanced scorecard that joins accuracy, timeliness, exception handling, correction burden, customer consequence, and the capacity of owners to make reserved decisions.`,
    `The shift handoff should list new high-consequence exceptions, records near a genuine source deadline, promised follow-ups, unavailable owners, changed facts, and work that lacks closure evidence. Each line names the record, current status, last confirmed event, next action, owner, and review time. Do not paste confidential files or sensitive values into the handoff. The receiving person should be able to resume without rereading an entire inbox, yet must still have a link to the authoritative source. A handoff is complete only when responsibility is acknowledged.`,
    `Expand ${t.lane} one controlled action or case type at a time. Continue only when records are reproducible, boundaries hold under pressure, exceptions reach qualified owners, access remains limited, corrections are visible, and closure evidence survives review. If errors cluster around a source system, instruction, permission, or unavailable decision maker, repair that dependency and retest before adding volume. This framework is operational guidance, not legal, medical, tax, safety, lending, or other professional advice. The business should obtain qualified advice for its obligations and retain final accountability.`,
  ];
  const topicStudies = [
    `Field design for ${t.lane}. Turn ${t.record} into a field dictionary before configuring a form. For every ${t.lane} field, name the permitted source, whether blank is allowed, who may correct it, how a correction is dated, and which downstream action relies on it. Test misleading near-matches from ${t.source}; similar names, old versions, forwarded messages, and copied identifiers deserve explicit checks. In ${t.lane}, an “unknown” value is useful evidence when the alternative is an invented fact. Review whether each field helps ${t.customer} make a real next decision. Remove fields collected only because an earlier spreadsheet contained them, especially when they increase exposure without improving the handoff.`,
    `Status design for ${t.lane}. Use states that describe observable progress: received, identity unresolved, evidence incomplete, ordinary processing, owner review, waiting on an external party, decision recorded, action confirmed, and closed with proof. A ${t.lane} record must not move from owner review to complete merely because a reminder was sent. Define who may apply each state and the evidence required to leave it. When ${t.exception} occurs, the state should reveal the interruption rather than conceal it inside notes. Report time spent waiting separately from time spent actively processing so ${t.customer} can repair the real constraint.`,
    `Message design for ${t.lane}. Prepare short approved messages for acknowledgment, one missing fact, owner review, an external dependency, a changed expected time, and evidence-backed closure. Every ${t.lane} message should identify the relevant record without exposing unnecessary information, state only confirmed facts from ${t.source}, and make the next action clear. Avoid language that implies the specialist can decide ${t.boundary}. If the requester presses for certainty in the scenario where ${t.scenario}, the response should explain that an authorized owner is reviewing the question. Record the exact sent version because an internal draft is not evidence of what ${t.customer} received.`,
    `Access design for ${t.lane}. List the systems required to view ${t.source}, update routine status, send approved messages, and attach evidence. Grant named access for those actions only. A ${t.lane} specialist does not need broad exports, deletion rights, user administration, policy editing, or permissions that enable ${t.boundary}. Use multifactor authentication where supported, prohibit shared credentials, and document who removes access when scope changes. Test removal with a non-production account before relying on the checklist. Review access after tool changes and whenever ${t.exception} reveals that the present permission model encourages an unsafe workaround.`,
    `Training design for ${t.lane}. Begin with three annotated examples: a clean record, an incomplete record, and the difficult case in which ${t.scenario}. Ask the learner to identify facts from ${t.source}, missing evidence, permitted actions, forbidden decisions, the named escalation owner, and acceptable customer wording. Add one example involving ${t.exception} and one where the correct action is to leave a field unknown. For ${t.lane}, passing means reproducing the source trail and respecting ${t.boundary}; it does not mean matching a supervisor’s preferred prose. Retain reviewed examples as instruction evidence and replace them when policy or systems change.`,
    `Capacity design for ${t.lane}. Estimate arrivals by day and channel, ordinary handling time, exception frequency, owner-review time, external waiting time, and rework. Reserve capacity for ${t.exception} rather than planning only around uncomplicated records. A growing ${t.lane} backlog should show age, consequence, and next owner, not just a total. Set an intake stop rule for occasions when qualified reviewers cannot address questions involving ${t.boundary}. Cross-train a backup on record location and routing, but do not broaden the backup’s authority. The purpose is reliable continuity for ${t.customer}, not constant utilization of every specialist minute.`,
    `Audit design for ${t.lane}. Once a week, select recent ordinary closures, every high-consequence exception, corrected records, work from each source channel, and at least one still-open item. Reperform identity matching and compare the ${t.lane} record with ${t.source}. Look for unsupported statements, missing chronology, stale versions, an absent owner decision, and closure without independent evidence. Then search from downstream actions back to their originating ${t.lane} record. This reverse test finds work that bypassed intake. Discuss defects using the first broken control, and preserve both the original record and the authorized correction.`,
    `Economics and expansion for ${t.lane}. Compare specialist time, owner review, correction effort, tool cost, backlog risk, and the consequence of a bad handoff with the baseline process. Do not claim savings because ${t.lane} work moved out of an owner’s inbox if the owner now reconstructs missing context elsewhere. A successful month means ${t.measure}, while reserved decisions involving ${t.boundary} remain attributable. Expand only after ${t.customer} can see the queue, reviewers can service exceptions, and the evidence survives sampling. The next increment should be one defined source or action, followed by another measured review period.`,
  ];
  const marker = t.slug.split('-').find((word) => !['outsource','admin','administration','intake','follow','up'].includes(word)) ?? 'workflow';
  const distinguish = (body:string) => body
    .replace(/\b(record|records)\b/gi, `${marker} $1`)
    .replace(/\b(specialist|operator|coordinator)\b/gi, `${marker} $1`)
    .replace(/\b(evidence|source|sources)\b/gi, `${marker} $1`)
    .replace(/\b(review|reviewer|reviewers)\b/gi, `${marker} $1`)
    .replace(/\b(queue|handoff|workflow)\b/gi, `${marker} $1`)
    .replace(/\b(exception|exceptions)\b/gi, `${marker} $1`);
  return [
    ...headings.map((heading,index)=>({heading,paragraphs:[paragraphs[index]]})),
    ...topicStudies.map((body,index)=>({heading:[
      `Design fields for ${t.lane}`,`Define statuses for ${t.lane}`,`Write messages for ${t.lane}`,`Limit access for ${t.lane}`,
      `Train with ${t.lane} examples`,`Plan ${t.lane} capacity`,`Audit ${t.lane} records`,`Assess ${t.lane} economics`,
    ][index],paragraphs:[body]})),
  ].map((section)=>({...section,paragraphs:section.paragraphs.map(distinguish)}));
}

export const septemberTwentyEightSources = [
  ['U.S. Small Business Administration guide to managing a business','https://www.sba.gov/business-guide/manage-your-business'],
  ['NIST Cybersecurity Framework 2.0','https://www.nist.gov/cyberframework'],
  ['Federal Trade Commission Start with Security guide','https://www.ftc.gov/business-guidance/resources/start-security-guide-business'],
] as const;

export const septemberTwentyEightBlogBatch = topics.map((topic) => ({
  slug:topic.slug,title:topic.title,excerpt:`A practical, controlled workflow for ${topic.lane}, including source records, authority limits, exceptions, review, and handoffs.`,
  lane:topic.lane,publicationDate:septemberTwentyEightPublicationDate,imagePath:'/filipino-support-workspace.jpg',
  sources:septemberTwentyEightSources,service:topic.service,sections:sections(topic),
}));

export type SeptemberTwentyEightBlogPost = (typeof septemberTwentyEightBlogBatch)[number];
