type Profile = {
  record: string; intake: string; routine: string; trap: string; example: string;
  decision: string; pilot: string; review: string; metric: string; handoff: string;
};

const profiles: Record<string, Profile> = {
  'outsource-dental-insurance-verification-admin': {
    record:'one verification record for each patient, payer, plan, appointment, portal response, call reference, benefit period, deductible, maximum, frequency limit, waiting period, and unresolved field',
    intake:'Start from the appointment schedule and the practice-approved benefit checklist. Match the subscriber name and identifiers before opening a payer portal. Record the source and time because a benefits screen is evidence of what was returned, not a guarantee of payment.',
    routine:'The specialist can request missing subscriber details, capture portal results, save reference numbers, compare the response with the checklist, and place unclear items in the practice review queue. Use neutral patient language that says verification is still being reviewed.',
    trap:'A portal may show a percentage beside a service while hiding frequency, downgrade, alternate-benefit, waiting-period, or network conditions elsewhere. Copying the percentage into a patient estimate without qualified review turns data entry into a coverage promise.',
    example:'For a crown appointment, the record shows an annual maximum and a benefit percentage but no clear answer about replacement frequency. The specialist saves the response, marks the frequency field unresolved, and asks the designated practice reviewer. The specialist does not tell the patient that the crown is covered.',
    decision:'Clinical coding, treatment choice, benefit interpretation, estimates, appeals, write-offs, and statements about what a patient will owe belong to authorized practice staff.',
    pilot:'Pilot twenty upcoming appointments that represent different payers and appointment types. Include a terminated plan, an unreadable response, dependent coverage, coordination-of-benefits information, and a portal outage. Review every record before staff use it in a patient conversation.',
    review:'Compare each captured field with the saved portal page or call note. Check patient matching, service date, benefit period, unresolved fields, and the exact wording used in follow-up. A neat checklist still fails if it belongs to the wrong patient or old plan year.',
    metric:'Track appointments checked before the cutoff, records returned for correction, unresolved fields routed, patient matches corrected, and staff minutes spent rechecking source evidence. Do not score a verification as accurate from the eventual payment alone.',
    handoff:'The daily handoff should name tomorrow""s unverified appointments, payer systems that failed, responses awaiting practice judgment, and patients who still need to supply information. Keep protected information inside approved systems rather than copying it into general chat.'
  },
  'outsource-property-maintenance-request-intake': {
    record:'a maintenance record with property, unit, reporter, callback method, exact observed condition, when it began, photos, access permission, pets or entry constraints, prior related requests, dispatch status, and every change in condition',
    intake:'Ask what the person can see, hear, or smell, where it is occurring, whether it is changing, and how staff may enter. Preserve the resident""s own words for safety-sensitive descriptions. Do not replace """sparking outlet""" with the softer label """electrical issue."""',
    routine:'An intake specialist may acknowledge the request, collect missing location and access facts, apply the written routing table, contact an approved vendor under an existing instruction, and update the resident with confirmed status. The queue should show who owns the next action.',
    trap:'Administrative urgency labels can become unsafe when an operator improvises. A ceiling stain near a light, loss of heat, a gas odor, active flooding, or a damaged lock may require the property""s emergency path even when the resident sounds calm.',
    example:'A resident reports a growing ceiling stain beside a fixture and asks if the unit is safe overnight. The specialist records the words and time, uses the emergency escalation path, and keeps the resident available for authorized staff. The specialist does not diagnose the source or give occupancy advice.',
    decision:'Habitability decisions, emergency instructions, technical diagnosis, vendor exceptions, spending approval, lease interpretation, and resident remedies remain with property management or qualified local responders.',
    pilot:'Use recent redacted requests covering an ordinary repair, repeat complaint, no-access visit, water event, after-hours report, and vendor no-show. Run them through the proposed queue and compare routing with the manager""s actual decisions before taking live volume.',
    review:'Sample the first report and the latest status together. Confirm that access permission was not inferred, hazards were not softened, duplicate requests were linked, and closure includes what was done. A vendor appointment is not the same as a completed repair.',
    metric:'Measure complete intake at first contact, time to required escalation, no-access visits, repeat requests, vendor acknowledgment, aging by priority, and closures reopened by residents. Speed alone can reward rushed intake that omits the fact a technician needs.',
    handoff:'At shift end, list unacknowledged emergencies, residents awaiting contact, vendor arrivals not confirmed, changed conditions, and jobs near a promised window. The manager needs a decision list, not a summary that says several tickets remain open.'
  },
  'outsource-freight-proof-of-delivery-follow-up': {
    record:'a shipment evidence record joining the customer order, bill of lading or carrier reference, origin, destination, appointment, carrier status, delivery timestamp, proof-of-delivery file, signature details, shortage or damage note, and follow-up history',
    intake:'Work from the business shipment list rather than a carrier email alone. Verify that the reference, consignee, and delivery location agree before attaching evidence. Save the document as received and record where and when it was obtained.',
    routine:'The specialist may request a missing proof of delivery, log confirmed status, identify an unreadable file, ask the carrier to clarify a reference, and tell an internal owner that evidence is outstanding. Approved customer updates must distinguish carrier status from confirmed receipt.',
    trap:'"""Delivered""" is a carrier event, not an automatic finding that the customer received every item in acceptable condition. An unfamiliar signature, blank count, altered address, or late document should remain visible rather than being normalized to close the queue.',
    example:'A carrier marks a load delivered, but the consignee denies receipt and the signature is unfamiliar. The specialist preserves the carrier page and document, records the dispute without accusing anyone, and routes it to the claims owner. No credit or liability statement is offered.',
    decision:'Claims, fault, fraud allegations, carrier disputes, liability, customer credits, contract interpretation, and acceptance of substitute evidence remain with authorized logistics or commercial staff.',
    pilot:'Choose shipments across parcel, less-than-truckload, and scheduled delivery records used by the business. Include a clean delivery, missing image, shortage notation, wrong address, duplicate reference, and customer dispute. Reconcile every pilot item to its source.',
    review:'Check identifier matching before document quality. Then inspect dates, consignee, signature, exception notes, page completeness, and whether the customer""s report was kept separate from the carrier""s statement. Never overwrite one account with the other.',
    metric:'Count outstanding documents by age, documents linked to the wrong shipment, unreadable files, delivery exceptions surfaced, carrier follow-ups, customer disputes routed, and owner time spent reconstructing evidence. Avoid treating document receipt as issue resolution.',
    handoff:'The handoff should isolate shipments with deadlines, customer disputes, missing pages, carrier silence, or contradictory status. Name the next contact and evidence requested so the following shift does not restart the same search.'
  },
  'outsource-subscription-billing-dispute-intake': {
    record:'a dispute record containing the verified account, invoice and transaction references, subscription plan history, renewal notice evidence, cancellation request, payment method token reference, customer wording, previous contacts, requested outcome, and assigned decision owner',
    intake:'Verify the customer through the approved account process before discussing account-specific billing. Ask which charge is disputed and what outcome is requested. Keep """I cancelled""" as the customer""s statement until the account record has been reviewed.',
    routine:'The operator may gather source records, explain where a request sits, send approved instructions, correct non-consequential contact details under policy, and route the packet. A clean intake separates observable account events from the customer""s allegation and the company""s eventual decision.',
    trap:'A demand for an immediate refund often bundles several risky actions: deciding authorization, changing a payment destination, deleting data, cancelling service, and responding to a chargeback threat. One helpful-sounding reply can exceed several authority limits at once.',
    example:'A customer says a renewal was unauthorized and asks for a refund to a different card plus immediate account deletion. The operator captures the disputed invoice and cancellation evidence, secures the account, and routes each requested action. The operator does not promise a refund or deletion date.',
    decision:'Refunds, fraud findings, chargeback submissions, contract meaning, payment destination changes, retention exceptions, and legal statements belong to designated billing, security, or legal owners.',
    pilot:'Test redacted disputes involving a forgotten renewal, duplicate-looking charge, prior cancellation message, failed payment, account takeover concern, and refund request to a new instrument. Review both the record assembled and the language sent to the customer.',
    review:'Compare the intake with invoice history, plan events, notices, and prior messages. Check that timestamps use one timezone and that the operator did not convert an allegation into a fact. Confirm that identity verification did not expose sensitive payment data.',
    metric:'Measure disputes with complete source packets, identity exceptions, mislinked transactions, decision turnaround, reopened contacts, unsupported promises, and reviewer correction time. Closure rate is misleading if tickets are closed while a chargeback deadline still runs.',
    handoff:'List disputes awaiting an owner, security-sensitive contacts, promised response windows, chargeback-related deadlines supplied by the source, and customers who sent new evidence. Keep payment information out of spreadsheets and general messaging tools.'
  },
  'outsource-insurance-renewal-packet-preparation': {
    record:'a renewal workspace with client and policy identifiers, carrier deadline, approved exposure questionnaire, payroll or sales period, locations, vehicles or property schedule, loss-run request, signed forms, open client questions, and licensed-review status',
    intake:'Begin with the agency""s current checklist for that account and policy type. Record the period each figure covers and retain the client""s source. """Same as last year""" is not a usable value when operations, locations, ownership, or exposures may have changed.',
    routine:'An administrative specialist may send approved requests, organize received files, flag missing signatures, reconcile checklist status, and prepare a clear list for the licensed reviewer. Follow-up should ask for facts, not suggest how the client ought to answer.',
    trap:'A client may describe a new operation in ordinary language and then ask whether the present policy covers it. Treat the description as an exposure update. Turning it into a coverage answer, classification choice, or reassurance crosses from preparation into licensed judgment.',
    example:'A client adds delivery work shortly before renewal and asks if the current policy automatically applies. The specialist records when the work began, saves the client""s description, flags the question for the producer, and continues gathering the approved packet without answering it.',
    decision:'Coverage advice, application interpretation, class selection, premium estimates, market choice, representations to a carrier, binding, waivers, and recommendations remain with licensed personnel.',
    pilot:'Use a small set of upcoming renewals with different checklists. Include a missing loss run, unsigned application, changed location, new operation, stale schedule, and client question about coverage. Licensed staff should review every outgoing request and assembled packet.',
    review:'Check names, policy periods, measurement periods, version dates, signatures, and whether values trace back to the client or approved system. Do not silently copy prior-year figures. Mark conflicting figures and preserve both sources for the reviewer.',
    metric:'Track packets ready by internal cutoff, missing-item follow-ups, stale values caught, client questions routed, packets returned by licensed reviewers, and time spent locating source documents. Binding rate is not a fair measure of administrative accuracy.',
    handoff:'The handoff should show renewals by carrier deadline, the exact item still missing, last contact, newly disclosed exposure, and producer decisions needed. It should never imply that sending a packet binds or renews coverage.'
  },
  'outsource-contractor-certificate-tracking': {
    record:'a contractor compliance record with legal name, project or site, contract requirement reference, requested certificate fields, received file, policy dates, certificate holder, insurer and producer details, endorsement request status, reviewer decision, and renewal reminder',
    intake:'Request documents from the approved contractor contact and match them to the correct project. Capture what the document states without deciding whether it satisfies the contract. Keep replaced and expired files available according to the company record policy.',
    routine:'The specialist may chase missing files, name visible omissions, record dates, detect a mismatch in contractor name, and queue documents for qualified review. Statuses should distinguish requested, received, incomplete, under review, accepted by an authorized reviewer, and expired.',
    trap:'A certificate is evidence, not a contract interpretation or guarantee of coverage. Marking a document accepted because familiar limits appear on the page can conceal exclusions, endorsements, name mismatches, or requirements that the tracker is not authorized to judge.',
    example:'A contractor sends a certificate with an expired date and asks to be marked compliant so work can start. The specialist records the file, flags the date, and contacts the named reviewer. The specialist does not waive the requirement or authorize site access.',
    decision:'Sufficiency, coverage interpretation, endorsement acceptance, waivers, risk acceptance, contract compliance, and contractor eligibility remain with authorized staff or professional advisers.',
    pilot:'Process redacted examples that include a correct file, expired policy, wrong entity name, missing holder, missing endorsement, duplicate contractor, and urgent access request. The reviewer should compare every proposed status with the actual document and requirement.',
    review:'Sample the contract reference, request, received file, extracted dates, and final reviewer action as one chain. Check that the tracker did not infer acceptance and that reminders use the policy date shown on the source rather than a guessed annual cycle.',
    metric:'Measure documents matched correctly, expired records found, incomplete items routed, renewals received before cutoff, reviewer reversals, duplicate requests, and access decisions attempted without authority. Separate tracking quality from whether a contractor ultimately qualifies.',
    handoff:'List contractors near expiry, projects with no reviewed evidence, documents returned for a named reason, reviewer decisions overdue, and site access questions. Do not circulate certificate files more broadly than the work requires.'
  },
  'outsource-construction-change-order-log-admin': {
    record:'a change record linking the request number, project, contract reference, drawing or specification revision, originating instruction, scope description, quotation, schedule statement, review comments, approval evidence, status, and related correspondence',
    intake:'Log the request from its source and distinguish who raised it from who can authorize it. Preserve verbal-direction notes as unconfirmed until the designated person supplies evidence. Link revised documents instead of relying on descriptive filenames in email.',
    routine:'A project administrator may assign a number, assemble supporting documents, request missing quotation detail, update the review queue, circulate an approved status, and remind owners about aging decisions. The log must not turn an unanswered request into authorization.',
    trap:'Construction conversations move quickly, and a sentence such as """we discussed this""" can be mistaken for approval. Price, time, technical direction, and authority may come from different people. A single status field should not collapse those separate decisions.',
    example:'A subcontractor begins extra work after a site conversation and asks the administrator to mark the price and extension approved. The administrator records the claimed instruction, links the quotation, and escalates it. No approved status or direction to proceed is invented.',
    decision:'Scope direction, design judgment, entitlement, price acceptance, schedule relief, safety instructions, contractual notice conclusions, and authority to proceed remain with designated project leaders.',
    pilot:'Run recent closed examples through the proposed log, including a rejected request, partial approval, revised quotation, urgent field condition, disputed instruction, and change with separate time and cost outcomes. Compare the reconstruction with the signed record.',
    review:'Inspect source version, status, decision maker, date, price and schedule fields, and the communication sent after review. Watch for """approved""" copied from a quotation heading or meeting note when the contractual approval sits elsewhere.',
    metric:'Track requests logged within the team cutoff, missing support, days awaiting each decision owner, status corrections, superseded quotations, and work reported as started before authorization. Do not use approved value as an administrator productivity target.',
    handoff:'Call out field work reportedly underway, notice dates from source documents, reviews blocking procurement or schedule, revised submissions, and decisions promised but not recorded. The next shift should see the precise missing action and owner.'
  },
  'outsource-hvac-maintenance-agreement-admin': {
    record:'a service-plan record with customer, site, covered equipment, agreement version, visit cadence, last completed visit, approved service window, access notes, reminder preference, technician assignment, completion evidence, renewal date, and open exception',
    intake:'Match the customer request to the active agreement and equipment list before scheduling. Ask for observable symptoms in the caller""s words, but do not diagnose. Apply the company""s urgent-language route whenever the report includes a listed safety condition.',
    routine:'The coordinator may send reminders, offer approved windows, confirm access, update asset details from authorized records, attach technician completion evidence, and route renewal questions. Scheduling scripts should say what is confirmed and avoid promises about repair outcomes.',
    trap:'A maintenance reminder can become an emergency call without warning. Treating gas odor, smoke, electrical damage, or acute loss of service as an ordinary reschedule creates risk. The safest administrative action is the written escalation, not improvised technical advice.',
    example:'During a reminder call, a customer reports a gas smell and asks whether the unit can run until tomorrow. The coordinator stops the routine script and follows the company emergency path. The coordinator does not diagnose, reassure, or delay contact with authorized local help.',
    decision:'Emergency direction, equipment safety, diagnosis, repair scope, warranty interpretation, pricing, contract exceptions, and promises about system performance stay with technicians or authorized managers.',
    pilot:'Use accounts with one unit, multiple assets, expired coverage, no-access history, overdue visit, urgent symptom language, and renewal questions. Review scheduling accuracy and every customer message before allowing the specialist to manage live confirmations.',
    review:'Compare the booked visit with the agreement, asset, cadence, technician coverage, access restrictions, and customer confirmation. A completed calendar event does not prove service occurred. Require the approved technician evidence before closing the visit.',
    metric:'Measure valid appointments, wrong-asset corrections, no-access events, urgent reports escalated, overdue visits, completion evidence received, and renewal questions routed. Keep technician repair results separate from administrative performance.',
    handoff:'List urgent calls, tomorrow""s unconfirmed access, technicians missing completion records, covered assets that do not match customer descriptions, and agreements nearing renewal. Include the last verified source rather than retelling the issue from memory.'
  },
  'outsource-wholesale-order-entry-admin': {
    record:'an order record connecting the customer account, purchase order, received channel, item code, description, quantity, approved price list and effective date, requested ship date, ship-to address, tax-status source, inventory exception, review decision, and acknowledgment',
    intake:'Enter from the customer purchase order or approved electronic source, not from a salesperson""s summary alone. Match account and ship-to details, preserve the original line order, and flag any item, price, quantity, or date that does not fit the approved rules.',
    routine:'The specialist may key eligible lines, validate required fields, identify duplicates, ask for a missing purchase-order page, place exceptions on hold, and prepare an acknowledgment after approval. The order should remain reviewable against the customer source.',
    trap:'An expired price and unavailable quantity can invite a seemingly practical substitution. That changes the commercial offer. Likewise, accepting a tax statement, extending credit, or promising allocation is not routine data entry merely because the customer requested it in writing.',
    example:'A customer orders more stock than is available using an expired price and requests a substitute on the same terms. The specialist records the submitted lines, flags all three exceptions, and routes them to sales or operations. No substitute, allocation, or price is promised.',
    decision:'Credit, price overrides, substitutions, allocation, tax treatment, freight terms, contract acceptance, and shipment commitments remain with authorized commercial staff.',
    pilot:'Process redacted orders containing clean lines, obsolete item, duplicate purchase order, changed ship-to address, expired quote, unavailable quantity, and ambiguous unit of measure. Compare every entered field and held exception with the source.',
    review:'Check account, address, item, unit, quantity, price basis, requested date, and approval evidence before release. Sample edits after entry as well as first entry. A corrected order needs a traceable reason so the same error does not reappear silently.',
    metric:'Track first-pass field accuracy, duplicates stopped, exceptions held correctly, corrections by field, orders awaiting commercial review, acknowledgment timing, and customer contacts caused by missing data. Do not reward line volume at the expense of exception control.',
    handoff:'Show orders near customer deadlines, held lines, changed source documents, allocation decisions needed, duplicate concerns, and approved orders awaiting acknowledgment. Keep the customer""s original purchase order linked throughout the handoff.'
  },
  'outsource-hotel-group-booking-inquiry-admin': {
    record:'an inquiry record with organization and planner, event purpose, arrival and departure, room pattern by night, guest count, meeting-space times, food and beverage needs, accessibility requests, decision date, competing dates, contact history, and sales owner',
    intake:'Ask for the room pattern rather than only a total room count. Capture meeting needs and access requests in the planner""s words. Check whether the dates and group size fit the written routing criteria, then schedule the approved next step without implying availability.',
    routine:'An inquiry specialist may gather missing facts, send approved property information, offer authorized call times, update the sales queue, and acknowledge documents. The specialist should distinguish a request, a tentative internal note, an approved hold, and a signed booking.',
    trap:'Busy dates create pressure to """save space""" while details are still missing. A casual statement that rooms are held can become a customer commitment. Concessions, deposits, upgrades, outside vendors, accessibility arrangements, and event feasibility also need named owners.',
    example:'A planner requests a large block during a busy period, free upgrades, and a verbal guarantee while delaying the deposit. The specialist captures the pattern and concessions, flags the requested decision date, and routes the inquiry. No inventory or rate is guaranteed.',
    decision:'Inventory commitment, pricing, concessions, capacity, accessibility commitments, food and beverage exceptions, deposits, and contract terms remain with hotel sales or operations leaders.',
    pilot:'Use prior inquiries with a simple room block, complex pattern, unavailable date, meeting-space conflict, accessibility request, concession list, and stalled planner. Compare qualification records with the actions experienced sales staff actually took.',
    review:'Check nightly pattern, event spaces and times, guest count, decision deadline, contact permission, and every promise in the outgoing message. Verify that internal availability notes were not quoted as a hold and that revisions did not erase the first request.',
    metric:'Measure inquiries with complete patterns, sales acceptance, missing-fact follow-ups, incorrectly routed dates, unsupported hold or rate language, and time to the first qualified handoff. Booking revenue is not an intake-quality score.',
    handoff:'List planners awaiting a response, dates requiring inventory review, accessibility requests, revised patterns, concessions needing decisions, and follow-ups due. The sales owner should see the original request beside the qualification summary.'
  },
  'outsource-security-questionnaire-coordination': {
    record:'a questionnaire workspace with requesting customer, document version, due date and timezone, question identifier, assigned control owner, approved answer version, evidence link, confidentiality handling, reviewer, exception note, submission approval, and final copy',
    intake:'Confirm the questionnaire version and submission channel before dividing the work. Preserve each customer question exactly. Map it to an answer owner or current approved library entry, and keep unanswered items visible instead of smoothing them into a broad control claim.',
    routine:'The coordinator may assign questions, chase owners, assemble approved text, flag expired evidence, maintain version control, and prepare the reviewed file. The role is coordination. It does not create security controls or decide what the company can warrant.',
    trap:'Absolute words such as """always,""" """all,""" and """fully compliant""" can exceed the evidence even when a related process exists. Copying an old answer into a differently scoped question may also turn a once-accurate statement into a false representation.',
    example:'A prospect asks whether the company is fully compliant with a framework and wants a guarantee that no breach has occurred. The coordinator assigns the questions to security and legal owners, links current evidence, and leaves unsupported language unresolved rather than improvising.',
    decision:'Control assertions, scope, risk acceptance, compliance claims, incident disclosure, legal interpretation, contractual warranties, and submission approval remain with accountable security, privacy, or legal owners.',
    pilot:'Test a small questionnaire with repeated questions, a new control claim, expired evidence, confidential attachment, ambiguous scope, and an absolute warranty. Review every assembled answer against its approval date and evidence before any external submission.',
    review:'Compare the exact question, answer version, control owner, evidence, scope, and reviewer decision. Look for edits made in spreadsheets after approval and answers pasted into the wrong row. Keep the final submitted copy immutable and retrievable.',
    metric:'Track questions assigned, owner response time, answers returned for unsupported claims, expired evidence found, version conflicts, late scope changes, and reviewer edits. Fast completion is harmful when it rewards filling blanks with convenient language.',
    handoff:'Show open questions by owner and due time, evidence access problems, claims requiring legal review, customer clarifications, and the version awaiting approval. Do not send partial drafts through unapproved channels simply to keep the thread moving.'
  },
  'outsource-medical-billing-denial-document-prep': {
    record:'a denial packet record with patient and claim identifier, payer response, denial code and wording, service dates, submission and remittance history, approved document checklist, received records, missing records, deadline source, assigned specialist, and review status',
    intake:'Start with the payer response and claim record. Copy the denial wording accurately and note the source of any date. Match documents to the correct patient and service before assembling them, using only approved systems for protected health information.',
    routine:'An administrative specialist may retrieve authorized records, name missing pages, organize the packet, request an approved document, and place the case in the coder or appeal reviewer queue. The specialist should not rewrite clinical content to make it fit the denial.',
    trap:'A denial code can sound like an instruction to change a diagnosis, modifier, or medical-necessity statement. Administrative preparation must preserve the submitted and clinical records. Corrections require the qualified process and evidence, not a convenient edit.',
    example:'A denial cites medical necessity and the patient asks the coordinator to change the diagnosis so payment will issue. The coordinator records the request, protects the existing record, and routes the denial to authorized coding or clinical review. Nothing is altered.',
    decision:'Coding, clinical interpretation, record amendment, appeal argument, deadline conclusions, payer negotiation, patient financial advice, and write-off decisions remain with authorized specialists.',
    pilot:'Use redacted denials with duplicate claim, missing authorization, medical-necessity wording, filing-date question, absent record, corrected claim history, and patient call. Review identity matching, packet completeness, and every outgoing message.',
    review:'Check patient and claim matching first, then denial text, dates, document versions, missing-item status, and reviewer assignment. Confirm that the packet distinguishes original submission, correction, and appeal materials instead of blending them.',
    metric:'Measure packets complete on first review, patient or claim mismatches caught, missing documents identified, cases returned by specialists, source dates recorded, privacy exceptions, and preparation time. Appeal outcome depends on judgments outside administrative control.',
    handoff:'List cases by sourced deadline, documents still missing, coding or clinical decisions required, payer files not retrievable, patient contacts awaiting an authorized answer, and packets ready for review. Keep health data out of general task comments.'
  }
};

const openers = [
  'The useful starting point is a reconstructable record.', 'Begin by making the source visible.',
  'This workflow works only when another reviewer can retrace it.', 'Treat the queue as an evidence trail, not a to-do list.',
  'A clean handoff starts before the first message is sent.', 'The owner should be able to inspect the work without asking for a recap.',
  'Good administration preserves what happened and who must decide next.', 'The first design question is what the record must prove.',
  'Build the lane around evidence that survives a shift change.', 'A status is useful only when its source can be found.',
  'Start with the business record, not the provider job title.', 'The safest process makes missing facts obvious.'
];

export function buildSeptemberTwentyFiveSections(slug:string, lane:string, index:number) {
  const p=profiles[slug]; if(!p) throw new Error(`Missing originality profile for ${slug}`);
  const intro=(n:number)=>openers[(index+n*5)%openers.length];
  return [
    ['Define the working record',`${intro(0)} For ${lane}, use ${p.record}. ${p.intake} Give each item one owner, one next action, and a source that another person can inspect. Preserve conflicts instead of choosing the convenient value. Before launch, ask a manager to reconstruct two sample items without an oral explanation. Any missing context belongs in the record or the written procedure.`],
    ['Draw the authority line',`${intro(1)} ${p.routine} Write each permitted action as a verb and name the evidence required for it. ${p.decision} Give the specialist approved holding language plus a primary and backup decision owner. """Use judgment""" is not a boundary. The instruction must show exactly where routine preparation ends.`],
    ['Build intake for consequential exceptions',`${intro(2)} ${p.trap} The form should collect facts that change routing, not merely fill boxes. Keep the requester's wording when a paraphrase could change urgency or meaning. Label an unavailable fact as missing. Never guess to make a record look complete. A reviewer must be able to distinguish observed facts, reported statements, and unresolved questions.`],
    ['Test a difficult case',`${intro(3)} ${p.example} A useful escalation contains the identifier, verified facts, source links, missing facts, actions taken, precise decision requested, and a due time supported by a source. Record who decides and what evidence supported the decision. Use the case for training only after sensitive details are removed and an owner confirms the resolution.`],
    ['Make the SOP usable by a backup',`${intro(4)} Write the trigger, eligible items, exclusions, source systems, ordered actions, approved messages, stop rules, contacts, and completion evidence for ${lane}. Explain which source controls when records disagree. Add a normal example, an incomplete example, and the difficult case above. Let a trained backup run redacted samples. Revise any step that depends on private memory.`],
    ['Limit system access',`${intro(5)} List the systems and permissions used for ${lane}. Prefer named accounts, multifactor authentication where supported, and narrow access. Separate viewing, drafting, sending, exporting, deleting, and approving. NIST Cybersecurity Framework 2.0 and CISA MFA guidance are useful references, but the business must choose its permissions. Test removal and backup access. Keep credentials and sensitive records out of SOPs and general chat.`],
    ['Run a reversible pilot',`${intro(6)} ${p.pilot} State the dates, volume, hours, reviewer, acceptance rules, and stop conditions. Use preparation or draft mode where an error could affect money, safety, privacy, professional judgment, or an external promise. Keep corrections beside the original work. After a consequential error, contain the item, notify the owner, fix the source through the approved process, and update instructions or access before continuing.`],
    ['Review against source evidence',`${intro(7)} ${p.review} Sample directly from the system of record, including closures with no action. Classify defects by where they entered: intake, source choice, transcription, routing, decision, communication, or closure. This separates a coaching problem from a broken instruction, missing permission, or unavailable owner. Recheck corrected work later rather than treating one repair as proof.`],
    ['Measure the lane honestly',`${intro(8)} ${p.metric} Use counts with denominators. Separate handling time from time waiting for an authorized decision. Include review, corrections, tools, management, and coverage gaps in the operating cost. Without a credible baseline, report the pilot results plainly and do not claim savings. Set the go, revise, and stop tests before reading the results.`],
    ['Prepare a decision-ready handoff',`${intro(9)} ${p.handoff} For each open item, show the last verified event, next action, owner, supported due time, and source. Remove resolved work instead of copying stale notes forward. Test absence coverage without sharing accounts. A backup needs the current procedure, queue, approved language, access, and escalation contacts.`],
    ['Decide whether to continue',`${intro(10)} Expand ${lane} only when work traces to reliable sources, actions remain inside the boundary, and exceptions reach the right owner. Revise a useful lane when fields, examples, permissions, staffing, or review timing cause failure. Stop when essential judgment cannot be separated or records cannot be reconstructed. Before extending the arrangement, review fees, confidentiality, account ownership, incident notice, subcontracting, data return, and termination support in the actual agreement.`]
  ] as const;
}
