import { sharedResearchMethod } from './sep23-research';

const published = '2026-09-24' as const;
const checked = 'September 24, 2026';

const sources = {
  sba: { title: 'Manage your business', publisher: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business', checked },
  finance: { title: 'Manage your finances', publisher: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business/manage-your-finances', checked },
  irs: { title: 'Publication 583, Starting a Business and Keeping Records', publisher: 'Internal Revenue Service', url: 'https://www.irs.gov/publications/p583', checked },
  nist: { title: 'Cybersecurity Framework 2.0', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/cyberframework', checked },
  ftcSecurity: { title: 'Start with Security: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', checked },
  ftcAds: { title: 'Advertising and Marketing Basics', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/advertising-marketing', checked },
};

const posts = [
  {
    slug: 'september-24-research-inbox-thread-continuity',
    title: 'Inbox Thread Continuity: Test Whether a Handoff Preserves the Whole Customer Story',
    excerpt: 'Measure whether outsourced customer support keeps identity, history, promises, and unresolved questions connected across channels and shifts.',
    serviceHandoff: { href: '/services/customer-support', label: 'Design a controlled customer-support lane', description: 'Use linked conversation records and approved replies while keeping identity disputes, remedies, policy exceptions, and sensitive decisions with the business.' },
    referenceSources: [sources.sba, sources.ftcSecurity, sources.nist],
    body: [
      'Decision in view. A fast reply can be operationally wrong when it treats the newest message as the whole case. Customers may change subject lines, use a second address, reply through a form, call after emailing, or refer to a promise made in another channel. Thread continuity means that an authorized worker can connect the current contact to the correct customer, prior statements, approved commitments, unresolved questions, and next owner without guessing. The buyer decision is whether an outsourced support lane preserves that continuity. It is not authority to merge identities, expose records, invent history, or settle a disputed account.',
      'Evidence and inference. SBA guidance supports deliberate management of customer-facing operations. FTC security guidance emphasizes understanding the information a business holds, limiting access, and protecting it. NIST CSF 2.0 frames governance, identity, protection, detection, response, and recovery. These sources do not set a universal match rate or approve a particular customer-data practice. We infer a narrow control: every response should be based on an attributable conversation record whose identity, permissions, source messages, prior promises, and open issues are visible to the responder at the time of action.',
      'Cohort and observation. Select one support queue, defined channels, one product or service family, and a fixed intake window. Include new questions, reopened conversations, forwarded messages, duplicate contacts, account-access disputes, complaints, attachments, wrong-recipient events, suspected spam, and unresolved cases. Preserve the immutable message identifiers, received times, sender and recipient fields, channel, subject, quoted history, attachments status, related record candidates, verification state, approved reply source, responder, actions, escalation, and final state at cutoff. Minimize customer information in the analysis file and never copy secrets merely to make the study convenient.',
      'Continuity test. Ask a reviewer who did not handle the case to reconstruct what the customer asked, what the business had already said, which facts were verified, what remained uncertain, and which next action was authorized. A match based only on a name, display address, phone fragment, or writing style is not identity evidence. A linked CRM record is not conclusive when imports, household accounts, aliases, or duplicate records exist. The specialist may locate candidate records and summarize attributable history; ambiguous identity, account recovery, disclosure, deletion, refunds, threats, and policy exceptions must stop with the named owner.',
      'Measures and counterchecks. Report the full eligible population, conversations with complete source history, cross-channel links supported by approved identifiers, duplicates kept visible, prior promises surfaced, unresolved questions carried forward, replies based on the wrong record, owner interventions, and cases still unknown. Show counts beside rates and stratify reopened and multi-channel cases because easy single-message contacts can conceal continuity defects. Reverse-sample closed cases from the customer-visible reply back to every supporting message, then sample source messages forward to their final disposition. Treat a confident but unsupported merge as more serious than an honest hold.',
      'Decision and limitations. Expand only if authorized staff consistently reconstruct the case, avoid wrong-party disclosure, carry open questions forward, use current approved language, and stop when identity or authority is uncertain. If history is fragmented, repair the source-of-truth and channel capture before increasing reply volume. A short observation window misses rare identity conflicts, seasonal campaigns, staff turnover, and delayed reopenings. Agreement between reviewers does not prove the customer is the same person, and a correct reply does not prove satisfaction. This is operational research, not privacy, security, consumer-protection, or legal advice. The bounded conclusion concerns continuity of one customer-support handoff.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'september-24-research-bookkeeping-duplicate-evidence',
    title: 'Duplicate Bookkeeping Evidence: Test Before One Expense Becomes Two Records',
    excerpt: 'Use source identifiers, timing, amounts, and dispositions to measure duplicate risk in outsourced bookkeeping preparation.',
    serviceHandoff: { href: '/services/small-business-bookkeeping', label: 'Scope bookkeeping preparation', description: 'Build a source-linked duplicate-review queue while reserving accounting treatment, payment, filing, and close approval for qualified owners.' },
    referenceSources: [sources.irs, sources.finance, sources.nist],
    body: [
      'Decision in view. The same business event can arrive as a receipt, invoice, card-feed item, reimbursement request, emailed statement, and manually entered record. Similar-looking items can also be legitimate repeat purchases. Duplicate control is therefore not a search for matching amounts alone. It is a reviewable method for linking evidence that may describe the same event while preserving records that are merely similar. The buyer decision is whether an outsourced preparation lane can surface candidate duplicates without deleting evidence or silently deciding the accounting treatment.',
      'Evidence and inference. IRS Publication 583 explains that supporting documents and a recordkeeping system should substantiate business transactions. SBA financial guidance encourages regular review of business finances. NIST provides a general integrity and governance lens. None of these sources specifies a duplicate-detection rule for a particular ledger, payment feed, reimbursement policy, or accounting system. We infer that duplicate review needs stable source identifiers, an event history, transparent matching criteria, retained alternatives, and approval by the person responsible for the books.',
      'Population and fields. Freeze one entity, defined accounts and intake channels, one accounting period, and a cutoff. Include posted, pending, voided, refunded, reimbursed, disputed, split, recurring, manually entered, imported, and unresolved items. Retain source-system identifiers, merchant or supplier as received, document number, transaction and posting dates, amount and currency, tax or fee components, payment instrument, uploader, file hash, import batch, linked purchase or reimbursement record, current ledger identifier, proposed relationship, reason code, reviewer, and disposition. Never manufacture a missing invoice number or normalize away a meaningful difference.',
      'Candidate logic and boundary. Declare the rules before inspecting results: exact identifiers, identical file hashes, shared invoice references, amount-and-date windows, recurring patterns, refunds, partial shipments, and known batch behavior. Each rule creates a candidate, not a conclusion. The specialist may assemble evidence, label how a candidate was produced, and place it in review. The specialist should not delete a source, merge ledger entries, choose tax treatment, net a refund, release payment, or close a disputed reimbursement without the designated approver. Preserve both records and the decision trail even after a duplicate is confirmed.',
      'Measures and counterchecks. Report eligible records, candidates by rule, confirmed duplicates, legitimate repeats, linked refunds or reversals, unresolved pairs, false positives, missed duplicates found during independent review, value represented, age to disposition, and owner interventions. Counts matter more than a single percentage when a small number of high-value records changes the risk. Review a consecutive sample of non-candidates to estimate what the rules miss. Test recurring vendors and common rounded amounts separately. Reconcile every removed or suppressed posting to retained source evidence and approval; a tidy ledger is not proof that the evidence chain is complete.',
      'Decision and limitations. Expand only if the process surfaces candidates reproducibly, preserves source records, distinguishes reversals and legitimate repeats, routes judgment, and allows the owner or qualified reviewer to reconstruct every disposition. If identifiers disappear during intake, fix capture before tuning fuzzy matching. Bank feeds can lag, merchants can reuse descriptors, foreign currency can change amounts, splits can resemble duplication, and later credits can change an earlier conclusion. No candidate rule proves accounting treatment or deductibility. This is operational research, not accounting, tax, audit, or legal advice. The bounded conclusion concerns duplicate-evidence preparation.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'september-24-research-lead-intake-consent-context',
    title: 'Lead Intake Consent Context: Test What the Record Actually Supports',
    excerpt: 'Separate source, wording, purpose, channel, and owner-approved outreach rules before delegating lead follow-up.',
    serviceHandoff: { href: '/services/lead-intake-administration', label: 'Plan a reviewable lead-intake lane', description: 'Prepare attributable lead records and approved routing while keeping consent interpretation, targeting, claims, and sensitive outreach decisions with the business.' },
    referenceSources: [sources.ftcAds, sources.ftcSecurity, sources.nist],
    body: [
      'Decision in view. A lead record often contains a checkbox, campaign label, referral note, imported list name, event scan, or free-text request. None should be silently translated into unlimited permission for every channel and purpose. Consent context is the preserved evidence of what the person did or said, where and when it occurred, the wording presented, the purpose connected to the interaction, and the business rule used for routing. The buyer decision is whether outsourced lead intake can preserve and apply owner-approved context without making legal conclusions or expanding outreach on assumption.',
      'Evidence and inference. FTC advertising guidance supports truthful marketing, while FTC security guidance emphasizes limiting information collection and access to legitimate needs. NIST supplies governance and data-protection concepts. These sources do not determine whether a particular communication is permitted, and requirements differ by channel, jurisdiction, relationship, and content. We infer an operational rule: store attributable source evidence and the exact owner-approved routing rule separately from any legal or policy interpretation. Unknown or conflicting context must remain visible and stop automated expansion.',
      'Cohort and evidence. Select one acquisition path, campaign family, geography defined by the business, and intake window. Include completed and abandoned forms, direct questions, referrals, event leads, duplicate submissions, imported records, existing customers, unsubscribed contacts, test data, complaints, and unknown sources. Preserve record identifiers, landing page or source reference, capture time, wording and version shown, affirmative action as logged, requested subject, stated channel, campaign parameters, referral source, existing suppression state, transformation history, destination, owner-approved route, outreach events, and final disposition. Minimize copied personal information and restrict the analysis file.',
      'Classification and authority. Keep observed source facts, system-derived labels, owner-supplied rules, and reviewer inference in separate fields. A campaign tag is not proof of what a person saw. A referral does not establish that the referred person requested contact. An old customer relationship does not by itself describe the current request. The specialist may check required fields, locate the approved rule, deduplicate records without erasing history, and route an attributable request. Questions about permission, suppression conflicts, minors, sensitive topics, purchased lists, unusual geographies, or a change of purpose belong with the business and its advisers.',
      'Measures and counterchecks. Report the eligible population, records with attributable sources, wording versions retained, requested purposes captured, channel context present, suppression checks completed, duplicates linked, rule versions applied, ambiguous records held, owner decisions, and outreach that exceeded the supported context. Show counts, not just completion rates. Trace a sample from the final CRM record back to the original interaction and from original interactions forward to every destination. Review the rejected and held population so missing evidence cannot be hidden by measuring only routed leads. Treat unsupported certainty as a defect, not a productivity gain.',
      'Decision and limitations. Expand only when source evidence survives transformations, suppressions remain effective, approved routing is reproducible, uncertainty stops, and the owner can reconstruct why each contacted record entered the lane. If forms do not retain wording versions or imports lose provenance, repair capture first. Logs can be incomplete, people can share devices, campaign parameters can be stripped, and later requests can supersede earlier context. Operational completeness does not establish legal consent or predict lead quality. This is not privacy, advertising, telecommunications, or legal advice. The bounded conclusion concerns preservation of lead-intake context.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'september-24-research-supplier-confirmation-decay',
    title: 'Supplier Confirmation Decay: Test When an Update Stops Being Decision-Ready',
    excerpt: 'Measure the age, scope, source, and dependencies of supplier confirmations before they guide customer or purchasing decisions.',
    serviceHandoff: { href: '/services/supplier-coordination', label: 'Design a supplier-coordination lane', description: 'Maintain dated supplier evidence and follow-up queues while keeping purchases, substitutions, changed terms, disputes, and customer promises with the owner.' },
    referenceSources: [sources.sba, sources.nist, sources.ftcAds],
    body: [
      'Decision in view. A supplier statement can be genuine and still become unsafe to rely on as inventory, production, shipping, terms, or downstream commitments change. Confirmation decay is the loss of decision usefulness between a supplier update and the moment the business relies on it. It depends on scope and events, not age alone. The buyer decision is whether an outsourced coordination lane keeps confirmations connected to the exact item, quantity, location, date, terms, dependencies, and later changes. It is not authority to place orders, accept substitutions, alter terms, or promise customers that a supplier will perform.',
      'Evidence and inference. SBA guidance places supplier and operational management within running a business. NIST CSF 2.0 emphasizes governance, dependencies, risk, and current information. FTC advertising guidance supports truthful customer-facing representations. None supplies a universal freshness interval for a supplier confirmation. We infer that each business should define event-based and time-based review triggers according to consequence, then test them on its own records. A recent email may still be out of scope, while an older contractual milestone may remain the controlling evidence until changed.',
      'Population and record design. Freeze one supplier group, purchasing or service category, destination, and observation window. Include requested, quoted, ordered, acknowledged, allocated, backordered, shipped, delivered, disputed, cancelled, substituted, and unknown cases. Retain the supplier identity, source message or portal record, actor and timestamp, item or service identifier, quantity, unit, location, promised window, assumptions, price or term reference without interpreting it, dependencies, business request version, later updates, customer commitments affected, follow-up due, owner decision, and state at cutoff. Record silence as no new evidence, not confirmation.',
      'Freshness rule. Before reviewing outcomes, define triggers such as a missed milestone, changed quantity, new destination, partial allocation, substitute offer, weather or carrier event, revised customer date, material term change, or a business-set elapsed interval. A specialist may request a status against an approved record, compare the response with the request, update the evidence register, and flag a trigger. Only the owner or named manager accepts terms, chooses a substitute, changes spend, resolves a dispute, or changes a customer promise. Never transform estimated, planned, or subject-to-availability wording into confirmed.',
      'Measures and counterchecks. Report the full population, commitments with source evidence, records inside the declared scope, trigger events detected, confirmations refreshed before reliance, contradictory updates, silent suppliers, partial confirmations, downstream promises supported at the time, exceptions awaiting decisions, and owner interventions. Show confirmation age as a distribution rather than one average, and segment by consequence and dependency. Trace a sample of customer or operations decisions backward to the exact supplier evidence available then. Also trace supplier changes forward to every affected internal record so a fresh source cannot remain trapped in an inbox.',
      'Decision and limitations. Expand only when the lane preserves exact wording, detects scope and event changes, refreshes according to approved triggers, propagates updates, and stops before unapproved commitments. If the business cannot identify which customer or work records depend on a supplier statement, repair dependency mapping first. Supplier portals can lag, messages can be informal, estimated dates can move, and silence has multiple explanations. Observation cannot prove why a supplier changed or guarantee future performance. This is operational research, not procurement, contract, trade, or legal advice. The bounded conclusion concerns decision readiness of supplier confirmations.',
      ...sharedResearchMethod,
    ],
  },
  {
    slug: 'september-24-research-social-content-claim-versioning',
    title: 'Social Content Claim Versioning: Test the Statement That Actually Went Live',
    excerpt: 'Connect each public claim to its source, approved wording, asset version, channel adaptation, and published output.',
    serviceHandoff: { href: '/services/social-content-administration', label: 'Design a controlled content-operations lane', description: 'Maintain claim and approval records while keeping substantiation judgments, endorsements, pricing, sensitive replies, and final publication authority with the business.' },
    referenceSources: [sources.ftcAds, sources.ftcSecurity, sources.nist],
    body: [
      'Decision in view. A marketing claim may begin in an approved brief, change during design, shorten for a platform, appear in an image, acquire a hashtag or endorsement context, and then publish from a scheduled draft that is not the latest file. Claim versioning is the evidence chain from the statement proposed through the exact wording and visual context that became public. The buyer decision is whether outsourced content administration can preserve that chain and stop unreviewed drift. It is not permission to substantiate claims, approve endorsements, set prices, invent results, or decide that a shortened statement remains compliant.',
      'Evidence and inference. FTC advertising guidance explains that advertising claims should be truthful and not misleading, and its business resources address endorsements and related disclosures. FTC security guidance and NIST support controlled access, integrity, and governance of business information. These sources do not approve any specific claim, disclosure, testimonial, image, jurisdiction, or channel adaptation. We infer a practical control: approval must bind the claim text, evidence reference, material context, asset version, channel, and planned publication state, while later changes reopen review according to owner-defined rules.',
      'Inventory and observation. Select one campaign family, all relevant channels, and a defined planning and publication window. Include proposed, rejected, revised, approved, scheduled, published, edited, deleted, failed, and unknown posts. Preserve the content identifier, brief version, claim register entry, source title and checked date, approved wording, qualifiers, required disclosures supplied by the owner, endorsement or customer-content status, asset hash, alt text, destination link, channel transformation, approver, approval time and scope, scheduler record, public URL or platform identifier, captured live text and asset, edits, comments requiring escalation, and disposition at cutoff.',
      'Comparison protocol and boundary. Normalize only formatting differences declared irrelevant in advance; preserve punctuation, numbers, qualifiers, superlatives, dates, geographic scope, price context, and text embedded in images. Compare the approved claim with the scheduled artifact and the public result. A specialist may maintain identifiers, apply approved copy, prepare platform variants, schedule within authority, capture the live result, and hold mismatches. The specialist should not decide whether evidence substantiates a claim, rewrite a qualifier for space, approve a testimonial, answer a sensitive comment, or infer permission from an earlier campaign.',
      'Measures and counterchecks. Report the full content population, claims with current source references, approvals bound to final versions, platform adaptations reopened for review, scheduled-to-live matches, public edits, missing qualifiers or disclosures, broken destinations, unauthorized claims, held items, takedowns, and owner decisions. Inspect both text and creative because a correct caption can accompany a conflicting image. Trace a sample from public output backward to approval and evidence, then trace approved claims forward to every reuse. Count posts with no substantive claim separately; do not inflate success by mixing them with evidence-dependent promotions.',
      'Decision and limitations. Expand only when the live statement can be reconstructed, qualifiers survive channel adaptation, changed versions reopen review, uncertain evidence stops publication, and the owner can rapidly identify every use of a corrected claim. If screenshots or platform exports do not preserve live state, establish a proportionate capture method before scaling. Platforms transform links, crops, previews, and labels; later edits can alter what a reviewer sees; and evidence may expire. A complete chain does not prove a claim lawful or true. This is operational research, not advertising, endorsement, intellectual-property, privacy, or legal advice. The bounded conclusion concerns claim-version integrity.',
      ...sharedResearchMethod,
    ],
  },
] as const;

export const septemberTwentyFourResearchBatch = posts.map((post) => ({
  ...post,
  published,
  imagePath: '/filipino-support-workspace.jpg',
}));
