const published = '2026-09-23' as const;
const checked = 'September 23, 2026';

const sources = {
  sba: { title: 'Manage your business', publisher: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business', checked },
  finance: { title: 'Manage your finances', publisher: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/manage-your-business/manage-your-finances', checked },
  irs: { title: 'Publication 583, Starting a Business and Keeping Records', publisher: 'Internal Revenue Service', url: 'https://www.irs.gov/forms-pubs/about-publication-583', checked },
  nist: { title: 'Cybersecurity Framework 2.0', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/cyberframework', checked },
  ftcSecurity: { title: 'Start with Security: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/start-security-guide-business', checked },
  ftcAds: { title: 'Advertising and Marketing Basics', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/advertising-marketing', checked },
  copyright: { title: 'Copyright Basics, Circular 1', publisher: 'U.S. Copyright Office', url: 'https://www.copyright.gov/circs/circ01.pdf', checked },
};

const sharedMethod = [
  'Research method. Freeze the eligible population, observation window, cutoff, definitions, exclusions, and decision thresholds before inspecting results. Preserve original records and append corrections rather than rewriting history. Report counts beside rates, expose unresolved inventory, and distinguish an event time from the time somebody entered it. Segment only when groups use comparable definitions and contain enough observations to interpret. These safeguards reduce selection bias and false precision; they do not eliminate either. A small sample can inform one bounded operating decision, but it cannot establish a universal outsourcing benchmark or prove a causal effect.',
  'Independent review. A second reviewer should compare a declared sample with the underlying source, current instruction, system state, and authority rule. Classify defects by consequence, not cosmetic difference, and retain disagreements. Locate the first failed handoff: source capture, instruction, integration, specialist action, owner decision, or fulfillment. Correct the control at that point. Expand review after a consequential defect and reduce it only after stable results across more than one operating change. No sample demonstrates that every unsampled record is correct.',
  'Authority and access. Use named accounts, multifactor authentication where supported, minimum necessary fields and actions, and a tested removal path. Exports, deletion, credential administration, payment release, policy changes, legal positions, pricing, concessions, and unusual customer promises remain outside a routine preparation lane. A template does not authorize a specialist to invent missing facts. Conflicts, ambiguity, sensitive information, and exceptions stop in a visible queue for a named owner. Test that the backup owner can receive and act on an escalation when the primary owner is unavailable.',
  'Interpretation. Facts are what preserved records directly show. Analysis applies declared definitions to those facts. Inference describes a plausible operational meaning. Uncertainty includes missing records, alternate explanations, changing case mix, reviewer disagreement, sampling error, and later events. Keep these layers separate. Faster work is not better if consequential errors rise, and a lower error rate is not credible when difficult cases vanish from the denominator. Compare owner time, correction burden, open inventory, and customer or supplier consequences alongside throughput.',
  'Evidence file. Retain the scope, data dictionary, instruction and policy versions, source identifiers, sample selection, reviewer decisions, exception log, corrections, access review, analysis workbook or code, owner disposition, and next review date. Minimize personal and confidential information, apply the business retention rules, and restrict the file. A future reviewer should be able to reconstruct why the business continued, narrowed, redesigned, or stopped the lane. Material changes in systems, policy, staffing, products, suppliers, or customer channels make the earlier finding historical and trigger a proportionate retest.',
  'Decision cadence. Name a primary owner and a backup. Review ordinary exceptions predictably and route consequential cases immediately. Every review ends with recorded decisions, owners, due dates, and closure evidence. Do not turn a proposed threshold into a public service promise or portray a pilot result as typical provider performance. Record observation dates and the cutoff. The smallest safe expansion is one additional defined action, channel, or case type followed by another review; broad permissions should not be the reward for one favorable sample.',
  'Baseline and comparison. Observe the existing process before changing staffing when records permit. Use the same eligibility rules, cutoff logic, consequence categories, and review method for the baseline and pilot. Record any simultaneous change in volume, channel, product, policy, system, pricing, ownership, or customer mix. If the baseline is too incomplete to compare, say so and use the pilot to establish a prospective reference point; do not reconstruct a favorable baseline from memory. Compare like periods and show missingness. Improvement in one measure should be read beside transfers, corrections, unresolved work, and owner interventions so that work shifted elsewhere is not mistaken for work removed.',
  'Stopping and recovery. Define in advance which event pauses routine processing, who is notified, how affected records are preserved, and what evidence is required before restart. Examples include an unauthorized action, wrong-party disclosure, unsupported financial change, broken source integration, missing approval, or repeated high-consequence classification error. A pause is a control outcome, not automatically a specialist failure. Reconcile the affected population, reverse or correct only through authorized paths, notify appropriate owners, and preserve the before-and-after record. Resume narrowly after the cause and containment are reviewed. If the business cannot identify the affected population, the lane is not ready to expand.',
  'Buyer conclusion. Treat the study as a gate for one defined work lane, not a score for a person or a prediction about every provider. A favorable result means the observed lane met predeclared requirements under the recorded conditions. It does not show that broader permissions, additional channels, unsampled work, or a different operating period will perform the same way. A mixed result can still be useful when it identifies a repairable source, instruction, permission, or owner bottleneck. The decision record should state continue, narrow, repair and retest, or stop, with the evidence and the next review trigger.',
] as const;

const posts = [
  {
    slug: 'september-23-research-customer-correction-propagation',
    title: 'Customer Corrections: Test Whether the Fix Reaches Every Active Record',
    excerpt: 'Measure whether a corrected customer fact survives inbox, CRM, ticket, and owner handoffs before expanding outsourced support.',
    serviceHandoff: { href: '/services/customer-support', label: 'Design a controlled customer-support lane', description: 'Use source-linked correction records while keeping identity, policy, remedies, and sensitive decisions with the business.' },
    referenceSources: [sources.sba, sources.ftcSecurity, sources.nist],
    body: [
      'Decision in view. A support team can acknowledge a correction accurately and still leave the wrong address, contact preference, order reference, or case status active somewhere else. This study calls that gap correction-propagation failure. The buyer decision is whether a bounded customer-support lane can carry an approved correction across the systems and people that legitimately depend on it. It is not permission to change identity, account ownership, financial details, consent, eligibility, or policy on a customer request alone. The useful result is a traceable update packet: original statement, verified fact, authorized destinations, completed updates, exceptions, and a final owner disposition.',
      'Evidence and inference. SBA operating guidance supports clear processes and review. FTC security guidance advises businesses to know what personal information they hold, keep only what they need, protect it, and dispose of it securely. NIST CSF 2.0 frames governance, protection, detection, response, and recovery. None specifies a propagation benchmark or decides when a customer statement is sufficient proof. We infer a narrow control: define which record is authoritative for each field, what verification is required, which downstream copies may be updated, and which changes demand an owner or security route.',
      'Population. Select one correction class and a consecutive four-to-six-week intake window. Include requests received through every declared channel, including incomplete, duplicate, suspicious, withdrawn, and still-open cases. Assign an immutable case identifier. Preserve the customer wording, receipt time, authenticated context if any, field requested, prior value with appropriate protection, verification performed, systems believed to consume the field, actions, messages, and cutoff status. Do not copy sensitive values into the research file when a protected source reference is enough. Excluding difficult requests after seeing their outcome would make propagation appear more reliable than it is.',
      'Propagation map. For each field, identify the system of record, authorized updater, dependent systems, synchronization method, expected delay, manual consumers, and exception owner. Distinguish correction accepted, verification required, update proposed, source updated, downstream confirmed, conflict found, customer notified, and closed. A CRM note is not proof that billing, fulfillment, support, or a scheduled job changed. Conversely, not every duplicate should be updated; some are historical evidence. The owner must decide whether a correction changes future actions, repairs an earlier record, or both.',
      'Measures and review. Report eligible cases, verified requests, authoritative records updated, expected destinations checked, destinations matching at cutoff, conflicts, unauthorized attempts, customer notices, reopen events, and unresolved age. Show counts and denominators. Audit in both directions: begin with a correction and follow it outward, then sample active downstream records and trace their current value back to authority. Critical defects include wrong-person changes, lost verification, security-sensitive updates outside the approved path, or customer action taken from a known stale value. Separate system latency from specialist delay and owner delay.',
      'Pilot rule and limitations. Begin in prepare-and-verify mode: the specialist identifies destinations, gathers permitted evidence, drafts routine notices, and records exceptions; authorized owners perform protected changes. Expand one low-risk field only when the trail reconstructs, expected destinations converge, conflicts stop safely, and open corrections remain within review capacity. A short study can miss rare integrations, batch jobs, seasonal channels, fraud patterns, and records held by processors. Agreement at cutoff does not prove that every future consumer will use the corrected value. This is operational research, not privacy, identity, legal, or security advice. The bounded conclusion concerns whether approved corrections remain intact through a defined support handoff.',
      ...sharedMethod,
    ],
  },
  {
    slug: 'september-23-research-bookkeeping-cutoff-integrity',
    title: 'Bookkeeping Cutoff Integrity: Test When Activity Enters the Review Queue',
    excerpt: 'Study whether documents and transactions land in the right review period without giving away accounting judgment.',
    serviceHandoff: { href: '/services/small-business-bookkeeping', label: 'Scope bookkeeping preparation', description: 'Build a source-linked cutoff queue while reserving accounting treatment, filing, payment, and close approval for qualified owners.' },
    referenceSources: [sources.irs, sources.finance, sources.nist],
    body: [
      'Decision in view. A tidy bookkeeping queue can still mislead when late documents, duplicated feeds, pending transactions, credits, or corrected invoices are assigned to a convenient period without evidence. Cutoff integrity here means that each item is captured with its actual source dates and routed for the appropriate owner decision; it does not mean an administrative specialist chooses accounting treatment. The buyer decision is whether repeatable document collection, matching, status maintenance, and exception preparation can be delegated while a qualified reviewer retains period, recognition, tax, adjustment, and close decisions.',
      'Evidence and inference. IRS Publication 583 describes supporting documents and record systems that clearly show business activity. SBA financial guidance supports orderly financial management and review. NIST provides governance and access principles for systems and information. Those sources do not prescribe the accounting basis, close calendar, materiality, or treatment for a particular company. We infer only that an outsourced preparation lane should preserve source evidence, distinguish dates instead of collapsing them, and put ambiguous timing in a visible exception queue rather than silently selecting a period.',
      'Population and dates. Choose one entity, currency, source family, and two adjacent review periods. Include every item arriving through declared feeds and document channels, including pending, reversed, duplicated, missing, personal-looking, disputed, and unresolved entries. Retain a source identifier, document date, service or fulfillment date when available, transaction authorization and posting dates where applicable, receipt time, import time, amount, counterparty, linked support, matching status, correction history, and reviewer decision. Never alter a source date to agree with a reporting cutoff. Unknown and not applicable require separate values.',
      'Queue design. Define collected, readable, matched, possible duplicate, missing support, date conflict, amount conflict, awaiting owner, reviewer adjusted, approved, and closed. The specialist may gather records, detect exact or probable matches under a documented rule, identify missing fields, and prepare an exception packet. The specialist should not infer the period, expense class, asset treatment, liability, revenue treatment, tax status, write-off, journal entry, or materiality from a deadline. A close checklist is evidence that steps were performed, not proof that the resulting accounts are correct.',
      'Measures and tests. Report captured items, records with required dates, matches supported by both sides, potential duplicates, late arrivals, date conflicts, unresolved values, owner decisions, post-review corrections, and open age at each cutoff. Compare the source population with the preparation queue and then trace a sample back from the queue to the original evidence. Reperform automated date extraction on a blinded sample. Separate ingestion delay, document delay, processor posting delay, specialist delay, and reviewer delay. One large item and many small items need count and value views; neither should hide the other.',
      'Decision and limitations. Expand only when population completeness is demonstrable, source dates survive import, uncertain timing stops for review, duplicates remain visible, access is narrow, and the qualified reviewer can reconstruct changes. If late documents dominate, repair collection before adding classification capacity. If owner decisions accumulate, define a close decision window rather than letting the specialist guess. Pending transactions, refunds, accruals, processor batches, time zones, and corrected supplier records complicate cutoff. A two-period study misses annual and unusual events. This is not accounting, tax, audit, or legal advice. The bounded conclusion concerns readiness of evidence preparation, not the correctness of financial statements.',
      ...sharedMethod,
    ],
  },
  {
    slug: 'september-23-research-appointment-cancellation-attribution',
    title: 'Appointment Cancellations: Separate the Stated Reason From the Operational Cause',
    excerpt: 'Build a defensible cancellation record before changing scripts, capacity, or outsourced scheduling scope.',
    serviceHandoff: { href: '/services/local-service-scheduling', label: 'Plan a reviewable scheduling lane', description: 'Use a source-linked appointment history while keeping capacity, policy exceptions, pricing, and remedies with the owner.' },
    referenceSources: [sources.sba, sources.ftcAds, sources.nist],
    body: [
      'Decision in view. A cancellation dashboard may label a slot customer cancelled even when the customer selected the nearest dropdown, the business rescheduled first, an address was outside the service area, or the underlying promise was never feasible. The stated reason, observed event, and operational cause are different evidence classes. Before expanding outsourced appointment coordination, a small business should test whether the record preserves that distinction. The decision is whether a specialist can maintain accurate histories and safe next actions, not whether that person can diagnose customers, set capacity, waive policy, or promise availability.',
      'Evidence and inference. SBA guidance supports deliberate management of operations and customer processes. FTC advertising guidance supports truthful representations, while NIST frames dependencies, governance, and information protection. These sources provide no universal cancellation target and do not establish causation. We infer that each appointment change should retain the original promise, actor, timestamp, source wording, capacity state, approved alternatives, and disposition. Local evidence can reveal repair candidates, but a reason code alone cannot prove why the appointment failed.',
      'Cohort. Select one service line, booking channel set, geography, and appointment window. Include kept, cancelled, rescheduled, no-show, business-cancelled, duplicate, test, disputed, and unresolved records so the denominator cannot be improved by dropping inconvenient outcomes. Preserve request time, booking time, service type, location facts required by policy, slot offered, capacity source and version, confirmations, reminders, every change event, initiator, original customer wording, chosen code, business constraint, final status, and cutoff. Minimize personal information and use identifiers in the analysis file.',
      'Classification. Keep customer-stated reason, scheduler observation, system event, and owner-assigned operational finding in separate fields. A customer saying unavailable is a fact about the statement, not proof that reminders failed. A no-show state is incomplete until the business confirms its own attendance evidence and contact rule. Use categories such as customer request, business capacity change, eligibility or location conflict, duplicate, communication failure, unknown, and mixed, but retain the underlying record. A specialist may apply objective event labels and propose a route; causal attribution, fees, exceptions, blame, and remedies remain with the owner.',
      'Measures and counterchecks. Report the full cohort, change-event completeness, records with preserved wording, stated reasons, owner findings, agreement between the two, changes after confirmation, capacity-caused moves, unresolved cases, rebookings, and owner decisions. Display counts with rates and show time from each event to the next supported action. Audit consecutive cases plus high-consequence changes. Compare booked capacity as it appeared at the time with later capacity history; never judge an earlier action solely from the current calendar. Test the same record with two reviewers and retain disagreements.',
      'Decision and limitations. Expand only if appointment history reconstructs, objective classifications agree, unknowns remain visible, approved alternatives match real capacity, sensitive cases stop, and owners can handle exceptions. If reasons are missing, repair capture before changing reminder scripts. If business-driven moves dominate, scheduling labor is not the primary constraint. Short windows miss seasonality, weather, illness, campaign mix, and repeat customers. Self-reported reasons may be incomplete; rebooking does not prove satisfaction; observation cannot establish that a reminder caused attendance. This is operational research, not consumer, accessibility, employment, or legal advice. The bounded conclusion concerns scheduling-record reliability.',
      ...sharedMethod,
    ],
  },
  {
    slug: 'september-23-research-content-asset-provenance',
    title: 'Content Asset Provenance: Test the Evidence Before Scheduling Publication',
    excerpt: 'Verify the source, permitted use, version, and approval of creative assets in an outsourced content lane.',
    serviceHandoff: { href: '/services/social-content-administration', label: 'Design a controlled content-operations lane', description: 'Maintain an evidence-backed asset register while keeping rights interpretation, claims, endorsements, and final approval with the business.' },
    referenceSources: [sources.copyright, sources.ftcAds, sources.nist],
    body: [
      'Decision in view. A polished calendar does not show whether an image, clip, testimonial, chart, font, or customer submission came from an approved source or remains suitable for the intended channel and date. Provenance is the evidence chain connecting an asset to its origin, version, permitted business use, modifications, required attribution or disclosure, approval, and final publication. The buyer decision is whether an outside specialist can administer that chain and stop uncertainty before scheduling. It is not authorization to interpret ownership, licenses, publicity rights, platform rules, endorsements, or fair use.',
      'Evidence and inference. The U.S. Copyright Office explains foundational copyright concepts, while FTC advertising guidance addresses truthful marketing and endorsement considerations. NIST informs governance, integrity, and access controls. None decides rights for a specific asset, jurisdiction, agreement, person, or use. We infer an operational safeguard: every production asset should have a stable identifier, source reference, intended-use record, approval state, and version history. Missing evidence is an exception, not an invitation to search for a convenient copy or assume that online availability permits reuse.',
      'Inventory. Select one campaign family and every asset proposed, rejected, replaced, scheduled, or published during the declared window. Include customer submissions, contractor work, licensed libraries, internally created files, generated media, screenshots, charts, music, fonts, templates, logos, and platform-native elements where relevant. Record the asset identifier, original file hash, creator or supplied-by field, acquisition source, agreement or license reference, acquisition date, allowed-use summary supplied by the owner, restrictions, attribution instruction, people or marks depicted, edits, derivative versions, channel, planned date, approver, final file hash, and publication URL.',
      'Workflow boundaries. The specialist may intake files from approved sources, verify required fields, compare the final file with the approved version, apply owner-provided credits, prepare channel variants, and place uncertain assets on hold. The specialist should not determine who owns a work, whether permission is valid, whether an exception applies, whether a likeness or trademark may be used, or whether a disclosure is legally sufficient. An approval must identify the asset version and intended use; general campaign approval should not silently authorize later replacements. Removing metadata or changing a filename does not create clean provenance.',
      'Measures and review. Report inventory completeness, assets with source references, owner-supplied use decisions, version-matched approvals, required credits present, replacements after approval, publications matching final hashes, expired or restricted items, holds, and unresolved assets. Sample high-risk categories separately and trace published output backward to the final approved file, then trace inventory items forward to disposition. Critical defects include publishing the wrong version, exposing confidential source material, omitting an owner-required disclosure, or using an asset placed on hold. Count clean administrative packets; do not label them legally cleared.',
      'Decision and limitations. Expand scheduling access only when the register covers every asset, final versions match approvals, restrictions remain visible, replacements reopen review, and uncertain material reliably stops. If source evidence arrives late, move the deadline for asset intake; do not compress review into the publishing window. Contracts, licenses, platform terms, publicity and privacy rights, trademarks, accessibility, and law vary. A complete register does not prove permission, and a takedown-free history does not prove lawful use. This is operational research, not legal advice. The bounded conclusion concerns whether evidence and approvals survive the content handoff.',
      ...sharedMethod,
    ],
  },
  {
    slug: 'september-23-research-operational-recovery-point-test',
    title: 'Operational Recovery Points: Test What Work Survives an Interrupted Handoff',
    excerpt: 'Run a bounded recovery exercise before relying on an outsourced daily operations lane for continuity.',
    serviceHandoff: { href: '/services/operations-support', label: 'Scope a resilient administrative lane', description: 'Build reconstructable queues and backup handoffs while keeping incident, security, money, and policy decisions with the owner.' },
    referenceSources: [sources.nist, sources.ftcSecurity, sources.sba],
    body: [
      'Decision in view. A daily queue may look controlled until the usual specialist, owner, inbox, integration, or device is unavailable. An operational recovery point is the latest trustworthy state from which an authorized backup can reconstruct completed work, open items, evidence, customer commitments, exceptions, and the next safe action. This is not a technical backup metric and does not promise disaster recovery. The buyer decision is whether one bounded administrative lane preserves enough current state to continue or pause safely without private memory, shared credentials, or unsupported action.',
      'Evidence and inference. NIST CSF 2.0 includes governance, protection, detection, response, and recovery outcomes. FTC security guidance emphasizes understanding information, limiting access, protecting it, and planning for incidents. SBA guidance supports managed business operations. These sources do not set a recovery time or prove a staffing arrangement resilient. We infer that continuity requires a declared source of truth, append-only change evidence, named primary and backup roles, an escalation path, and a tested method for finding the last reliable state.',
      'Exercise scope. Choose one repeatable, low-risk lane and a harmless simulation window. Freeze the eligible queue at a recorded time. Without disabling real controls or impersonating anyone, give the authorized backup the normal instruction, permitted accounts, queue, source links, and escalation contacts. The primary should leave no special hints beyond the standard record. Observe whether the backup can identify completed, pending, waiting, blocked, duplicate, customer-promised, owner-decided, and unknown items. Protect live customers by using read-only reconstruction or owner-approved synthetic records where action would create risk.',
      'Evidence packet. Each work item needs an immutable identifier, source request, current state, last supported action, actor and timestamp, instruction version, linked output, open question, deadline or review date, authority needed, customer or supplier promise if any, and next owner. The lane register also needs system dependencies, authentication route, backup contact, safe-stop rule, and restoration check. Chat messages and personal notes can point to evidence but should not be the only record. A green status without a source link is not a recovery point.',
      'Measures. Report population reconciled, states independently reproduced, missing source links, contradictory states, inaccessible records, work falsely treated as complete, customer promises found, exceptions routed, time to safe orientation, owner interventions, and items still unknown at cutoff. Prioritize consequence over average time. Conduct a reverse check by asking the primary to review the backup reconstruction without revealing the expected answers beforehand. Record whether disagreement came from stale instructions, undocumented action, permission design, integration lag, ambiguous status, or reviewer interpretation.',
      'Decision and limitations. Continue only if the backup can reconstruct the lane without shared secrets, prevent duplicate or unsafe action, locate promises, reach the correct owner, and leave a reviewable trail. If access is excessive, redesign roles; if access is missing, do not automatically broaden it—consider a safer read-only view or owner bridge. A tabletop test does not reproduce outages, attacks, regional events, vendor failures, or pressure. Synthetic records may be easier than real work, while one successful recovery can become obsolete after a system change. This is not business-continuity, cybersecurity, legal, or emergency advice. The bounded conclusion concerns recoverability of one administrative handoff.',
      ...sharedMethod,
    ],
  },
] as const;

export const septemberTwentyThreeResearchBatch = posts.map((post) => ({
  ...post,
  published,
  imagePath: '/filipino-support-workspace.jpg',
}));
