export const septemberTwentyFourPublicationDate = '2026-09-24' as const;

type Topic = readonly [slug:string,title:string,excerpt:string,lane:string,work:string,example:string,boundary:string,service:string,metric:string];
const topics: readonly Topic[] = [
  ['outsource-ecommerce-returns-support','How to Outsource Ecommerce Returns Support Without Losing Policy Control','A practical returns lane for request intake, eligibility checks, labels, and status updates while refunds and policy exceptions stay with the store.','ecommerce returns support','return requests, order verification, approved eligibility rules, label status, warehouse receipt, and customer updates','A customer says an opened final-sale item arrived damaged and asks for an immediate refund to a different payment method.','Refund approval, policy exceptions, fraud decisions, payment changes, inventory write-offs, and legal promises remain with authorized store staff.','ecommerce-order-support','requests matched to valid orders, policy exceptions routed, label accuracy, warehouse confirmation, and time to resolution'],
  ['outsource-saas-support-ticket-triage','How to Outsource SaaS Support Ticket Triage for a Small Software Company','Build a first-line queue for reproducible issue details, known fixes, and engineering handoffs without letting support promise product changes.','SaaS support ticket triage','account verification, browser and device details, reproduction steps, approved help articles, incident status, and engineering handoffs','A customer reports missing data, calls it a security breach, and demands a restoration time that engineering has not confirmed.','Security incident classification, data-restoration promises, roadmap commitments, account ownership changes, credits, and legal statements stay with authorized leaders.','customer-inbox-management','tickets with complete reproduction details, correct severity routing, approved answers used, and reopened ticket rate'],
  ['outsource-home-care-scheduling-admin','How to Outsource Home Care Scheduling Administration Safely','Coordinate approved visits, availability, and call-outs while care decisions, credential judgments, and emergencies remain with licensed or local leaders.','home care scheduling administration','approved visit schedules, caregiver availability, call-outs, travel windows, client confirmations, and supervisor escalation','A caregiver calls out before a visit and the client reports a new symptom while asking whether the replacement can change the care plan.','Clinical advice, care-plan changes, emergency direction, credential exceptions, overtime approval, and suitability decisions remain with authorized agency staff.','local-service-scheduling','visits confirmed against approved plans, uncovered shifts escalated, schedule changes acknowledged, and no unapproved care promise'],
  ['outsource-veterinary-appointment-reminders','How to Outsource Veterinary Appointment Reminders and Recall Admin','Use a controlled reminder lane for appointments and approved recall lists while medical advice and urgent triage stay inside the clinic.','veterinary reminder and recall administration','appointment reminders, approved preventive-care recall lists, contact preferences, reschedule requests, and failed-contact notes','A pet owner replying to a routine vaccine reminder says the animal is struggling to breathe and asks whether tomorrow is soon enough.','Clinical triage, treatment advice, medication guidance, urgency decisions, fee exceptions, and release of medical records stay with clinic staff.','customer-support','reminders sent through approved channels, preferences respected, urgent language escalated, and confirmed schedule changes'],
  ['outsource-auto-repair-estimate-follow-up','How to Outsource Auto Repair Estimate Follow-Up Without Making Price Promises','Delegate approved estimate delivery, customer questions, and authorization tracking while diagnosis and repair recommendations stay with the shop.','auto repair estimate follow-up','approved estimate delivery, contact attempts, customer questions, authorization status, parts timing, and pickup updates','A customer disputes a diagnostic charge, asks whether the car is safe to drive, and wants a guaranteed final price before teardown.','Safety advice, diagnosis, repair recommendations, price changes, warranty decisions, and payment disputes remain with authorized shop staff.','customer-support','approved estimates delivered, authorization evidence captured, questions routed, and stalled jobs surfaced'],
  ['outsource-landscaping-lead-intake','How to Outsource Landscaping Lead Intake and Quote Scheduling','Create a lead-intake lane for property details, service fit, photos, and appointment windows without giving away scope or price authority.','landscaping lead intake','contact details, service address, requested work, property access, photos, timing, service-area fit, and approved consultation slots','A prospect requests tree removal beside a power line and asks for a binding price from photos before anyone visits.','Hazard assessment, arborist judgment, scope design, pricing, permits, service-area exceptions, and binding commitments remain with local managers.','lead-intake-administration','qualified records with complete site details, valid appointments, hazards routed, and estimator callbacks caused by missing information'],
  ['outsource-mortgage-broker-document-follow-up','How to Outsource Mortgage Broker Document Follow-Up Without Giving Loan Advice','Organize approved document requests and status reminders while licensed personnel handle eligibility, rates, disclosures, and recommendations.','mortgage document follow-up','approved borrower checklists, secure upload status, missing pages, unreadable files, expiration dates, and licensed-review queues','A borrower asks whether moving money between accounts will improve approval odds and whether a quoted rate is guaranteed.','Loan advice, eligibility judgments, rate or fee representations, disclosure explanations, document alteration, and approval decisions stay with licensed staff.','administrative-support','documents received through approved channels, files matched correctly, missing items described accurately, and licensed questions routed'],
  ['outsource-architecture-project-administration','How to Outsource Architecture Project Administration Without Shifting Design Authority','Support transmittals, meeting records, submittal logs, and deadline tracking while architects retain design and code decisions.','architecture project administration','drawing and specification versions, transmittals, meeting actions, submittals, RFIs, consultant inputs, and milestone dates','A contractor asks whether a field substitution complies with code and wants email approval before concrete placement.','Design intent, code interpretation, professional seals, substitutions, contractual direction, and safety decisions remain with responsible professionals.','operations-support','current versions distributed, open decisions visible, deadlines surfaced, and no unapproved technical direction'],
  ['outsource-manufacturing-purchase-order-follow-up','How to Outsource Manufacturing Purchase Order Follow-Up','Track acknowledgments, dates, quantities, and shipping evidence while buyers retain supplier, specification, and commercial decisions.','manufacturing purchase order follow-up','approved purchase orders, supplier acknowledgments, promised dates, quantity variances, shipping documents, and receiving exceptions','A supplier cannot meet the date and proposes an unapproved material substitution with a higher unit price.','Supplier selection, specification changes, price acceptance, quality disposition, expedite fees, and contractual waivers remain with authorized staff.','supplier-coordination','acknowledgments matched to orders, variances flagged, dates updated from evidence, and late items escalated'],
  ['outsource-event-venue-inquiry-qualification','How to Outsource Event Venue Inquiry Qualification','Capture event requirements and schedule approved tours while capacity, alcohol, accessibility, pricing, and contract decisions remain with venue management.','event venue inquiry qualification','event date, guest count, event type, room needs, accessibility requests, catering questions, and approved tour times','A prospect wants to exceed the stated capacity, bring outside alcohol, and hold a date without the standard deposit.','Capacity and safety exceptions, alcohol rules, accessibility commitments, package pricing, date holds, deposits, and contract terms stay with managers.','lead-intake-administration','inquiries with complete requirements, tours matched to availability, exceptions surfaced, and no unapproved date or price promise'],
  ['outsource-association-membership-administration','How to Outsource Association Membership Administration','Handle routine applications, renewals, profile updates, and event records while eligibility and disciplinary decisions stay with the association.','association membership administration','application completeness, renewal notices, directory fields, payment status, event registration, and committee handoffs','An applicant lacks a required credential but asks to be listed immediately because an employer deadline is approaching.','Eligibility interpretation, waivers, credential validation, disciplinary matters, refunds, and public status representations remain with authorized association leaders.','administrative-support','complete applications, accurate renewal status, privacy preferences preserved, and exceptions routed before publication'],
  ['outsource-msp-ticket-intake','How to Outsource MSP Ticket Intake Without Expanding System Risk','Build a controlled IT service intake lane for identity checks, device facts, approved troubleshooting, and technician routing.','managed IT service ticket intake','requester verification, affected device and service, error text, business impact, approved checks, ticket priority, and technician handoff','A caller claiming to be an executive asks for an MFA reset and remote access to a finance employee’s computer.','Identity exceptions, credential resets, privileged access, security incident declarations, destructive changes, and contractual priority overrides remain with authorized technicians.','customer-support','verified requesters, complete technical context, correct security escalation, and tickets routed without unsafe access changes'],
];

export const septemberTwentyFourSources = [
  ['U.S. Small Business Administration guide to managing a business','https://www.sba.gov/business-guide/manage-your-business'],
  ['NIST Cybersecurity Framework 2.0','https://www.nist.gov/cyberframework'],
  ['CISA guidance on phishing-resistant MFA','https://www.cisa.gov/resources-tools/resources/implementing-phishing-resistant-mfa'],
] as const;

export const septemberTwentyFourBlogBatch = topics.map(([slug,title,excerpt,lane,work,example,boundary,service,metric]) => ({
  slug,title,excerpt,lane,publicationDate:septemberTwentyFourPublicationDate,imagePath:'/filipino-support-workspace.jpg',sources:septemberTwentyFourSources,service,
  sections:[
    ['Decide whether this lane is ready to outsource',`Start with the work, not a job title. For ${lane}, list the items that arrived during the last two normal weeks: ${work}. Mark the source of each item, the action taken, the person who approved an exception, and the evidence that showed completion. This sample reveals whether the lane repeats often enough to teach and whether its finish line is observable. Do not outsource a queue whose rules live only in one person's memory. First separate routine preparation from professional judgment, safety decisions, money movement, and commitments to customers. Write a one-sentence outcome that a reviewer can test. Then list eligible items, excluded items, normal service hours, and the person accountable for the result. This turns “help with ${lane}” into a bounded operating process. It also gives a provider enough detail to estimate staffing without pretending that every arrival takes the same effort.`],
    ['Map the intake before discussing staffing',`Create one intake record with an identifier, received time, requester, source link, relevant dates, required fields, current status, next action, and owner. Use statuses that explain what is happening: ready, working, waiting for requester, waiting for internal decision, scheduled, completed, or closed with a reason. Avoid a broad “in progress” status that hides delay. For this lane, the record should cover ${work}. Use a representative sample containing ordinary requests, missing information, duplicate messages, a change after submission, and at least one consequential exception. Measure active handling time separately from waiting time. A five-minute update may remain open for days while an authorized person decides. That difference affects coverage, service levels, and price. Before granting access, ask a candidate to process redacted samples and show what they would record, what they would return as incomplete, and what they would escalate.`],
    ['Set the authority boundary in verbs',`Define what the operator may view, create, edit, send, schedule, export, approve, merge, close, and delete. Pair each permitted verb with the required evidence and identify actions that always need review. ${boundary} A policy that merely says “ask when unsure” is not enough. Give the operator named stop conditions, a primary escalation contact, a backup, and the safe action while waiting. Use named accounts, multifactor authentication where supported, and only the folders, fields, and systems needed for the lane. NIST Cybersecurity Framework 2.0 offers a useful governance structure, and CISA explains stronger MFA options, but neither replaces a business-specific access decision. Test access removal before launch. Never put credentials in the SOP, work queue, or chat transcript.`],
    ['Work through a realistic exception',`Use this scenario during training: ${example} The operator should preserve the caller's or requester's wording, record the time and available source, avoid inventing an answer, and route the item through the written exception path. The business should decide in advance whether the operator may acknowledge receipt, which neutral language is approved, and when a live transfer or local response is required. Review the scenario from two angles. First, could delay create customer, safety, financial, privacy, or deadline risk? Second, would the proposed response exceed the operator's training or authority? A good escalation contains the identifier, verified facts, missing facts, attempted actions, requested decision, and supported due time. It does not bury the decision inside a long chat log. Store the final decision with the item so it becomes a future example only after an authorized reviewer approves it.`],
    ['Build the SOP from examples',`Write the shortest instruction that another trained person can follow. Start with the trigger, eligible inputs, required sources, step order, approved templates, quality checks, stop rules, escalation contacts, and completion evidence. Add three annotated examples: one ordinary item, one incomplete item, and one exception. For ${lane}, include screenshots or field names only when they are stable and do not expose real customer data. State which system is the source of truth when email, a portal, and a spreadsheet disagree. Preserve the conflict instead of silently selecting the convenient value. Give the SOP an owner, version, effective date, and review date. Operators may propose clarifications, but changes to authority, policy, or customer commitments require owner approval. Retire old versions so a backup worker cannot accidentally follow a superseded rule.`],
    ['Run a paid and reversible pilot',`Use a pilot with a start date, end date, eligible volume, working hours, accounts, reviewer, daily handoff, stop conditions, and acceptance rules. Begin with preparation or draft mode when an error could affect a customer, a protected record, money, safety, or a legal commitment. Review every consequential item and a random sample of routine work against the original source. Keep returned work in the record; deleting it makes the pilot look cleaner while hiding training needs. Limit volume until the operator can demonstrate the boundary as reliably as the routine steps. If a material error occurs, contain the affected item, correct the customer or system record through an authorized person, preserve what happened, and update the instruction or access. Expand only when another trained reviewer can reproduce why items passed, stopped, or escalated.`],
    ['Score quality without rewarding shortcuts',`Track ${metric}. Add received volume, completed volume, aging, returned work, clarification requests, repeated exceptions, and owner review minutes. Every percentage needs a denominator. Separate ordinary work from high-consequence exceptions, because combining them can hide the very cases that test the process. Do not reward closure speed if the operator can close an item with missing evidence. Sample completed items directly from the source system and compare the record, action, and timestamp. Count setup, training, tools, correction, management time, and coverage gaps alongside the provider fee. If no credible baseline exists, report the pilot period plainly rather than claiming savings. Agree before launch what evidence supports a go, revise, or stop decision. That prevents enthusiasm or frustration from changing the test after results arrive.`],
    ['Design the daily handoff and backup path',`At the beginning of each shift, review new arrivals, aging items, promised dates, failed contacts, and decisions returned by the business. During the shift, keep the source link and status current instead of reconstructing work at day end. Finish with a short handoff: completed items, exceptions, near-deadline items, failed system access, and the exact decisions needed from named people. The owner should answer in the shared record so the reasoning is available to reviewers and backup staff. Test backup coverage using a non-sensitive sample. The backup should be able to locate the live SOP, queue, approved language, source systems, and escalation contacts without borrowing another person's account. Weekly, sample quality and review recurring questions. Monthly, reassess permissions, volume, service windows, and whether the lane still creates useful owner capacity.`],
    ['Choose go, revise, or stop',`Choose go when outputs are usable, sources support the record, authority stayed within bounds, exceptions reached the right person, and management effort fits the benefit. Choose revise when the lane is valuable but needs a clearer field, example, schedule, permission, reviewer, or staffing assumption. Choose stop when the work depends on undocumented judgment, access cannot be limited, records cannot be reconstructed, or the provider repeatedly crosses consequential boundaries. Document who owns every open item and how access and data will be returned if the pilot ends. Before signing a longer arrangement, confirm fees, minimums, service windows, confidentiality, account ownership, work-product terms, incident notice, subcontracting, data return, and termination help in the actual agreement. For a next step, compare this plan with the on-site ${service.replaceAll('-',' ')} service guide and bring a small redacted sample to a scoping conversation.`],
  ] as const,
}));

export type SeptemberTwentyFourBlogPost = (typeof septemberTwentyFourBlogBatch)[number];
