export const septemberTwentyTwoPublicationDate = '2026-09-22' as const;

type Topic = readonly [slug:string,title:string,excerpt:string,lane:string,queue:string,risk:string,example:string,service:string];
const topics: readonly Topic[] = [
  ['outsource-appointment-scheduling-small-business','How to Outsource Appointment Scheduling Without Losing Control','Build a scheduling handoff around approved availability, complete intake, and clear exceptions.','appointment scheduling','new requests, confirmations, reminders, cancellations, and reschedules','overpromised availability or incomplete booking details','A caller wants a same-day slot outside the published service area.','local-service-scheduling'],
  ['ecommerce-customer-service-outsourcing-checklist','Ecommerce Customer Service Outsourcing Checklist','Prepare order access, reply rules, refund boundaries, and quality checks before handing off an ecommerce queue.','ecommerce customer service','order-status questions, delivery exceptions, returns, and address corrections','an unsupported promise about delivery, replacement, or refund','The store shows fulfilled while the carrier has not received the parcel.','ecommerce-order-support'],
  ['outsource-lead-intake-without-losing-leads','How to Outsource Lead Intake Without Losing Good Prospects','Create a fast, complete lead-intake routine while keeping qualification, pricing, and promises with the owner.','lead intake administration','website forms, calls, email inquiries, source attribution, and follow-up reminders','missing context or an unauthorized sales promise','A prospect requests a custom service and asks for a price before sharing the required details.','lead-intake-administration'],
  ['outsource-invoice-follow-up-small-business','How to Outsource Invoice Follow-Up for a Small Business','Delegate factual payment reminders while protecting customer relationships and owner-only decisions.','invoice follow-up','verified aging records, reminder dates, replies, disputes, and promised payments','contacting the wrong customer or stating an unverified balance','A customer says the work was disputed even though the accounting queue still shows the invoice overdue.','invoice-follow-up'],
  ['outsource-customer-inbox-management','How to Outsource Customer Inbox Management','Turn a crowded inbox into a controlled queue with source-backed drafts, aging rules, and sensitive-message escalation.','customer inbox management','triage, labels, draft replies, follow-ups, and unresolved threads','deleting context or sending a sensitive reply without approval','A routine-looking email contains a privacy request and a threat to post publicly.','customer-inbox-management'],
  ['outsource-supplier-coordination-small-business','How to Outsource Supplier Coordination Without Creating Procurement Risk','Delegate status chasing and recordkeeping while reserving commitments, substitutions, and changed terms for the owner.','supplier coordination','requests, confirmations, delivery dates, dependencies, and open questions','treating an informal change as an approved commercial commitment','A supplier offers a substitute product at a different price after the original delivery slips.','supplier-coordination'],
  ['outsource-online-review-responses','How to Outsource Online Review Response Drafting Safely','Use factual drafts, privacy checks, and approval rules to respond promptly without inventing customer outcomes.','online review response drafting','new reviews, fact gathering, draft status, approvals, and publication records','disclosing private details or admitting facts that have not been verified','A one-star review uses a name that does not match any visible customer record.','review-response-drafting'],
  ['outsource-weekly-dashboard-reporting','How to Outsource Weekly Dashboard Reporting','Create source-linked reporting that saves owner time without turning missing data into confident numbers.','weekly dashboard reporting','measure refreshes, source links, exceptions, trend notes, and owner decisions','silently estimating a missing value or changing a metric definition','The CRM total and billing-system total disagree on completed jobs for the same week.','owner-dashboard-reporting'],
  ['outsource-crm-data-cleanup','How to Outsource CRM Data Cleanup Without Damaging Customer Records','Define safe merge, update, enrichment, and review rules before a specialist edits your CRM.','CRM data cleanup','duplicates, missing fields, stale stages, bounced contacts, and source evidence','merging different people or overwriting a valid customer history','Two contacts share a company and surname but have different email addresses and buying histories.','administrative-support'],
  ['outsource-appointment-setting-sales-team','How to Outsource Appointment Setting for a Small Sales Team','Separate prospect research and scheduling from qualification judgment, pricing, and sales commitments.','sales appointment setting','approved prospect lists, contact attempts, replies, calendar holds, and handoffs','misrepresenting the business or booking meetings that do not meet the written rule','A prospect agrees to meet only after asking for a discount the setter is not authorized to discuss.','administrative-support'],
  ['outsource-order-exception-management','How to Outsource Ecommerce Order Exception Management','Build an exception queue for delayed, mismatched, returned, and incomplete orders without giving away refund authority.','order exception management','carrier mismatches, address problems, stock issues, returns, and aging cases','closing an exception before the customer and system records agree','A package is marked delivered, the customer reports nonreceipt, and the address matches the order.','ecommerce-order-support'],
  ['who-owns-sop-updates-outsourced-team','Who Should Own SOP Updates on an Outsourced Team?','Set a practical change-control routine so operators can flag gaps while business owners approve policy and authority changes.','SOP change control','clarification requests, proposed edits, examples, approvals, versions, and training acknowledgments','an operator quietly changing a rule after one unusual case','A new customer exception exposes a missing step, but the proposed fix would expand refund authority.','operations-support'],
];

const sourceLinks = [
  ['U.S. Small Business Administration management guidance','https://www.sba.gov/business-guide/manage-your-business'],
  ['NIST Cybersecurity Framework 2.0','https://www.nist.gov/cyberframework'],
  ['Federal Trade Commission business guidance','https://www.ftc.gov/business-guidance'],
] as const;

export type SeptemberTwentyTwoBlogPost = { slug:string; title:string; excerpt:string; lane:string; publicationDate:typeof septemberTwentyTwoPublicationDate; imagePath:string; sections:readonly (readonly [string,string])[]; sources:typeof sourceLinks };

export const septemberTwentyTwoBlogBatch: SeptemberTwentyTwoBlogPost[] = topics.map(([slug,title,excerpt,lane,queue,risk,example,service]) => ({
  slug,title,excerpt,lane,publicationDate:septemberTwentyTwoPublicationDate,imagePath:'/filipino-support-workspace.jpg',sources:sourceLinks,
  sections:[
    ['Define the outcome before choosing a person',`Outsourcing ${lane} works best when the business defines a finished result before discussing hours or job titles. Start with ten recent items and trace each one from arrival to completion. For this lane, the working queue includes ${queue}. Record what made each item actionable, which source established the facts, who made any judgment call, and what evidence showed the work was finished. This exercise turns a vague request for “help” into a reviewable operating lane. It also exposes work that should stay internal. Write a one-sentence outcome, a short list of eligible items, and an explicit list of exclusions. A Philippines-based specialist can then be selected and trained against real work instead of a generic assistant description. The owner should be able to look at the resulting queue and tell, without asking for a private explanation, what happened and what still needs a decision.`],
    ['Prepare a representative workload sample',`Count arrivals by day and week, including quiet periods, deadlines, and seasonal spikes. Note the channel, required response window, handling time, waiting time, and most common reason an item stops. Do not size the role from a single unusually busy week or from a provider's suggested capacity. Use a sample containing normal work, incomplete inputs, duplicates, and at least one consequential exception. Remove personal or confidential details when candidates only need to demonstrate their method. Ask each candidate to process the same sample and show their sources, assumptions, status choices, and escalation. For ${lane}, volume alone does not establish workload: an item that waits two days for owner approval may take five minutes of operator time while remaining important to the customer. Separate active handling from waiting so coverage, pricing, and service windows can be compared honestly.`],
    ['Write the authority boundary',`List what the specialist may view, create, edit, send, schedule, export, approve, close, and delete. Pair every permitted action with its required evidence. The main avoidable risk in this lane is ${risk}. Keep money movement, credentials, contracts, policy changes, sensitive customer remedies, legal conclusions, and unsupported public claims with a named business owner. Consider this case: ${example} The instruction should say what the specialist can verify, what may be drafted or recorded, and which person receives the held item. “Use your judgment” is not an escalation rule. Use named accounts, the minimum necessary permissions, multifactor authentication where supported, and a tested removal process. NIST Cybersecurity Framework 2.0 is a useful governance reference, but the business still needs controls suited to its tools, customers, and risk.`],
    ['Build one intake and status record',`Every item should carry an identifier, received time, original request, source link, owner, current status, next action, and due point. Design statuses around decisions: ready to work, waiting for evidence, waiting for owner approval, scheduled, completed, or closed with a stated reason. Avoid an all-purpose “in progress” label that hides waiting and rework. Preserve corrections rather than overwriting the history that explains a result. If two systems disagree, record both values and stop at the approved boundary. For ${lane}, a replacement operator should be able to reconstruct one completed item and one held exception from the shared record alone. If that is impossible, the intake fields or source links need improvement. Keep business decisions with the work item rather than in private chat, because a side-channel answer cannot reliably train the next person or support a later quality review.`],
    ['Create examples and response rules',`Prepare at least three approved examples: an ordinary item, an incomplete item, and an exception that must stop. Annotate why each action was acceptable. If the work involves communication, distinguish drafts, messages that may be sent from an approved template, and replies that always require review. State which facts must be checked immediately before sending, because a correct draft can become wrong when status changes. For ${lane}, tone guidance should be specific enough to apply but should never override accuracy. Ban invented deadlines, results, testimonials, discounts, guarantees, and explanations. The specialist may acknowledge receipt and describe the next verified step without pretending that a decision has already been made. Store current language in one controlled location, retire obsolete versions, and name the person who approves changes. Examples reduce needless questions while making the boundary more concrete than a long policy paragraph.`],
    ['Run a paid, reversible pilot',`Define a pilot with dates, eligible volume, accounts, service window, reviewers, daily handoff, stop conditions, and acceptance rules. Start in draft or preparation mode when customer-facing or financial consequences are possible. Review every high-impact item and a random sample of routine work against the original source. Preserve returned items and questions; they show where the process or training is weak. A pilot is not successful because every row was marked complete. Success means the outputs are usable, exceptions reached the correct owner, records can be reconstructed, and the business spent an acceptable amount of time supervising the work. If a defect could harm a customer, payment, account, or public statement, contain it first, correct the record, and then adjust the instructions. Expand only the item types that another trained person could reproduce under the same rules.`],
    ['Measure quality and owner effort',`Track accepted items, returned work, significant defects, clarification requests, exception accuracy, queue age, and owner review minutes. Give every rate a denominator and separate routine work from consequential cases. Count setup, coaching, correction, coordination, tools, and waiting costs alongside provider fees. A fast queue can still be poor if it produces reopened work or shifts difficult decisions back to the owner without context. Compare the pilot with a credible baseline from the same workflow; if none exists, report the first period plainly rather than inventing a savings claim. The U.S. Small Business Administration's management resources can help frame planning and oversight, but they do not validate a particular provider or guarantee a result. Decide before launch what evidence would support expanding, revising, or ending the lane so enthusiasm does not rewrite the test.`],
    ['Plan the daily and weekly routine',`At the start of each work period, the specialist should review new items, aging work, deadlines, and decisions returned by the owner. During the shift, keep source links and statuses current rather than reconstructing the history later. End with a short handoff covering completed work, exceptions, items near deadline, and the exact owner decisions needed. The owner should answer in the shared record and avoid creating a separate instruction trail. Weekly, sample completed work, review repeated questions, inspect permissions, and decide whether an example or rule needs revision. Monthly, reassess volume, coverage, access, and whether the lane still creates useful capacity. This rhythm makes ${lane} manageable without constant monitoring. It also gives a Philippines-based team a clear asynchronous handoff when the owner's workday and the specialist's schedule only partly overlap.`],
    ['Choose a go, revise, or stop decision',`Choose “go” when the work is usable, the authority boundary held, exceptions reached the right owner, and total management effort fits the benefit. Choose “revise” when the lane is valuable but fields, examples, permissions, staffing, or response rules need a bounded change. Choose “stop” when the workflow depends on undocumented judgment, access cannot be limited, records cannot be reconstructed, or customer and business risk remains unacceptable. Document the reason and the recovery action for open items. Before committing, confirm fees, minimums, coverage assumptions, account ownership, confidentiality, work-product terms, data return, access removal, and transition support in the actual agreement. Legal, employment, tax, privacy, and regulatory questions belong with qualified advisers for the relevant jurisdictions. To turn this workflow into a controlled handoff, review the on-site service guide for ${service.replaceAll('-',' ')} and bring a small sample of real, redacted work to the scoping call.`],
  ]
}));
