const published = '2026-09-04' as const;
const blogImage = '/filipino-support-workspace.jpg';
const researchImage = '/aug31-heroes/research-claim-map.png';

type BlogSeed = {slug:string;title:string;excerpt:string;lane:string;record:string;exception:string;measure:string};
function blog(seed:BlogSeed){return {...seed,publicationDate:published,imagePath:blogImage,sections:[
  ['Define the finish line',`Small businesses often outsource ${seed.lane} because it repeats, yet repetition does not make every case routine. Begin with one observable finish line. State what arrives, what the specialist may change, what evidence must remain attached, and who accepts the result. ${seed.record} Use examples from the business's own queue, including one clean item and one awkward item. The first week should be a supervised sample, not a promise that the entire backlog will disappear. This narrower start gives the owner something real to inspect and gives the specialist a fair way to learn the work.`],
  ['Keep the source beside the work',`The working record should retain the original request, its identifier, the time received, relevant attachments, and the instruction version used. A tidy summary is helpful, but it must not replace the source. Mark unknown values as unknown and conflicting values as conflicts. Do not fill gaps from memory. For ${seed.lane}, a Philippines-based specialist can collect, label, compare, and prepare. The business still owns facts that require verification and decisions that create a commitment. That division is especially useful when another person needs to reconstruct the case after a handoff.`],
  ['Use statuses that explain what happens next',`Avoid a single vague status such as pending. Separate work that is ready, waiting for a source, waiting for the customer, held for owner review, returned for correction, and complete with evidence. Each held item needs a next owner and review time. Completion should require the stated finish line, not merely an activity log. When the queue is busy, sort first by consequence and promised response time. A transparent hold is better than a quick guess because it lets the owner address the exact obstacle without rereading the full history.`],
  ['Build an exception route before launch',`${seed.exception} Put these cases in a visible exception lane with the triggering fact, supporting source, safe temporary action, and named decision owner. The specialist should never be rewarded for making the exception count look small. Repeated exceptions may reveal a missing intake field, an outdated instruction, weak permissions, or a genuine policy question. Review the pattern and improve the system instead of asking someone to improvise. The owner decides whether a rule changes and records the reason so the next case does not depend on a private conversation.`],
  ['Match access to the assignment',`List the exact systems and actions required for ${seed.lane}. Prefer named accounts, multifactor authentication, and the smallest useful permissions. Separate preparation from approval for payments, refunds, contracts, customer remedies, access changes, employee matters, and public claims. If a tool cannot enforce that boundary, use a reviewer queue or keep the action outside the outsourced lane. Record who granted access and when it should be reviewed. Remove unused access promptly. A broad administrator account is not a substitute for a clear process.`],
  ['Review real samples',`During the trial, review every high-consequence item and a random sample of ordinary ones. Compare each result with the source, instruction, output, and approval trail. Classify defects by consequence and cause. A spelling correction calls for a different response from a wrong customer promise or an unsupported record change. Return feedback with the exact item and a corrected example. If the same issue returns, revise the intake, example, permission, or decision rule. General reminders to be careful rarely fix a system that supplies ambiguous evidence.`],
  ['Measure the lane without hiding rework',`${seed.measure} Always show the denominator and keep aging beside volume. Count returned work, corrections, reopened items, and exceptions rather than reporting only completions. Track how much owner time is needed to review the lane. A specialist may prepare the numbers and point out observed patterns, but the business decides what they mean. Do not turn a small internal trial into a public claim about savings or performance. Useful measurement helps decide whether to narrow, improve, pause, or gradually expand the work.`],
  ['Run a reversible first week',`Choose a limited set that contains normal variation without exposing the whole business. Agree on schedule, eligibility, exclusions, review sample, stop conditions, and the handoff format before the first item. Keep questions and returned work in the record. At the end of the week, trace one completed case and one held case from intake to disposition. Check whether another person can follow the evidence. Expand only the stable parts. If review still requires the owner to rebuild every case, improve the inputs before adding volume.`],
] as const};}

export const septemberFourBlogBatch = [
 blog({slug:'outsourcing-small-business-quote-request-intake',title:'How to Outsource Quote Request Intake Without Promising a Price',excerpt:'Organize customer requirements and missing facts while keeping prices, scope, and commitments with the owner.',lane:'quote request intake',record:'Capture the requested service, quantity, location, timing, constraints, referral source, and customer contact details.',exception:'Rush requests, unclear specifications, regulated work, custom discounts, and requests outside the normal service area need owner review.',measure:'Track requests received, complete briefs, missing fields, response aging, owner decisions, corrections, and quotes returned for clarification.'}),
 blog({slug:'outsourcing-small-business-return-authorization-prep',title:'Outsource Return Authorization Preparation With Clear Approval Limits',excerpt:'Prepare order evidence and policy matches without delegating refunds or customer remedies.',lane:'return authorization preparation',record:'Preserve the order number, item, delivery evidence, customer reason, photos, policy version, and earlier support messages.',exception:'Safety concerns, chargebacks, damaged high-value goods, expired windows, repeat claims, and exceptions to policy must be escalated.',measure:'Track complete packets, missing evidence, policy matches, exceptions, approval time, reopened cases, and avoidable customer follow-ups.'}),
 blog({slug:'outsourcing-small-business-vendor-onboarding-intake',title:'Build a Safe Vendor Onboarding Intake Lane for Outsourced Support',excerpt:'Collect vendor records consistently while reserving selection, compliance, and payment decisions.',lane:'vendor onboarding intake',record:'Keep the legal name supplied, contact, requested service, tax and banking document status, contract reference, and reviewer.',exception:'Bank changes, identity conflicts, sanctions questions, contractual terms, compliance judgments, and approval to buy require authorized review.',measure:'Report packets opened, complete fields, missing documents, mismatches, review aging, approved vendors, and returned packets.'}),
 blog({slug:'outsourcing-small-business-calendar-conflict-triage',title:'Use Outsourced Calendar Triage Without Giving Away Priority Decisions',excerpt:'Surface conflicts, travel constraints, and missing context while the owner chooses tradeoffs.',lane:'calendar conflict triage',record:'Record the invitation, organizer, participants, location, time zone, preparation need, travel buffer, and stated flexibility.',exception:'Executive priorities, confidential meetings, customer commitments, personal appointments, travel changes, and double bookings require the calendar owner.',measure:'Count conflicts found, missing context, proposals prepared, owner decisions, late changes, incorrect moves, and preparation gaps.'}),
 blog({slug:'outsourcing-small-business-renewal-notice-tracking',title:'Track Contract Renewal Notices Without Outsourcing the Renewal Decision',excerpt:'Monitor dates and assemble terms while keeping negotiation, cancellation, and signature authority internal.',lane:'contract renewal notice tracking',record:'Store the agreement identifier, counterparty, term, notice window, renewal language, owner, source file, and last verified date.',exception:'Ambiguous terms, price changes, auto-renewal disputes, termination notices, legal interpretation, and signature requests must be escalated.',measure:'Track agreements covered, verified dates, upcoming windows, missing files, owner decisions, late reviews, and corrected records.'}),
 blog({slug:'outsourcing-small-business-crm-duplicate-review',title:'Outsource CRM Duplicate Review Without Losing Customer History',excerpt:'Prepare evidence for merges while protecting ownership, consent, and active opportunities.',lane:'CRM duplicate review',record:'Retain both record IDs, source, contact fields, consent notes, owners, open activity, account links, and change history.',exception:'Conflicting identities, active deals, privacy requests, separate legal entities, disputed ownership, and destructive merges need approval.',measure:'Measure pairs reviewed, clear matches, conflicts, approved merges, prevented false merges, restored records, and owner review time.'}),
 blog({slug:'outsourcing-small-business-purchase-request-packets',title:'Prepare Purchase Request Packets Before Anyone Places an Order',excerpt:'Gather specifications, comparisons, and budget evidence without delegating spending authority.',lane:'purchase request preparation',record:'Capture the requester, business need, specification, quantity, required date, candidate suppliers, quoted terms, and budget reference.',exception:'New suppliers, bank detail changes, sole-source requests, regulated items, conflicts of interest, and commitments need owner review.',measure:'Count complete requests, missing specifications, comparable quotes, exceptions, approval aging, rejected requests, and order corrections.'}),
 blog({slug:'outsourcing-small-business-review-response-drafts',title:'Draft Customer Review Responses Without Inventing Public Claims',excerpt:'Prepare measured replies from verified records while the business owns remedies and public statements.',lane:'customer review response drafting',record:'Keep the public review, platform, date, account match status, service record, prior contact, approved tone, and response owner.',exception:'Legal threats, privacy details, discrimination claims, safety issues, refunds, disputed facts, and media attention require escalation.',measure:'Track reviews received, records matched, drafts prepared, owner edits, response time, privacy catches, and cases moved offline.'}),
 blog({slug:'outsourcing-small-business-job-applicant-scheduling',title:'Outsource Applicant Scheduling Without Delegating Hiring Judgment',excerpt:'Coordinate interviews and candidate updates while protecting evaluation and employment decisions.',lane:'applicant interview scheduling',record:'Retain the role, candidate identifier, approved stage, interviewer availability, time zone, accommodation route, and message template.',exception:'Selection questions, compensation, accommodations, background information, complaints, conflicts, and rejection decisions stay with authorized staff.',measure:'Report invitations, confirmed interviews, reschedules, no-shows, response aging, template exceptions, and scheduling errors.'}),
 blog({slug:'outsourcing-small-business-expense-receipt-followup',title:'Set Up Outsourced Expense Receipt Follow-Up Before Month End',excerpt:'Chase missing support and label records without deciding tax treatment or reimbursement.',lane:'expense receipt follow-up',record:'Capture the transaction ID, date, amount, cardholder, merchant, submitted purpose, receipt status, project, and accounting period.',exception:'Personal charges, disputed transactions, tax classification, policy exceptions, altered receipts, and reimbursement decisions need finance review.',measure:'Track transactions reviewed, receipts obtained, missing explanations, duplicates, disputed items, aging, and reviewer corrections.'}),
 blog({slug:'outsourcing-small-business-website-change-requests',title:'Route Website Change Requests Without Letting the Queue Rewrite the Site',excerpt:'Clarify requested edits, evidence, and approvals before public content changes.',lane:'website change request intake',record:'Save the requested URL, exact current text or behavior, proposed change, reason, requester, supporting source, and desired timing.',exception:'Pricing, legal language, credentials, testimonials, tracking, account access, redirects, and deletion of live pages require named approval.',measure:'Count requests, complete briefs, duplicate requests, approval waits, rejected changes, defects after release, and emergency reversions.'}),
 blog({slug:'outsourcing-small-business-stockout-followup',title:'Outsource Stockout Follow-Up Without Promising Inventory',excerpt:'Assemble supplier and order facts while keeping substitutions and customer promises controlled.',lane:'stockout follow-up',record:'Preserve the item, location, system balance, open orders, supplier update, affected customer orders, and last physical check.',exception:'Substitutions, expedited freight, partial fulfillment, customer compensation, allocation rules, and inventory adjustments need owner approval.',measure:'Track stockouts, source confirmations, affected orders, update aging, approved substitutions, incorrect promises, and repeat items.'}),
];

type ResearchSeed={slug:string;title:string;excerpt:string;question:string;method:string;finding:string;limits:string};
function research(s:ResearchSeed){return {...s,published,imagePath:researchImage,body:[
 `Research question. ${s.question} The unit of analysis is one outsourced work item and its linked intake, instruction, output, exception, approval, and review records. The purpose is to support a small-business operating choice, not to rank workers or claim that outsourcing alone causes an outcome.`,
 `Evidence scope and method. ${s.method} The design uses operational records generated during ordinary work. It separates preparation by a Philippines-based specialist from decisions retained by the business. Before observing results, define eligibility, exclusions, defect categories, and the review window. Retain missing and returned items so the sample does not contain only successful cases.`,
 `Evidence context. The U.S. Small Business Administration's management guidance supports documented operating practices. NIST Cybersecurity Framework 2.0 supplies a risk-management frame for access and information handling. Federal Trade Commission business guidance emphasizes reasonable safeguards and accurate representations. Google Search Central guidance supports people-first, useful content rather than material produced only to attract search visits. These sources inform the controls; they do not prove that one staffing model will work for every business.`,
 `Measured finding to test. ${s.finding} Report the numerator and denominator together, show aging distributions, and separate routine items from exceptions. Compare the first supervised sample with a later sample only when the rules and population remain comparable. Review high-consequence cases individually instead of allowing an average to hide them.`,
 `Interpretation. A favorable observation means the tested lane met its predeclared controls during the measured window. It does not establish general productivity, savings, employee quality, or customer satisfaction. Owner review time matters because a queue that appears fast may simply shift reconstruction work to the manager. Pair speed with accuracy, traceability, exception handling, and reversibility.`,
 `Limitations. ${s.limits} Operational data may contain recording errors, reviewer judgments may differ, and small samples are unstable. Tool changes, seasonality, queue mix, and training can alter later results. A missing record should be treated as missing evidence, not a pass. Any public claim would need its own substantiation beyond this internal design.`,
 `Decision rule. Expand only if the defined controls pass, exceptions reach the correct owner, access stays within scope, and sampled records can be reconstructed without private memory. Otherwise revise the intake, examples, permissions, or boundary and run another limited sample. Preserve the decision and its evidence so a later reviewer can understand why the lane changed.`
 ] as const};}

export const septemberFourResearchBatch=[
 research({slug:'september-4-research-outsourced-intake-completeness',title:'Research: Intake Completeness in Outsourced Small-Business Work',excerpt:'A bounded audit design for testing whether required source fields are present before work begins.',question:'What share of eligible items enters an outsourced lane with every required source field present and verifiable?',method:'Sample consecutive eligible items, freeze a field dictionary, and independently check each field against its source before the operator begins.',finding:'Test whether complete intake is associated with fewer clarification loops and less owner reconstruction time, without treating association as causation.',limits:'Teams may change behavior when observed, field requirements may be overinclusive, and different queue types should not be pooled without justification.'}),
 research({slug:'september-4-research-exception-escalation-latency',title:'Research: Exception Escalation Latency in Outsourced Operations',excerpt:'A route-level study design for measuring how quickly consequential exceptions reach an authorized owner.',question:'How long do defined exceptions remain in an outsourced queue before the correct decision owner receives a complete packet?',method:'Timestamp trigger recognition, packet completion, owner notification, response, and final disposition for consecutive exceptions.',finding:'Test whether named owners and required packet fields reduce unowned waiting while preserving evidence quality.',limits:'Timestamps do not show attention quality, urgent cases can distort averages, and notification does not prove that an owner understood the issue.'}),
 research({slug:'september-4-research-review-sample-defect-detection',title:'Research: Defect Detection in Review Samples for Outsourced Work',excerpt:'A practical design for comparing random checks with consequence-based review.',question:'Which review mix finds material defects while keeping owner review effort visible?',method:'Preclassify consequence, review all high-consequence items, randomly sample routine items, and record defect type, reviewer time, and corrective action.',finding:'Compare detection yield and review minutes across the two strata rather than reporting one blended accuracy percentage.',limits:'Rare defects need larger samples, reviewers can disagree, and detection during review does not measure defects missed by every reviewer.'}),
 research({slug:'september-4-research-owner-reconstruction-time',title:'Research: Owner Reconstruction Time After Outsourced Handoffs',excerpt:'An observational method for measuring hidden management effort in supposedly completed work.',question:'How much owner time is required to understand and decide a completed or escalated outsourced item?',method:'Time a structured review of consecutive handoffs and classify minutes spent reading the packet, locating missing sources, asking questions, and making the decision.',finding:'Test whether source-linked handoffs reduce search and clarification time while maintaining decision quality.',limits:'Timing can influence behavior, complex cases legitimately take longer, and shorter review is not better if evidence or judgment quality declines.'}),
 research({slug:'september-4-research-access-scope-conformance',title:'Research: Access-Scope Conformance for Outsourced Small-Business Roles',excerpt:'A least-privilege audit design linking assigned tasks to actual tool permissions.',question:'Do active permissions for an outsourced role match the documented actions required by its current work lane?',method:'Build a task-to-permission matrix, inspect named accounts and group membership, sample activity logs, and route every unexplained permission to its owner.',finding:'Measure accounts reviewed, justified permissions, excess permissions, missing controls, remediation time, and repeat findings after scope changes.',limits:'An entitlement audit cannot prove credentials were never shared, logs may be incomplete, and legitimate emergency access needs separate interpretation.'}),
];
