const published = '2026-09-07' as const;
const blogImage = '/filipino-support-workspace.jpg';
const researchImage = '/aug31-heroes/research-claim-map.png';

type BlogSeed = {slug:string;title:string;excerpt:string;lane:string;sourceRecord:string;boundary:string;exception:string;metric:string};
function blog(seed: BlogSeed) { return {...seed, publicationDate: published, imagePath: blogImage, sections: [
  ['Start with one inspectable outcome', `Treat ${seed.lane} as a defined operating lane, not a loose request for help. The intake should identify the source, the expected prepared output, the deadline, the reviewer, and the condition that makes the item complete. ${seed.sourceRecord} Begin with a small consecutive sample that includes ordinary and incomplete cases. This gives the owner a fair view of the work and gives the specialist examples grounded in the business rather than assumptions.`],
  ['Preserve the evidence trail', `Keep the original request beside every summary, label, and draft. Record identifiers, timestamps, attachments, and the instruction version used. Mark an absent value as missing and conflicting values as a conflict; never make the record look complete by guessing. For ${seed.lane}, a concise handoff should let another person trace the prepared result back to its source without relying on private chat or memory.`],
  ['Separate preparation from authority', `${seed.boundary} Use named accounts and the narrowest permissions that support preparation. If a system cannot separate drafting from approval, route the proposed action to a reviewer or keep that action outside the lane. The business remains accountable for commitments, policy interpretations, money movement, access changes, and consequential public statements.`],
  ['Give exceptions a visible route', `${seed.exception} Record the triggering fact, supporting evidence, safe temporary state, requested decision, and named owner. Do not reward a low exception count: hidden exceptions make a queue look efficient while shifting risk to customers and managers. Review repeated exceptions for a missing intake field, unclear example, outdated rule, or permission problem.`],
  ['Review the first week against examples', `Inspect every high-consequence item and a random sample of routine ${seed.lane} work. Compare the source, instruction, prepared output, approval trail, and final state. Return corrections with the exact record and a worked example. If the same defect returns, improve the system that produced it instead of relying on a general reminder to be careful.`],
  ['Measure without hiding rework', `${seed.metric} Show the denominator, aging, blocked work, returned items, corrections, and owner review time. A completion number alone cannot show whether the lane is dependable. Expand only the stable portion after another reviewer can reconstruct both a completed item and an exception. Keep the launch reversible so the business can narrow or pause the lane when evidence is incomplete.`],
] as const}; }

export const septemberSevenBlogBatch = [
  blog({slug:'outsourcing-small-business-customer-address-change-intake',title:'Outsource Customer Address Change Intake Without Moving the Wrong Record',excerpt:'Prepare verified address-change requests while keeping identity checks and final account edits controlled.',lane:'customer address change intake',sourceRecord:'Capture the customer-supplied request, account identifier, current address, proposed address, channel, effective date, and verification status.',boundary:'The specialist may assemble and compare the request, but identity exceptions and the final account change need the business’s approved control.',exception:'Mismatched identities, returned mail, shared accounts, fraud indicators, legal holds, and requests affecting tax or service eligibility require escalation.',metric:'Track requests received, verified packets, missing fields, identity conflicts, approved changes, incorrect edits, and review time.'}),
  blog({slug:'outsourcing-small-business-warranty-claim-packets',title:'Build Outsourced Warranty Claim Packets Without Promising Coverage',excerpt:'Collect purchase and defect evidence while reserving eligibility and remedy decisions for authorized staff.',lane:'warranty claim preparation',sourceRecord:'Retain the order, product, serial number, purchase date, stated problem, photos, prior contact, and applicable warranty version.',boundary:'Support may organize facts and identify the relevant terms; it must not decide coverage, replacement, repair, refund, or fault.',exception:'Safety reports, expired coverage, altered products, missing serials, repeat claims, disputed facts, and requested exceptions go to the warranty owner.',metric:'Report complete packets, evidence gaps, policy matches, exceptions, decision aging, reopened claims, and correction reasons.'}),
  blog({slug:'outsourcing-small-business-project-status-chasing',title:'Use Outsourced Project Status Chasing Without Inventing Progress',excerpt:'Gather dated updates from task owners while keeping forecasts and delivery commitments with project leadership.',lane:'project status follow-up',sourceRecord:'Record the project, work item, named owner, last verified state, dependency, requested update, due date, and source link.',boundary:'The specialist may request and organize updates, but cannot declare work complete or change a customer-facing forecast without approval.',exception:'Conflicting updates, missed milestones, scope changes, blocked dependencies, unresponsive owners, and customer commitments need the project lead.',metric:'Count updates requested, verified responses, unresolved blockers, stale records, forecast changes, corrections, and owner follow-up minutes.'}),
  blog({slug:'outsourcing-small-business-certificate-expiry-tracking',title:'Track Certificate Expiry Dates Without Outsourcing Compliance Judgment',excerpt:'Maintain evidence-backed renewal reminders while qualified owners decide acceptability and compliance.',lane:'certificate expiry tracking',sourceRecord:'Preserve the certificate file, issuer, holder, identifier, covered activity, issue date, expiry date, source, and last verification.',boundary:'Support can transcribe dates and prepare reminders; acceptance, waiver, interpretation, and continued-work decisions stay with the qualified owner.',exception:'Unreadable files, conflicting dates, changed scope, lapsed coverage, unknown issuers, and regulated requirements must be escalated.',metric:'Track certificates inventoried, dates verified, reminders sent, missing evidence, expiries, owner decisions, and corrected entries.'}),
  blog({slug:'outsourcing-small-business-customer-consent-log-review',title:'Outsource Customer Consent Log Review Without Assuming Permission',excerpt:'Compare consent records with approved requirements while privacy decisions remain with the business.',lane:'customer consent log review',sourceRecord:'Keep the customer identifier, channel, consent wording, version, timestamp, collection source, withdrawal history, and linked activity.',boundary:'The specialist may flag absent or inconsistent records but may not infer consent, restore withdrawn permission, or interpret privacy law.',exception:'Missing proof, conflicting systems, minors, sensitive data, deletion requests, complaints, and cross-border questions require the privacy owner.',metric:'Measure records reviewed, verified consent entries, gaps, conflicts, withdrawals, suppressed actions, corrections, and escalation aging.'}),
  blog({slug:'outsourcing-small-business-delivery-proof-matching',title:'Match Delivery Proof to Orders Without Closing Customer Disputes',excerpt:'Link carrier evidence to order records while keeping liability and customer remedies under review.',lane:'delivery proof matching',sourceRecord:'Capture the order, shipment, carrier event, delivery timestamp, location detail, signature or photo status, and customer message.',boundary:'Support may match and summarize carrier records; it cannot decide liability, deny a claim, reship, refund, or make a customer promise.',exception:'Address discrepancies, damaged goods, unsafe delivery notes, missing signatures, high-value orders, chargebacks, and disputed proof go to an owner.',metric:'Track shipments matched, missing proof, identity conflicts, disputes, decision time, reopened cases, and incorrect matches.'}),
  blog({slug:'outsourcing-small-business-subscription-cancellation-intake',title:'Prepare Subscription Cancellation Requests Without Changing Terms',excerpt:'Organize cancellation facts and deadlines while retaining authority over refunds, contracts, and exceptions.',lane:'subscription cancellation intake',sourceRecord:'Retain the subscriber, plan, request wording, channel, request time, renewal date, notice rule, payment status, and prior support history.',boundary:'The specialist may prepare the request and approved acknowledgment; refunds, term interpretation, retention offers, and account closure require authorization.',exception:'Disputed dates, annual terms, chargebacks, hardship requests, legal threats, data deletion, and service failures must be escalated.',metric:'Report requests received, complete packets, notice-window matches, exceptions, decision aging, refunds approved, and repeat contacts.'}),
  blog({slug:'outsourcing-small-business-maintenance-request-triage',title:'Outsource Maintenance Request Triage Without Diagnosing the Hazard',excerpt:'Capture property and equipment issues consistently while qualified people assess safety and authorize work.',lane:'maintenance request triage',sourceRecord:'Record the site, asset, reporter, observed symptoms, time discovered, photos, access constraints, occupancy impact, and prior work order.',boundary:'Support may categorize and route facts but cannot diagnose a hazard, instruct unsafe action, select a contractor, or approve spending.',exception:'Fire, gas, electrical, structural, security, injury, water intrusion, accessibility, and repeat-failure reports use the emergency owner path.',metric:'Track requests, complete intake, emergency escalations, routing time, duplicate reports, owner decisions, and misclassified cases.'}),
  blog({slug:'outsourcing-small-business-sales-demo-preparation',title:'Use Outsourced Sales Demo Preparation Without Fabricating Product Claims',excerpt:'Assemble account context and approved materials while sales owners control promises and fit judgments.',lane:'sales demo preparation',sourceRecord:'Keep the prospect, meeting, stated use case, participants, approved product facts, requested integrations, source links, and open questions.',boundary:'Support may prepare the brief and approved assets; pricing, capability promises, roadmap statements, security answers, and fit decisions remain with sales owners.',exception:'Regulated use, custom terms, unavailable features, competitor claims, security questionnaires, discounts, and public references need review.',metric:'Count briefs prepared, missing discovery facts, unsupported requests, owner edits, late changes, reused assets, and post-demo corrections.'}),
  blog({slug:'outsourcing-small-business-donation-request-screening',title:'Screen Donation Requests Without Delegating the Giving Decision',excerpt:'Create consistent request packets while leadership retains budget, eligibility, and reputational decisions.',lane:'donation request screening',sourceRecord:'Capture the requesting organization, contact, purpose, amount or goods requested, event date, beneficiary, documents, and relationship history.',boundary:'The specialist may check completeness against published criteria; approval, rejection, tax treatment, messaging, and exceptions belong to leadership.',exception:'Political activity, personal benefit, urgent payment, identity mismatch, restricted causes, publicity commitments, and conflicts of interest require escalation.',metric:'Track requests, complete packets, criteria gaps, exceptions, decisions, response aging, duplicate requests, and reviewer time.'}),
  blog({slug:'outsourcing-small-business-training-record-administration',title:'Administer Training Records Without Certifying Competence',excerpt:'Maintain completion evidence and reminders while managers own qualification and work-assignment decisions.',lane:'training record administration',sourceRecord:'Retain the worker, course, version, provider, assigned date, completion evidence, score if supplied, expiry rule, and manager.',boundary:'Support can log evidence and send approved reminders; it cannot certify competence, waive training, or assign regulated work.',exception:'Missing evidence, expired credentials, failed assessments, accommodations, disputed attendance, role changes, and safety-sensitive duties need the manager.',metric:'Measure assignments, verified completions, overdue items, expiring records, evidence gaps, corrections, and manager decisions.'}),
  blog({slug:'outsourcing-small-business-price-list-change-prep',title:'Prepare Price List Changes Without Publishing an Unapproved Price',excerpt:'Reconcile approved source data and page targets while pricing authority stays with the business.',lane:'price list change preparation',sourceRecord:'Keep the approved price source, item or service identifier, current displayed price, proposed price, effective date, channel, requester, and approval status.',boundary:'Support may compare fields and stage drafts; it must not choose prices, interpret taxes, alter discounts, or publish before named approval.',exception:'Conflicting sources, bundled offers, regulated fees, active quotes, currency changes, customer-specific terms, and missing approval stop the change.',metric:'Track lines checked, differences found, drafts staged, approval waits, publishing errors, rollbacks, and channels reconciled.'}),
];

type ResearchSeed = {slug:string;title:string;excerpt:string;question:string;method:string;finding:string;limits:string};
function research(s: ResearchSeed) { return {...s, published, imagePath: researchImage, body: [
  `Research question. ${s.question} The unit of analysis is one eligible outsourced work item and its linked source, instruction, prepared output, exception, approval, and review record. The study supports a bounded operating decision for a small business; it does not rank individuals or assume that outsourcing caused an outcome.`,
  `Method and evidence scope. ${s.method} Define eligibility, exclusions, observation window, defect categories, and stop conditions before reviewing results. Include incomplete, corrected, blocked, and escalated items so the sample is not limited to clean completions. Preserve the original evidence and record reviewer disagreements.`,
  `Control context. The U.S. Small Business Administration provides general management guidance; NIST Cybersecurity Framework 2.0 supplies a risk-management structure; Federal Trade Commission business guidance emphasizes reasonable safeguards and accurate representations; and Google Search Central describes people-first content. These sources frame controls but do not validate a provider, staffing model, or local result.`,
  `Measured finding to test. ${s.finding} Report counts with denominators, aging distributions, exception classes, rework, and owner review minutes. Separate routine and high-consequence cases. Do not turn an observed association, short trial, or process improvement into a causal or universal claim.`,
  `Interpretation. A favorable result means only that the defined lane met its predeclared controls during the measured window. Speed must be considered with accuracy, traceability, access boundaries, reversibility, and the effort required from the owner. A fast queue that hides reconstruction or exceptions is not a successful result.`,
  `Limitations. ${s.limits} Operational records can contain errors, reviewers can disagree, and changing tools, instructions, staffing, seasonality, or queue mix can alter later results. Missing evidence is not a pass. Public performance or savings claims would require separate substantiation.`,
  `Decision rule. Expand only when the sample meets the stated threshold, consequential exceptions reach the correct owner, and a second reviewer can reconstruct both a completed and a held item. Otherwise revise the intake, examples, permissions, or approval boundary and repeat a limited test. Preserve the decision and evidence for later comparison.`
] as const}; }

export const septemberSevenResearchBatch = [
  research({slug:'september-7-research-source-link-survival-through-handoffs',title:'Research: Do Source Links Survive Outsourced Handoffs?',excerpt:'A bounded audit of whether decision evidence remains reachable after work changes hands.',question:'What share of prepared items retains a working, specific source link through operator, reviewer, and owner handoffs?',method:'Sample consecutive eligible items, test every recorded link at each handoff, and classify missing, inaccessible, overly broad, superseded, and intact sources.',finding:'Test whether a required source field and handoff checklist are associated with fewer owner searches and fewer returned packets.',limits:'Link availability can change after review, access rights differ by reviewer, and a working link does not prove that the source supports the summary.'}),
  research({slug:'september-7-research-reopened-work-after-approval',title:'Research: Reopened Work After Outsourced Preparation and Approval',excerpt:'An observational design for learning why accepted work returns to the queue.',question:'How often does approved outsourced preparation reopen, and which documented causes account for the return?',method:'Follow a defined cohort beyond approval, preserve the first accepted version, and code returns as source change, instruction gap, preparation defect, approval error, or unrelated later event.',finding:'Test whether versioned sources and explicit acceptance criteria reduce preventable reopenings without hiding legitimate later changes.',limits:'Observation windows can miss late returns, cause coding involves judgment, and reopening may reflect healthy correction rather than poor quality.'}),
  research({slug:'september-7-research-permission-scope-drift',title:'Research: Permission-Scope Drift in Outsourced Small-Business Lanes',excerpt:'A repeatable review of whether tool access remains aligned with assigned work.',question:'How often do active permissions exceed the documented actions required by an outsourced lane?',method:'Freeze a task-to-permission matrix, compare named accounts with actual role assignments, and independently classify required, unused, inherited, and unexplained access.',finding:'Test whether scheduled access reviews and named grant owners reduce unexplained permissions while preserving task completion.',limits:'Application labels may not reveal effective privileges, temporary access may be missed, and the design does not establish that excess access caused harm.'}),
  research({slug:'september-7-research-owner-decision-packet-completeness',title:'Research: Completeness of Owner Decision Packets From Outsourced Work',excerpt:'A field-level study of whether escalations arrive with enough evidence for an owner to act.',question:'What proportion of escalated items reaches the named owner with every predeclared decision field and supporting source?',method:'Define required fields by exception type, sample consecutive escalations, and have a second reviewer compare each packet with original records before the owner decides.',finding:'Test whether complete packets are associated with fewer clarification loops and less reconstruction time, while reporting consequence separately.',limits:'Field lists may be overinclusive, owner familiarity can affect review time, and association between completeness and speed does not establish causation.'}),
  research({slug:'september-7-research-routine-change-detection',title:'Research: Detecting Instruction Changes in Outsourced Routines',excerpt:'A controlled audit of whether operators use the current approved procedure after a revision.',question:'After a routine changes, what share of eligible items uses the correct instruction version and preserves evidence of the transition?',method:'Record the effective time and affected population, sample items immediately before and after the change, and compare cited versions, outputs, questions, and corrections.',finding:'Test whether explicit effective dates, archived versions, and change acknowledgments reduce use of superseded instructions.',limits:'Small post-change samples are unstable, simultaneous tool changes can confound results, and acknowledgment does not prove correct understanding.'}),
];
