export type ServiceRecord = {
  slug: string;
  title: string;
  summary: string;
  buyerProblem: string;
  tasks: readonly string[];
  deliverables: readonly string[];
  tools: readonly string[];
  boundaries: readonly string[];
  launch: readonly string[];
  measures: readonly string[];
  faqs: readonly { question: string; answer: string }[];
  illustration: string;
  illustrationAlt: string;
};

const majorServices: ServiceRecord[] = [
  {
    slug: 'operations-support',
    title: 'Operations Support',
    summary: 'Philippines-based operations support for recurring task tracking, procedure upkeep, vendor follow-up, and owner-ready weekly reporting.',
    buyerProblem: 'Recurring work keeps returning to the owner because deadlines, handoffs, and exceptions live across inboxes and disconnected tools. The owner spends the week chasing status instead of reviewing a reliable operating picture.',
    tasks: ['Turn approved recordings and notes into usable procedures', 'Maintain task boards with owners, due dates, dependencies, and source links', 'Follow up with staff and vendors using approved messages', 'Prepare a weekly summary of completed work, overdue items, blockers, and decisions needed'],
    deliverables: ['Current procedure library with change dates', 'Daily task and exception queue', 'Vendor follow-up log with response history', 'Weekly owner review packet'],
    tools: ['Asana', 'Trello', 'Monday', 'ClickUp', 'Google Workspace', 'Microsoft 365', 'Slack'],
    boundaries: ['The specialist may organize records and send approved follow-ups.', 'Pricing, refunds, staffing decisions, contract changes, and unusual commitments stay with the owner.', 'Missing sources, conflicting instructions, and policy exceptions stop for review.'],
    launch: ['Choose one recurring workflow and identify its business owner', 'Share one correct example and one exception example', 'Grant only the accounts and permissions needed for that workflow', 'Review the first five completed items before expanding the lane'],
    measures: ['On-time completion rate', 'Open exceptions by age', 'Items returned for correction', 'Owner review time'],
    faqs: [{ question: 'What operations work should a small business outsource first?', answer: 'Start with repeatable coordination, task updates, procedure maintenance, and routine follow-up. Keep work that changes money, policy, contracts, or customer remedies with the owner until written approval rules are tested.' }, { question: 'How does the owner avoid creating another job to manage?', answer: 'Use one queue, a written finish line, linked source records, and a scheduled review. A useful support lane should make exceptions easier to see instead of creating a second hidden workflow.' }],
    illustration: '/illustrations/getillustrations/goodle-business/owner-approved-remote-handoff.svg',
    illustrationAlt: 'Illustration of a small business owner reviewing an organized operations handoff',
  },
  {
    slug: 'customer-support',
    title: 'Customer Support',
    summary: 'Philippines-based customer support for inbox triage, approved replies, ticket notes, follow-up, and controlled escalation.',
    buyerProblem: 'Customer messages wait while the owner switches between delivery work and the inbox. A rushed handoff can be just as costly when the support person lacks approved answers or makes refund and account decisions alone.',
    tasks: ['Classify email, chat, and helpdesk conversations by issue and urgency', 'Prepare or send replies from approved guidance', 'Maintain accurate ticket notes and customer context', 'Route billing, privacy, legal, and service-recovery exceptions to the named owner'],
    deliverables: ['Daily queue and aging report', 'Reviewed reply library', 'Escalation log with owner status', 'Weekly issue summary'],
    tools: ['Gmail', 'Outlook', 'Zendesk', 'Freshdesk', 'Gorgias', 'Intercom', 'Shopify'],
    boundaries: ['Routine factual replies may use approved templates and records.', 'Refunds, credits, account recovery, legal threats, and policy exceptions require named approval.', 'The specialist never invents order status, guarantees, or customer history.'],
    launch: ['Review a recent sample of customer conversations', 'Group common questions and approve initial replies', 'Write the escalation map and response targets', 'Run the first shift in draft mode and review every exception'],
    measures: ['First response time', 'Aging unresolved conversations', 'Escalation accuracy', 'Reopened or corrected replies'],
    faqs: [{ question: 'Can a support specialist approve refunds?', answer: 'Not by default. The specialist can gather the order details and prepare a reply, while a named owner approves the refund or exception unless a narrow written rule has been tested.' }, { question: 'Which support channel should move first?', answer: 'Start with the channel that has reliable records and repeatable questions. Email or an established helpdesk is usually easier to review than unlogged calls or scattered direct messages.' }],
    illustration: '/illustrations/getillustrations/humano-scenes/small-business-role-planning.svg',
    illustrationAlt: 'Illustration of an organized customer support and follow-up workflow',
  },
  {
    slug: 'administrative-support',
    title: 'Administrative Support',
    summary: 'Philippines-based administrative support for inboxes, calendars, records, documents, reminders, and owner-ready follow-up.',
    buyerProblem: 'Small administrative requests interrupt sales and service work throughout the day. The owner needs help that can organize the queue without moving meetings, sending sensitive messages, or changing records beyond clear permission.',
    tasks: ['Sort inbox messages and prepare draft replies', 'Maintain calendars, meeting notes, and reminder queues', 'Update approved CRM fields, spreadsheets, and document folders', 'Prepare routine forms and meeting materials from source records'],
    deliverables: ['Daily inbox and reminder summary', 'Accurate calendar with preparation notes', 'Updated records with source links', 'Organized document and follow-up queue'],
    tools: ['Google Workspace', 'Microsoft 365', 'HubSpot', 'Salesforce', 'Calendly', 'Dropbox', 'Notion'],
    boundaries: ['Customer-facing messages begin in draft mode.', 'The owner keeps approval for sensitive messages, calendar conflicts, access changes, and record deletion.', 'Unclear identity, missing source data, and conflicting dates are escalated.'],
    launch: ['Select one inbox, one calendar, and one record view', 'Agree on labels, priorities, and a finished example', 'Limit access and test each permitted action', 'Review the first week with a short accuracy scorecard'],
    measures: ['Inbox items triaged', 'Calendar conflicts caught', 'Record accuracy', 'Follow-ups completed on time'],
    faqs: [{ question: 'What administrative tasks are safest to delegate first?', answer: 'Inbox sorting, calendar preparation, reminder tracking, document formatting, and bounded data updates are practical starting points when source records and approval limits are clear.' }, { question: 'Should an administrative specialist send messages as the owner?', answer: 'Begin with drafts and approved templates. Sending authority should expand only for narrow message types after the owner has reviewed enough accurate examples.' }],
    illustration: '/illustrations/getillustrations/humano-scenes/small-business-role-planning.svg',
    illustrationAlt: 'Illustration of a small team planning an administrative support role',
  },
  {
    slug: 'reporting-quality-assurance',
    title: 'Reporting and Quality Assurance',
    summary: 'Philippines-based reporting and quality support for source-linked scorecards, sample checks, exception logs, and owner decisions.',
    buyerProblem: 'Problems surface late because completed work, source records, errors, and exceptions are not reviewed in one place. The owner needs evidence that work is accurate without repeating every task personally.',
    tasks: ['Gather approved operating measures from named systems', 'Check a dated sample against a short quality checklist', 'Flag missing fields, conflicting records, late work, and broken handoffs', 'Prepare a weekly summary that separates facts from owner decisions'],
    deliverables: ['Source-linked weekly scorecard', 'Quality sample ledger', 'Exception and correction queue', 'Decision-ready owner summary'],
    tools: ['Google Sheets', 'Excel', 'Looker Studio', 'Airtable', 'HubSpot', 'Asana', 'Notion'],
    boundaries: ['The specialist reports what the records show and identifies gaps.', 'Interpretation, targets, disciplinary decisions, and policy changes stay with the owner.', 'A missing source is labeled missing rather than estimated or invented.'],
    launch: ['Choose five measures the owner already uses', 'Document each source and calculation rule', 'Build the first report manually and review a sample', 'Record corrections before considering automation'],
    measures: ['Source completeness', 'Sample pass rate', 'Correction rate', 'Age of unresolved exceptions'],
    faqs: [{ question: 'Can an outsourced specialist own business reporting?', answer: 'The specialist can gather, check, and present approved measures. The owner or manager remains responsible for interpreting results and deciding what the business should change.' }, { question: 'What belongs in a useful quality checklist?', answer: 'Use a short list tied to real risks: correct source, complete required fields, approved action, accurate status, and a visible escalation when the item falls outside the rule.' }],
    illustration: '/illustrations/getillustrations/goodle-business/owner-approved-remote-handoff.svg',
    illustrationAlt: 'Illustration of a reviewed small business reporting and quality workflow',
  },
  {
    slug: 'finance-accounting',
    title: 'Finance and Bookkeeping Administration',
    summary: 'Philippines-based preparation support for invoices, receipts, transaction records, reconciliation queues, and owner or adviser review.',
    buyerProblem: 'Receipts, invoice records, and follow-up accumulate between review periods. The business needs an orderly record trail without delegating payment release, tax positions, account changes, or professional accounting judgment.',
    tasks: ['Collect and label approved source documents', 'Prepare transaction and reconciliation queues for review', 'Track missing receipts, invoice status, and unresolved differences', 'Maintain month-end checklists and supporting links'],
    deliverables: ['Organized source-document folder', 'Prepared bookkeeping review queue', 'Missing-record and exception log', 'Month-end owner or adviser packet'],
    tools: ['QuickBooks', 'Xero', 'Google Drive', 'Dropbox', 'Excel', 'Google Sheets'],
    boundaries: ['The specialist prepares records and flags differences.', 'Bank access changes, payment release, tax filings, accounting conclusions, and unusual classifications stay with the owner or qualified adviser.', 'The service is administrative support and is not tax, audit, or accounting advice.'],
    launch: ['Name the system of record and reviewer', 'Share examples of accepted supporting documents', 'Separate preparation access from approval and payment permissions', 'Review the first transaction sample and all exceptions'],
    measures: ['Documents matched to records', 'Missing documents by age', 'Review corrections', 'Open reconciliation exceptions'],
    faqs: [{ question: 'Is this a replacement for an accountant or bookkeeper?', answer: 'No. The service prepares and organizes records for review. Tax treatment, filing, accounting judgment, and advice remain with the business and its qualified professionals.' }, { question: 'Can the specialist release payments?', answer: 'No. Payment release and supplier account changes stay with named business approvers. Preparation and approval should remain separate.' }],
    illustration: '/illustrations/getillustrations/goodle-business/owner-approved-remote-handoff.svg',
    illustrationAlt: 'Illustration of a source-linked finance administration review',
  },
];

type FocusedSeed = Omit<ServiceRecord, 'launch' | 'illustration' | 'illustrationAlt'>;
const focusedSeeds: FocusedSeed[] = [
  { slug:'local-service-scheduling', title:'Local Service Scheduling', summary:'Scheduling support for service requests, approved availability, confirmations, reminders, and capacity exceptions.', buyerProblem:'Calls and booking requests interrupt field work, while incomplete details and overpromised windows create avoidable rescheduling.', tasks:['Capture service type, location, timing, and contact details','Offer only approved windows from the current capacity record','Send confirmations and reminders from approved language','Escalate unusual scope, travel, access, and capacity conflicts'], deliverables:['Complete booking record','Confirmation and reminder queue','Reschedule log','Capacity exception list'], tools:['Google Calendar','Outlook','Calendly','Jobber','Housecall Pro'], boundaries:['The specialist uses published availability and approved service details.','Quotes, compensation, capacity overrides, and unusual promises stay with the owner.','Incomplete addresses and conflicting windows stop for review.'], measures:['Complete booking rate','Reschedule rate','Confirmation completion','Capacity exceptions'], faqs:[{question:'Can the specialist quote a service price?',answer:'Only if the business supplies a current, unambiguous approved price for that exact service. Custom quotes and discounts return to the owner.'},{question:'What information should every request include?',answer:'Capture the service needed, address or area, preferred timing, contact details, and any access notes required by the business.'}] },
  { slug:'small-business-bookkeeping', title:'Small-Business Bookkeeping Preparation', summary:'Bookkeeping preparation for source documents, transaction queues, missing-record follow-up, and owner or adviser review.', buyerProblem:'The record trail falls behind because routine preparation competes with sales, service delivery, and owner review.', tasks:['Organize receipts and invoices by the approved filing rule','Prepare routine transaction records from complete sources','List missing documents and unresolved differences','Assemble the review packet without releasing money'], deliverables:['Prepared record queue','Source-document index','Missing-item log','Reviewer handoff'], tools:['QuickBooks','Xero','Google Drive','Excel','Google Sheets'], boundaries:['Preparation is separated from approval and payment.','Tax treatment, filings, journal approval, and accounting judgment stay with qualified reviewers.','Unsupported entries are flagged instead of guessed.'], measures:['Source match rate','Missing records','Reviewer corrections','Queue age'], faqs:[{question:'What can bookkeeping support prepare?',answer:'A specialist can organize source documents, prepare routine records, and identify missing support under the business process.'},{question:'What stays with the owner or adviser?',answer:'Payment release, filing, tax treatment, unusual classifications, and professional judgment remain with named approvers.'}] },
  { slug:'ecommerce-order-support', title:'Ecommerce Order Support', summary:'Order support for status questions, record checks, approved updates, fulfillment mismatches, and controlled escalation.', buyerProblem:'Routine order questions consume the team while delivery delays, return requests, and inventory mismatches need careful context.', tasks:['Check order and fulfillment records before replying','Prepare approved status and tracking updates','Tag returns, delays, address issues, and stock mismatches','Escalate refunds, guarantees, and policy exceptions'], deliverables:['Updated order queue','Customer reply record','Fulfillment exception log','Daily aging summary'], tools:['Shopify','WooCommerce','Gorgias','ShipStation','Zendesk'], boundaries:['The specialist reports verified order status only.','Refunds, credits, replacements, delivery guarantees, and policy exceptions require approval.','Conflicting carrier and store records are escalated.'], measures:['First response time','Order record accuracy','Exception age','Corrected replies'], faqs:[{question:'Can support promise a delivery date?',answer:'Only when the verified carrier or fulfillment record and approved policy support that statement.'},{question:'Can support approve returns?',answer:'The specialist can prepare the request and apply a narrow approved rule, while exceptions return to the owner.'}] },
  { slug:'lead-intake-administration', title:'Lead Intake Administration', summary:'Lead intake support for complete records, source attribution, approved routing, response reminders, and owner follow-up.', buyerProblem:'New inquiries arrive through several channels and lose context before the owner can qualify or respond.', tasks:['Capture required inquiry details without inventing facts','Record source, consent context, time, and requested service','Route leads using the approved territory or service rule','Maintain follow-up reminders and unresolved questions'], deliverables:['Complete lead record','Routing and follow-up queue','Missing-information list','Daily response summary'], tools:['HubSpot','Salesforce','Pipedrive','Gmail','Google Sheets'], boundaries:['The specialist records and routes information under written rules.','Qualification judgment, promises, pricing, and sensitive complaints stay with the owner.','Unknown facts remain unknown and visible.'], measures:['Required-field completion','Routing accuracy','Time to first owner action','Duplicate records'], faqs:[{question:'Can the specialist qualify a lead?',answer:'A specialist can apply objective written criteria, but subjective fit, pricing, and promises should remain with the owner.'},{question:'What should a lead record contain?',answer:'Use the contact details, source, request, time, consent context where needed, and the next named owner action.'}] },
  { slug:'invoice-follow-up', title:'Invoice Follow-Up', summary:'Invoice follow-up support for aging queues, approved reminders, dispute context, payment status, and owner exceptions.', buyerProblem:'Overdue records are reviewed inconsistently, but an aggressive or inaccurate reminder can damage a customer relationship.', tasks:['Reconcile the reminder queue to the current ledger','Send approved reminders with correct invoice references','Record replies, disputes, promises, and next dates','Escalate balance questions, concessions, and legal issues'], deliverables:['Current aging follow-up queue','Reminder record','Dispute and promise log','Owner exception summary'], tools:['QuickBooks','Xero','FreshBooks','Gmail','Outlook'], boundaries:['The specialist sends only approved factual reminders.','Balance changes, concessions, legal language, and collection decisions stay with the owner.','Disputed or inconsistent records stop for review.'], measures:['Records verified before contact','Follow-ups completed','Disputes escalated','Queue age'], faqs:[{question:'Can a specialist negotiate payment terms?',answer:'No. The specialist records the request and routes it to the named owner.'},{question:'What should an invoice reminder contain?',answer:'Use the verified customer, invoice identifier, amount shown in the source system, due date, approved payment instructions, and contact path.'}] },
  { slug:'customer-inbox-management', title:'Customer Inbox Management', summary:'Inbox management for triage, approved drafts, tags, reminders, aging reports, and sensitive-message escalation.', buyerProblem:'Important customer messages are mixed with routine questions, causing slow replies and missed owner decisions.', tasks:['Apply approved labels and priorities','Draft factual replies from source records and templates','Maintain follow-up reminders and thread status','Escalate privacy, billing, legal, and service-recovery issues'], deliverables:['Triaged inbox','Draft reply queue','Aging conversation report','Escalation record'], tools:['Gmail','Outlook','Front','Help Scout','Slack'], boundaries:['Sending authority starts narrow and evidence based.','Sensitive account, refund, legal, and policy messages require approval.','The specialist does not delete records or invent context.'], measures:['Inbox aging','Draft acceptance rate','Escalation accuracy','Missed follow-ups'], faqs:[{question:'Should the specialist send replies immediately?',answer:'Start in draft mode. Expand sending authority only for narrow, reviewed reply types.'},{question:'How is inbox quality reviewed?',answer:'Sample recent threads for correct source use, complete context, appropriate tone, and accurate escalation.'}] },
  { slug:'social-content-administration', title:'Social Content Administration', summary:'Content administration for approved calendars, source assets, draft preparation, scheduling, moderation queues, and review.', buyerProblem:'Publishing slips because files, approvals, captions, and schedules live in different places, while unsupported claims create brand risk.', tasks:['Maintain the approved content calendar and asset links','Prepare posts from approved facts and source materials','Schedule only owner-approved content','Route complaints, rights issues, and sensitive replies for review'], deliverables:['Current content calendar','Approval-ready draft queue','Published-post ledger','Moderation exception list'], tools:['Buffer','Hootsuite','Meta Business Suite','Canva','Google Drive'], boundaries:['The specialist coordinates approved content rather than inventing claims or testimonials.','Strategy, offers, guarantees, rights decisions, and sensitive public replies stay with the owner.','Missing approvals prevent scheduling.'], measures:['Posts prepared on time','Approval cycle time','Source completeness','Publishing corrections'], faqs:[{question:'Can a specialist create customer testimonials?',answer:'No. Testimonials require genuine customer evidence and approval. A specialist may format verified material without changing its meaning.'},{question:'Who approves published claims?',answer:'A named business owner reviews claims, offers, and sensitive statements before publication.'}] },
  { slug:'supplier-coordination', title:'Supplier Coordination', summary:'Supplier coordination for requests, confirmations, delivery updates, source records, and owner-approved exceptions.', buyerProblem:'Vendor updates are spread across email and calls, making it hard to see which commitment is current and who must decide next.', tasks:['Send approved requests and status follow-ups','Link confirmations and changes to the correct record','Track delivery dates, open questions, and dependencies','Escalate changed terms, substitutions, disputes, and approvals'], deliverables:['Supplier status ledger','Confirmation archive','Open-question queue','Exception handoff'], tools:['Gmail','Outlook','Google Sheets','Airtable','QuickBooks'], boundaries:['The specialist requests and records information.','Purchasing approval, changed terms, substitutions, disputes, and contract commitments stay with the owner.','Verbal changes are not treated as final without an approved record.'], measures:['Open requests by age','Confirmation completeness','Late updates','Exceptions awaiting decision'], faqs:[{question:'Can a specialist approve a substitute item?',answer:'No, unless the business has a narrow written substitution rule. Otherwise the option is documented for owner review.'},{question:'What makes vendor follow-up reviewable?',answer:'Keep the source request, latest response, promised date, open question, and named decision owner together.'}] },
  { slug:'review-response-drafting', title:'Review Response Drafting', summary:'Review response support for factual drafts, issue classification, privacy checks, approval records, and owner publication.', buyerProblem:'Public reviews need timely attention, but rushed replies can disclose private details, admit unsupported facts, or promise a remedy without authority.', tasks:['Classify routine, service-recovery, privacy, and legal-risk reviews','Gather approved facts without exposing customer records','Prepare neutral drafts for owner review','Maintain approval and publication status'], deliverables:['Draft response queue','Fact and source notes','Sensitive-review escalation list','Publication ledger'], tools:['Google Business Profile','Trustpilot','Yelp','Facebook','Google Docs'], boundaries:['The specialist prepares factual drafts only.','Compensation, admissions, legal issues, threats, and personal information require owner review.','No review, customer identity, or outcome is invented.'], measures:['Draft turnaround','Fact-check corrections','Sensitive reviews escalated','Approved responses published'], faqs:[{question:'Can the specialist post every response?',answer:'Routine approved responses may be posted only under a tested rule. Sensitive cases always require owner review.'},{question:'Should a public reply discuss the customer record?',answer:'No. Keep private details out of public replies and move account-specific discussion to an approved private channel.'}] },
  { slug:'owner-dashboard-reporting', title:'Owner Dashboard Reporting', summary:'Dashboard support for source-linked operating measures, refresh routines, exceptions, and concise owner review.', buyerProblem:'The owner spends review time collecting numbers instead of understanding what changed and which decisions are waiting.', tasks:['Refresh approved measures from named systems','Link each number to its source and date','Flag missing, conflicting, and unusual values','Prepare a short summary of changes and decisions needed'], deliverables:['Current dashboard','Source and refresh ledger','Data exception queue','Weekly decision summary'], tools:['Google Sheets','Excel','Looker Studio','Airtable','HubSpot'], boundaries:['The specialist gathers and checks approved measures.','Interpretation, forecasting, targets, and business decisions stay with the owner.','Missing values are labeled rather than estimated.'], measures:['Refresh completion','Source coverage','Data corrections','Owner review time'], faqs:[{question:'Can the specialist decide which numbers matter?',answer:'The owner chooses business measures and definitions. The specialist can maintain the agreed view and identify gaps.'},{question:'How often should a dashboard update?',answer:'Use a schedule that matches the decision. Daily queues may need daily refreshes, while strategic measures may be reviewed weekly or monthly.'}] },
];

const defaultLaunch = ['Name the workflow owner and the source system', 'Share one correct result and one exception example', 'Grant only the access needed for the first task lane', 'Review the first five items and update the written rule'];
const supportIllustration = '/illustrations/getillustrations/goodle-business/owner-approved-remote-handoff.svg';

export const fleetServices: readonly ServiceRecord[] = [
  ...majorServices,
  ...focusedSeeds.map((service) => ({
    ...service,
    launch: defaultLaunch,
    illustration: supportIllustration,
    illustrationAlt: `Illustration of an owner reviewing ${service.title.toLowerCase()} work`,
  })),
];
